### ISSUE TITLE
There's now no way to pass the path to build.gradle

### ISSUE THREAD

**Issue by pioneer32** [microsoft/appcenter-cli#1005]
We just started integrating CodePush into a hybrid application (an originally native application that React Native is injected in), so the path to `build.gradle` is not `android/app/build.gradle` (the default one used for most React Native applications). In our case the folder is named differently, for instance `android/our-app` and the whole path to `build.gradle` is `android/out-app/build.gradle`.

So, with 
```
"appcenter-cli": "2.6.3"
```
every our attempt to make a code-push release for Android fails with:
```
{ Error: ENOENT: no such file or directory, lstat 'android/app'
    at Object.lstatSync (fs.js:845:3)
    at Object.getHermesEnabled (......./node_modules/appcenter-cli/dist/commands/codepush/lib/react-native-utils.js:327:12)
    at CodePushReleaseReactCommand.<anonymous> (......./node_modules/appcenter-cli/dist/commands/codepush/release-react.js:112:72)
    at Generator.next (<anonymous>)
    at fulfilled (......./node_modules/appcenter-cli/dist/commands/codepush/release-react.js:11:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'android/app' }
```

in function `getHermesEnabled` at https://github.com/microsoft/appcenter-cli/blob/a63017dcc66f6eca4874757cead23eafba0ff2b6/src/commands/codepush/lib/react-native-utils.ts#L409

because the path is hardcoded:
https://github.com/microsoft/appcenter-cli/blob/a63017dcc66f6eca4874757cead23eafba0ff2b6/src/commands/codepush/lib/react-native-utils.ts#L405

Here's a slightly bigger piece of code:
```
...
export function getHermesEnabled(gradleFile: string): boolean {
  let buildGradlePath: string = path.join("android", "app");
  if (gradleFile) {
    buildGradlePath = gradleFile;
  }
  if (fs.lstatSync(buildGradlePath).isDirectory()) {
   ..
```

For the time being, we just patch this file on `postinstall` hook (I know this is a bad piece of duct-tape), otherwise we cannot use code-push at all.

What would be a better approach here? Is this already planned to be implemented, or it's intentional and should never be changed? I can raise a PR to introduce a CLI argument for that.

**Comment by yujincat** [comment]
Have you tried giving the `gradleFile` value to the method `getHermesEnabled` ?That can be done by setting args `-g` or `--gradle-file`. Run `$ appcenter codepush release-react --help` will show the help text for the args.

**Comment by pioneer32** [comment]
Oh... there's already an arg for that.... thanks for pointing at it. I actually missed it. Sorry about that. Such a shame :) And, yes it does work.
