### ISSUE TITLE
Allow generation and use of Organization API Tokens

### ISSUE THREAD

**Issue by mrowles** [microsoft/appcenter-cli#1030]
Feature Request: we would love to generate, manage and use Organization API Tokens rather than our own user ones since we do a lot of AppCenter CLI work through our CI/CD.

Let us know how we can help :)

**Comment by jp-andre** [comment]
I don't know about organization tokens, do we have that in the portal?

Have you considered using "app tokens" instead of user tokens? Those can easily be shared within a team of collaborators.

**Comment by mrowles** [comment]
@jp-andre I cannot find it if it exists - but I think what you recommended **might** work for now, however, we automatically create the apps based off env etc....so it's a race-condition. Unless we have an overarching token which can create, build, deploy any app within the organisation (same deal as a normal user account). Does that make sense?

**Comment by jp-andre** [comment]
It totally makes sense but I'm afraid there is no support for org tokens at this point in app center, so this is not a CLI issue.

You can browse and open a new issue in https://github.com/microsoft/appcenter instead, though we may not be able to address the request in the near future, see [note](https://github.com/microsoft/appcenter#planning).

**Comment by mrowles** [comment]
Got it! Thanks. Shall I leave this one here open and linked to for the future, or reopen later?

**Comment by jp-andre** [comment]
If you don't mind, we would rather close it here. Thanks for your understanding and follow-up on the main repo!
