### ISSUE TITLE
[Android/Hermes] Error: Failed to release a CodePush update

### ISSUE THREAD

**Issue by mrousavy** [microsoft/appcenter-cli#1043]
I cannot create CodePush updates for Android anymore. iOS works fine.

I'm just getting the error: `Error: Failed to release a CodePush update`:

![image](https://user-images.githubusercontent.com/15199031/91890020-1715bb00-ec8f-11ea-9b82-d16b52af76ce.png)

using

```
"hermes-engine": "^0.5.2-rc1",
"react": "^16.13.1",
"react-native": "^0.63.2",
"react-native-code-push": "^6.3.0",
"metro-config": "^0.58.0",
```

And `appcenter version 2.6.7`

**Comment by mrousavy** [comment]
After digging around the source code, I can pinpoint the issue. It prints

```
Converting JS bundle to byte code via Hermes, running command:\n
```

This line can be found in [react-native-utils.ts#L366](https://github.com/microsoft/appcenter-cli/blob/dd27e2652d23717386e350fdd1aa5e70a1ab5e32/src/commands/codepush/lib/react-native-utils.ts#L366), but it does not reach the next print statement which prints the hermes command ([react-native-utils.ts#L369](https://github.com/microsoft/appcenter-cli/blob/dd27e2652d23717386e350fdd1aa5e70a1ab5e32/src/commands/codepush/lib/react-native-utils.ts#L369)) so it has to be between those two statements. ([react-native-utils.ts#L367-L368](https://github.com/microsoft/appcenter-cli/blob/dd27e2652d23717386e350fdd1aa5e70a1ab5e32/src/commands/codepush/lib/react-native-utils.ts#L367-L368))

It's either the `getHermesCommand()` function, or the `spawn(hermesCommand, hermesArgs)` call.

**Comment by mrousavy** [comment]
Also, when running with the `--debug` flag, I still don't get extra information about the error thrown (trying to see [this statement](https://github.com/microsoft/appcenter-cli/blob/1ff1f23f33501da0f77d076fe24213a3381fb251/src/commands/codepush/release-react.ts#L221))

**Comment by anywherepilot** [comment]
@mrousavy do you get a ton of other debug output? If not, you should read [how to use debugging with the CLI](https://github.com/microsoft/appcenter-cli/blob/master/contributing.md#enabling-debug-logs).

**Comment by mrousavy** [comment]
@anywherepilot I'm getting `TypeError: Invalid Version: ^0.63.2`:


![image](https://user-images.githubusercontent.com/15199031/91962714-318e7980-ed0d-11ea-94d0-cedca4ea46f4.png)

**Comment by RickMartian** [comment]
> @anywherepilot I'm getting `TypeError: Invalid Version: ^0.63.2`:
> 
> ![image](https://user-images.githubusercontent.com/15199031/91962714-318e7980-ed0d-11ea-94d0-cedca4ea46f4.png)

This helped me -> https://github.com/microsoft/react-native-code-push/issues/1676#issuecomment-679957976

Hope you can get it work now!

**Comment by rpasup** [comment]
i am getting error internal server  and we are using the Codepush plugn from azure devops.. not sure how to debug as well.. any help

**Comment by Krasavinigor** [comment]
Hi there! 
I'm from CodePush team. It looks like: 
- microsoft/react-native-code-push#1676
- microsoft/react-native-code-push#1939

https://github.com/microsoft/appcenter-cli/pull/1104 was opened for these issues. Could you please check it?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
