### ISSUE TITLE
Download Appium Logs using API or CLI

### ISSUE THREAD

**Issue by icloudmegam** [microsoft/appcenter-cli#1051]
I am running appium test from Azure DevOps in Appcenter, After the test is completed I want to download the Appium logs from App Center. Any API or CLI is available to download the Appium Logs from AppCenter

**Comment by yujincat** [comment]
Hi there 👋 
Have you tried the command `appcenter test download`? You can download the test report by using this command.

**Comment by icloudmegam** [comment]
i tried appcenter test download, but i am getting the appium logs i am triggering and found API to get the mobile logs but couldn't find the logs for Appium 
![image](https://user-images.githubusercontent.com/59383451/93063182-81692b00-f693-11ea-842d-7dbec59be986.png)

**Comment by icloudmegam** [comment]
using this API i was able to get the links to download the logs related to Test that I ran 
`https://api.appcenter.ms/​v0.1​/apps​/{owner_name}​/{app_name}​/test_runs​/{test_run_id}​/report`
