### ISSUE TITLE
❓ What is CodePush default target binary version?

### ISSUE THREAD

**Issue by franznkemaka** [microsoft/appcenter-cli#1063]
Hello, 

I have a question: What is CodePush default target binary version?
I'm using my CI to CodePush on a particular release and I'd like to know what is the default value of `-t` is it all the native versions or the latest native version?

Thanks

**Comment by maleking** [comment]
yeap, when u don't  set any target version,target binary version refer to  current version of project in  android and  ios 
<img width="181" alt="Screen Shot 2020-10-27 at 4 05 17 PM" src="https://user-images.githubusercontent.com/6384225/97302377-3899ba00-186e-11eb-9404-615a5a81323b.png">

**Comment by franznkemaka** [comment]
Hello @maleking  thanks very much for your reply.
