### ISSUE TITLE
Unexpected end of Json input 

### ISSUE THREAD

**Issue by amitme0014** [microsoft/appcenter-cli#1067]
Hi,

I have a jenkins job running appcenter-cli commands. 
Everything was working smooth few hours ago and suddenly appcenter cli started breaking with ****Unexpected end of JSON Input*** while doing appcenter login.

Running it on jenkins server, as a root user i can run appcenter commands without any issue butas a jenkins user i am getting ****Unexpected end of JSON Input***.

I tried everything from removing node_modules to npm cache clean but nothing worked.

Not able to guess, why it suddenly stopped working. 

Please provide some help😕

**Comment by russelarms** [comment]
Hi @amitme0014, sorry for the delay, do you still experience the issue?
