### ISSUE TITLE
Error: failed to create release upload for platforms/android/app/build/outputs/apk/debug/app-debug.apk. Not found. Correlation ID: 1962762e-3118-4805-94d2-e605a6c43b0e

### ISSUE THREAD

**Issue by Lucasc23051994** [microsoft/appcenter-cli#1078]
Hello!
I´ve started to use App Center recently and I´m facing a issue when uploading an apk to my account, here´s the code and the error:

- name: Build
      run: |
          export NODE_OPTIONS="--max-old-space-size=8192" && npm run a:first:build:prd
      
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: mediservice
        path: platforms/
        
    - name: Install Dependencies for App Center
      run: |
          npm install resolve-url
    
    - name: Install Web Pack
      run: |
          npm i -D webpack@latest
   
    - name: Install App Center Cli
      run: |
          sudo npm install -g appcenter-cli --unsafe-perm
          
    - name: Log in to App Center
      run: |
          appcenter login -u ${{ secrets.APP_CENTER_USERNAME }} -p ${{ secrets.APP_CENTER_PASSWORD }} --token ${{ secrets.APPCENTER_ACCESS_TOKEN }}
    
    - name: Upload artefact to App Center
      run: |
          appcenter distribute release -g "Collaborators" -f "platforms/android/app/build/outputs/apk/debug/app-debug.apk" -a "Lucas.Azevedo.23/mediservice"

I receive the tittle message when the job is finished...I´ve cheked the app name, groups, file and etc. yet I don´t know what´s happening...

Thank you in advance for the support.

**Comment by russelarms** [comment]
Hi @Lucasc23051994, sorry for the delay. It should be fixed now. Please reopen if you still experience this issue.
