### ISSUE TITLE
Allow setting release ID on upload

### ISSUE THREAD

**Issue by steverichey** [microsoft/appcenter-cli#1079]
The App Center API allows for setting a release ID in the body of the request when creating a release upload: https://openapi.appcenter.ms/#/distribute/releaseUploads_create

Exposing this in the CLI would be very useful for keeping the release ID in sync with CI build numbers. As near as I can tell, this would require adding a `release_id` property on the upload body used in [release.ts](https://github.com/microsoft/appcenter-cli/blob/master/src/commands/distribute/release.ts). Perhaps even on [this line](https://github.com/microsoft/appcenter-cli/blob/master/src/commands/distribute/release.ts#L365).

If that is the correct place to add this value (in addition to a new property on `ReleaseBinaryCommand`), I'd be happy to open a pull request. Otherwise, I would greatly appreciate this feature in the next release. Thanks!

**Comment by russelarms** [comment]
Hi, @steverichey, the API has changed the mentioned endpoint is deprecated now. As far as I understand, there is currently no option to manually set the release ID.
The updated instruction:
https://docs.microsoft.com/en-us/appcenter/distribution/uploading#upload-new-release
