### ISSUE TITLE
Why can't I install it?

### ISSUE THREAD

**Issue by AiDres** [microsoft/appcenter-cli#1101]
C:\>npm install -g appcenter-cli
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/appcenter-cli failed, reason: write EPROTO 53096:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1942:
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dre\AppData\Roaming\npm-cache\_logs\2020-10-12T08_29_38_696Z-debug.log

**Comment by AiDres** [comment]
I try changing it to the HTTPS registry (https://registry.npmjs.org/).
C:\>npm install -g appcenter-cli
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/appcenter-cli failed, reason: write EPROTO 8756:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1942:
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dre\AppData\Roaming\npm-cache\_logs\2020-10-12T08_17_35_955Z-debug.log

**Comment by anywherepilot** [comment]
I just tried installing on Windows and macOS and it works fine. Is this your first time trying, or did it start failing after the new release today? Could you try to install the previous release 2.7.1?

**Comment by russelarms** [comment]
Hi @AiDres!
We haven't heard from you in a while and provided information isn't enough for future investigation, so I'm closing this issue. Please reopen/comment if you have more details or have any other questions.
