### ISSUE TITLE
Switch to force deleting a release w/o requiring interaction

### ISSUE THREAD

**Issue by jayMcBee** [microsoft/appcenter-cli#1114]
We are using appcenter-cli to script our builds.
Occasionally we need to remove a release from App Center (**appcenter distribute releases delete**).

An option to invoke the command w/o requiring the user to confirm deletion - e.g. via a **--force** switch - would be great in order to enable users to delete releases from scripts.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
