### ISSUE TITLE
Error "Failed to release a CodePush update - TypeError: Cannot convert undefined or null to object" with appcenter codepush release-react command

### ISSUE THREAD

**Issue by hemasharma8390** [microsoft/appcenter-cli#1138]
I tried to upload a react bundle  using the release -react command, but it fails with following error

  appcenter-cli:commands:codepush:release-react Failed to release a CodePush update - TypeError: Cannot convert undefined or null to object
  appcenter-cli:commands:codepush:release-react     at Function.from (<anonymous>)
  appcenter-cli:commands:codepush:release-react     at C:\Users\....\AppData\Roaming\npm\node_modules\appcenter-cli\dist\commands\codepush\lib\react-native-utils.js:339:22
  appcenter-cli:commands:codepush:release-react     at runMicrotasks (<anonymous>)
  appcenter-cli:commands:codepush:release-react     at processTicksAndRejections (internal/process/task_queues.js:94:5) +0ms

After examining the logs it seems that below code is crashing in react-native-utils.getHermesEnabled(gradleFile) with code
  return g2js
        .parseFile(buildGradlePath)
        .catch(() => {
        throw new Error(`Unable to parse the "${buildGradlePath}" file. Please ensure it is a well-formed Gradle file.`);
    })
        .then((buildGradle) => {
            **return Array.from(buildGradle["project.ext.react"]).includes("enableHermes: true");**
    });

I have defined project.ext.react in  main module's gradle file like below
**apply plugin: 'com.android.application'**
**apply plugin: 'io.fabric'**
**import com.android.build.OutputFile**

**project.ext.react = [**
       **entryFile: "index.js",**
**]**
**apply from: "../../node_modules/react-native/react.gradle"**
**apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"**

This command is working with a newly created project but not in my existing project.
Below is the command that I'm using : 
appcenter codepush release-react -a  <user.name>/<android -project>  --gradle-file "./android/main_module_name/build.gradle"

Following versions are used in project
 "appcenter": "3.1.2",
 "appcenter-analytics": "3.1.2",
 "appcenter-cli": "2.7.3",
 "appcenter-crashes": "3.1.2",
 "react-native": "0.61.5",
 "react-native-code-push": "^6.3.0"

**Comment by hemasharma8390** [comment]
As per my findings, when gradle file is parsed in the method

**react-native-utils.getReactNativeProjectAppVersion(versionSearchParams, projectRoot)**  using **g2js.parseFile(buildGradlePath)**

It returns a valid json object and so is able to access **buildGradle.android.defaultConfig.versionName** 
and  **project.ext.react** with value  [ 'entryFile: "index.js"', '' ]

But when this gradle is parsed in method
 **react-native-utils.getHermesEnabled(gradleFile)** 

It return an invalid json with partial data and that's why not able to access **project.ext.react** which causes the crash.

**Comment by russelarms** [comment]
Hi @hemasharma8390, sorry for the delay, do you still experience the issue?

**Comment by andreidubov** [comment]
Hi @hemasharma8390, we have reproduced the issue and added it to our backlog until it is fixed you can use the workaround described there #1249

**Comment by DmitriyKirakosyan** [comment]
Closing as fixed.
