### ISSUE TITLE
appcenter codepush TypeError: pna.nextTick is not a function

### ISSUE THREAD

**Issue by mrousavy** [microsoft/appcenter-cli#1145]
I can't run the appcenter codepush command at all!

![Screenshot 2020-11-13 at 23 38 33](https://user-images.githubusercontent.com/15199031/99127764-64a49180-2609-11eb-8db2-18634084ca4b.png)

### Versions

* node: v15.2.0
* npm: 6.14.8
* appcenter: 2.7.3
* macOS: Big Sur 11.0.1

**Comment by mrousavy** [comment]
I hate to bump issues, but I've been completely unable to run any appcenter commands since I've upgraded to macOS Big Sur, which is a huge blocker for me considering 10 days is a pretty long time for not being able to push hotfixes to an app. 😕

cc maybe @anywherepilot @owenniblock @kmiecikt @jp-andre @russelarms

**Comment by jp-andre** [comment]
> I hate to bump issues, but I've been completely unable to run any appcenter commands since I've upgraded to macOS Big Sur, which is a huge blocker for me considering 10 days is a pretty long time for not being able to push hotfixes to an app. 😕
> 
> cc maybe @anywherepilot @owenniblock @kmiecikt @jp-andre @russelarms

Hi @mrousavy, quick reply before looking into this more.

Have you considered using node version 10, 12 or even 14? We've previously had issues where newer versions of node would break the CLI, so I would consider trying to run on an older version of node first. I believe even numbered versions are more "stable" since they are node LTS versions, so I'd recommend sticking to them, see https://nodejs.org/en/about/releases/.

**Comment by mrousavy** [comment]
@jp-andre Thanks for your response. Yes, I have tried with node 15, node 14 and even node 12 (using brew), but none of this seems to change anything. I'm pretty sure it's Big Sur's fault, since it didn't work after upgrading to Big Sur and I didn't upgrade node during that time.

**Comment by roman-myshchyshyn** [comment]
@mrousavy Just for your information, it may not be Big Sur, cause I am able to push updates after updating to it.

**Comment by russelarms** [comment]
Hi @mrousavy, sorry for the delay, do you still experience the issue?

**Comment by mrousavy** [comment]
@russelarms just tested it again and it seems like everything is working now. Not sure what the cause was, I haven't touched the appcenter cli since november 😅
