### ISSUE TITLE
AppCenter has no documentation nor transparency in their build system

### ISSUE THREAD

**Issue by bricepollock** [microsoft/appcenter-cli#1154]
I have been waiting days to fix several broken issues with submitting a queue'd build on AppCenter through 'support'.

1. Despite a Carthage workaround being shared and used for months in the iOS community... AppCenter does not support using this workaround script and always fails building via Carthage
2. Switching to Pods and removing all reference to Carthage, still triggers a build install step in AppCenter to install Carthage. There is no documentation on how to modify the AppCenter build script or why this is happening. 

Situation:
No ability to build on app center through CLI. Manual submission of an IPA to AppCenter works.

Shell command triggered by fast lane:
appcenter build queue --app "<app path>" --branch master

**Comment by russelarms** [comment]
Hi @bricepollock, sorry for the delay, do you still experience the issue?

**Comment by bricepollock** [comment]
Hello @russelarms, I think there is still a lot of documentation that could be added. How AppCenter resolves dependancies with Carthage, pods, etc. is not documented and this hidden logic makes it hard to use AppCenter when things go wrong

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to expand our documentation in the next year, I'm closing the issue.
