### ISSUE TITLE
[React Native] Support Hermes on iOS (react-native 0.64)

### ISSUE THREAD

**Issue by mrousavy** [microsoft/appcenter-cli#1164]
react-native 0.64-rc0 released, which includes Hermes support for iOS. (see https://github.com/react-native-community/releases/issues/214) Currently, all `appcenter codepush` commands fail, because the bundle-generation is hardcoded in such a way that it isn't expecting a hermes js executor/bitcode instead of JSC for iOS builds, so at the moment codepush does not work.

Is hermes support planned for codepush?

**Comment by mrousavy** [comment]
I managed to actually build the JS bundle using the appcenter CLI, and it actually works with Hermes. The problem is, that the bundle is not built with the Hermes compiler (hermesc), meaning it is not in bytecode format and the app will therefore not run with maximum performance.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Hermes for IOS is on our roadmap but we don't have ETA for this. We will do it as soon as possible and notify you when we will have any updates.

**Comment by fredyonge** [comment]
@AnastasiaKubova are there any updates on this?

**Comment by AnastasiaKubova** [comment]
We don't have ETA for this. We will notify here when we will have any updates.

**Comment by mcarlson** [comment]
We need this also. It would be nice if your documentation clearly listed the limitations for various versions of react-native.

**Comment by aleksandr-dorofeev** [comment]
I'm closing this issue, since https://github.com/microsoft/appcenter-cli/pull/1461 was merged.
