### ISSUE TITLE
Error: Failed to analyze MachO file: Unknown load command: 2147483700

### ISSUE THREAD

**Issue by palmerc** [microsoft/appcenter-cli#1165]
appcenter fails with:
`Error: Failed to analyze MachO file: Unknown load command: 2147483700`

This is server-side analysis I'm quite sure, but you'll start seeing issues about it if people attempt to upload to Test with Xcode 12.2 as the build system.

The XCUITest frameworks and libraries contain an ARM64e slice and two new Load Commands. 0x33 and 0x34

Workaround - remove the arm64e slices from the XCUITest frameworks and dylibs in the Runner.

**Comment by snoozemoose** [comment]
@palmerc This is very useful info but exactly how does one perform the workaround?

**Comment by palmerc** [comment]
@snoozemoose you can remove the arm64e slice easily enough with the lipo tool. However, AppCenter still has problem with Test Runner's compiled in Xcode 12. So... the work around is to compile your test running with Xcode 11, then copy the *-Runner.app and your Xcode 12 app into a folder and upload the pair. It is not ideal, but does work for us.

**Comment by snoozemoose** [comment]
@palmerc Thank you, I'll give this a try!

**Comment by JayakumarKnila** [comment]
Facing the same issue, Is this fixed now?

**Comment by timroeringDB** [comment]
When is there an update to this?

**Comment by sethrj** [comment]
Is this error coming from the python `macholib` package? I recently got an identical error directly from that package which was fixed by https://github.com/ronaldoussoren/macholib/commit/e86c2d8745ef13826df0e4227e2f775edec1ec4f .

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
