### ISSUE TITLE
[React Native | Hermes] Code Push for Hermes-Enabled Apps in Monorepos

### ISSUE THREAD

**Issue by agreea** [microsoft/appcenter-cli#1170]
We have a React Native Android app within a monorepo, where the react-native package installs in the root-level node_modules.
Currently, when attempting to code push for a React Native app in a monorepo, the process fails when attempting to convert the JS bundle to byte code via Hermes (see output below).
```bash
Converting JS bundle to byte code via Hermes, running command:

node_modules/hermesvm/osx-bin/hermes -emit-binary -out /var/folders/q3/fzyknkyx3cv21d6lxj0k3vnw0000gn/T/code-push2020113-30003-1c4vji1.e8hb/CodePush/index.android.bundle.hbc /var/folders/q3/fzyknkyx3cv21d6lxj0k3vnw0000gn/T/code-push2020113-30003-1c4vji1.e8hb/CodePush/index.android.bundle
node:events:304
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/hermesvm/osx-bin/hermes ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:269:19)
    at onErrorNT (node:internal/child_process:465:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:275:12)
    at onErrorNT (node:internal/child_process:465:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node_modules/hermesvm/osx-bin/hermes',
  path: 'node_modules/hermesvm/osx-bin/hermes',
  spawnargs: [
    '-emit-binary',
    '-out',
    '/var/folders/q3/fzyknkyx3cv21d6lxj0k3vnw0000gn/T/code-push2020113-30003-1c4vji1.e8hb/CodePush/index.android.bundle.hbc',
    '/var/folders/q3/fzyknkyx3cv21d6lxj0k3vnw0000gn/T/code-push2020113-30003-1c4vji1.e8hb/CodePush/index.android.bundle'
  ]
}
```

The problem is [this function](https://github.com/microsoft/appcenter-cli/blob/9670fae935d2d2e90bf9e02c7187854cfcb3e6f6/src/commands/codepush/lib/react-native-utils.ts#L451) which assumes `hermes-engine` (or `hermesvm`) will be found within the project's `node_modules`. The `react-native-codepush` package threw errors with [similar causes](https://github.com/microsoft/react-native-code-push/blob/6ae9392d81eb5a8377664681da7ca673e630c481/android/codepush.gradle#L32) in the build process. These were solved by setting the `nodeModulesPath` in our project's `gradle.properties`.

An easy solution would be checking the app's gradle file for `hermesCommand` or `nodeModulesPath` values (as code push does [here](https://github.com/microsoft/appcenter-cli/blob/9670fae935d2d2e90bf9e02c7187854cfcb3e6f6/src/commands/codepush/lib/react-native-utils.ts#L422) to determine whether to run hermes in the first place). This would also bring the code push cli behavior more in line with the code push package's build behavior. Then, perhaps, we could add some documentation about how AppCenter behaves with Hermes-enabled apps, as others have run into issues [1](https://github.com/microsoft/appcenter-cli/issues/1013) [2](https://github.com/microsoft/appcenter-cli/issues/1013) [2](https://github.com/microsoft/appcenter-cli/issues/1043).

I tried implementing this with the intent of opening a PR but wasn't able to build `appcenter-cli` locally.

Also note that the cli doesn't detect that we're on `react-native@^0.63.0` because it's using `hermesvm` rather than `hermes-engine`. This may have something to do with `react-native` being installed at root node_modules.

Details:
appcenter cli: 2.7.3
react-native: 0.63.3
hermes-engine: 0.5.0
react-native-code-push: 6.4.0

**Comment by DmitriyKirakosyan** [comment]
Closing as fixed.
