### ISSUE TITLE
Android -- Failed to release a CodePush update - Error: ENOENT: no such file or directory, lstat 'android/app'

### ISSUE THREAD

**Issue by liufeng0504** [microsoft/appcenter-cli#1178]
I specified the --target-binary-version parameter, not the --gradle-file  parameter, because my project is completely independent, do I have to specify the --gradle-file parameter?

env:
appcenter-cli: 2.7.3

error: 
  appcenter-cli:commands:codepush:release-react Failed to release a CodePush update - Error: ENOENT: no such file or directory, lstat 'android/app'
  appcenter-cli:commands:codepush:release-react     at Object.lstatSync (fs.js:923:3)
  appcenter-cli:commands:codepush:release-react     at Object.getHermesEnabled (/Users/fht360/Desktop/fht-react-native/node_modules/appcenter-cli/dist/commands/codepush/lib/react-native-utils.js:327:12)
  appcenter-cli:commands:codepush:release-react     at CodePushReleaseReactCommand.<anonymous> (/Users/fht360/Desktop/fht-react-native/node_modules/appcenter-cli/dist/commands/codepush/release-react.js:107:72)
  appcenter-cli:commands:codepush:release-react     at Generator.next (<anonymous>)
  appcenter-cli:commands:codepush:release-react     at fulfilled (/Users/fht360/Desktop/fht-react-native/node_modules/appcenter-cli/dist/commands/codepush/release-react.js:11:58)
  appcenter-cli:commands:codepush:release-react     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  appcenter-cli:commands:codepush:release-react   errno: -2,
  appcenter-cli:commands:codepush:release-react   syscall: 'lstat',
  appcenter-cli:commands:codepush:release-react   code: 'ENOENT',
  appcenter-cli:commands:codepush:release-react   path: 'android/app'
  appcenter-cli:commands:codepush:release-react } +0ms
Error: Failed to release a CodePush update.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! @fht360/fht-react-native@1.0.16 update-android-debug: `DEBUG=* appcenter codepush release-react --target-binary-version '1.0.x' --entry-file ./index.js --deployment-name Debug      --app fht360.com/fht-android --development`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the @fht360/fht-react-native@1.0.16 update-android-debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fht360/.npm/_logs/2020-12-07T09_11_49_756Z-debug.log

**Comment by russelarms** [comment]
Hi @liufeng0504, sorry for the delay, do you still experience the issue?

**Comment by liufeng0504** [comment]
@russelarms I'm sorry, I've asked for leave to go home these days. I didn't reply to you in time.
I still have this problem.

**Comment by liufeng0504** [comment]
It has nothing to do with --target-binary-version, but Hermes needs the build.gradle file, and the content needs to contain "project.ext.react". You can find it in function getHermesEnabled of "./node_modules/appcenter-cli/dist/commands/codepush/lib/react-native-utils.js".

**Comment by lado2713** [comment]
Hi,
I am getting error "ENOENT: no such file or directory, lstat 'android\app'" when running command: 'codepush release-react -a <user_name>/<app_name> -d Staging'. Inside android directory I have used "MyApp" folder instead of "App" folder.                      
Please help in resolving this error.

**Comment by AnatolyPristensky** [comment]
Hello @lado2713, 
You should use 'android/app' folder structure instead of 'android/MyApp'. 

`codepush release-react command` is looking for this structure.
