### ISSUE TITLE
Release Notes Format not working

### ISSUE THREAD

**Issue by Zeropointer11** [microsoft/appcenter-cli#1184]
One Question since we have update to App Center CLI for the reason Microsoft has begun to deactivate the old API (https://status.appcenter.ms/incidents/7930rkfgtg1y) the formatting of our Release notes is not longer working.

Can you tell me witch format the Release notes should have? We upload it as an Markdown but the Website show it as Plain Text.
CLI Command: Format Markdown:
`
appcenter distribute release \
  --app $appcenter_owner_appname \
  --group "Collaborators" \
  --file $filename \
  --token $apitoken \
  --release-notes "- Change 1 \n- Change2 \n - Change 3 ....."
`
CURRENT:
Shown Text on the Download Page:
"- Change 1 \n- Change2 \n - Change 3 ....."

SHOULD:
Text should be formatted with line breaks and all other stuff (Markdown)
Like:

- Change 1
- Change 2
- Change 3 .....

**Comment by russelarms** [comment]
Hi, @Zeropointer11, as far as I know, release notes are handled as plain text throughout App Center.

**Comment by ahujamanish** [comment]
@russelarms as far as I know, the REST API does handle Markdown format for the release notes.

**Comment by DmitriyKirakosyan** [comment]
Hi @Zeropointer11 and @ahujamanish 

App Center distribution does support Markdown text for release notes.
Using option `--release-notes` allows you to specify a short one-line message. It does support some basic markdown though, such as _italic_ and **bold**.
If you want to write a more complex markdown text for release notes, you can create a file with your markdown text and specify it to the `--release-notes-file` (or just `-R`) option.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
