### ISSUE TITLE
Error occurs when updating name of current app twice or more, consecutively.

### ISSUE THREAD

**Issue by alexDtorres** [microsoft/appcenter-cli#1201]
After setting the current app, update the current app with a new name:
`$ appcenter apps update -n <newName>`

```
App Secret:            <appSecret>
Description:           
Display Name:          <displayName>
Name:                  <newName>
OS:                    iOS
Platform:              React-Native
Release Type:          Beta
Owner ID:              <ownerID>
Owner Display Name:    <ownerDisplayName>
Owner Email:           
Owner Name:            <ownerName>
Azure Subscription ID:
```

The first update command returns successfully.  However, an error occurs when trying to update the current app with another new name:

`$ appcenter apps update -n <newName>`

```
Error: Command 'apps update -n <newName>' 
failed with exception "Not found. Correlation ID: <correlationID>"
```

I suspect the error occurs because the current app needs to be "set" again after the "update" operation, but before control is returned to the cli user.

If this isn't a duplicate issue, or solved with a new release, then I'll start working on a PR. 

_Thanks, let me know what you all think! 👍_

**Comment by russelarms** [comment]
Hi @alexDtorres, sorry for the delay! I confirm it's a bug. After changing the name we need to execute:
`appcenter apps set-current *updated_name*`
The PR is welcome :)

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
