### ISSUE TITLE
Badges or CLI query for UITests success/failure

### ISSUE THREAD

**Issue by hot33331** [microsoft/appcenter-cli#1206]
Currently I do not see a way to have a good overview over succeeding/failing of a large amount of projects' UITest. One has to open up the project 2x (droid/ios) in the web interface and dig down to the tests to see whether they fail or succeed currently.

I'd like to build a dashboard where one can immediately get a good overview over the status of  all projects and thought about something like the build badges for tests or a possibility to query the status of the last fully run test (fail/success).

Is that something that is already doable or would this be a feature request?

**Comment by unnati914** [comment]
could i work on this?

**Comment by AnastasiaKubova** [comment]
Hi, @unnati914 , feel free to open contribution PR with a solution to this issue and we will definitely consider it.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
