### ISSUE TITLE
appcenter distribute release returns non-json response on failure (with --output json option)

### ISSUE THREAD

**Issue by ahujamanish** [microsoft/appcenter-cli#1207]
The following command `appcenter distribute release` returns a text response even with `--output json` option passed. 

In my use case, the command throws an error because the app with the specified name doesn't exist, so am expecting a valid JSON response with the status code, so that appropriate action can be taken. 

**Sample command:** 

`appcenter distribute release -f [PATH_TO_FILE]  --release-notes 'release_notes' -g 'Collaborators' --app 'org/app-name' --output json`

Actual Response:
`Error: failed to create release upload for [PATH_TO_FILE].ipa. Not found. Correlation ID: d7136eb9-6f2a-4c0f-98bd-xxxxxxxxx`

**Desired Response**
`{"message":"Not found. Correlation ID: d7136eb9-6f2a-4c0f-98bd-xxxxxxxxx","statusCode":404,"code":"Not Found"}`

**Comment by russelarms** [comment]
It is fixed in the 2.9.0 release.

**Comment by varemenos** [comment]
@russelarms this also happens with the `add` command

**Comment by DmitriyKirakosyan** [comment]
Hi @varemenos , could you elaborate on your point? Why would you like to change the response format in case the deployment was added successfully?

**Comment by DmitriyKirakosyan** [comment]
@varemenos it is still unclear what exactly would you expect to receive as a result of success. Json data is displayed when there was requested some data. In this case the command `codepush deployment add` creates a deployment with success or failure. All such commands behave the same in terms of output.

If you still think this exact command doesn't output json while other similar commands do, please describe why and provide an example.
if you think all such commands that upload or create something should output a json output, please file a separate feature request.
