### ISSUE TITLE
Appcenter --debug seems to write debug output to stdout

### ISSUE THREAD

**Issue by andrewshuttlewood-masabi** [microsoft/appcenter-cli#1211]
We're using appcenter to upload Proguard mappings after an APK file, and to make sure we have the right information we parse the json response that comes back from `appcenter distribute` command.

We hit some issues a while ago and added the --debug flag, however this seems to output the debug information to stdout, rather than to stderr, which makes it very difficult to use from a script.

Our script looks something like:
```
release_response=$(appcenter distribute release \
      --app ${application_id} \
      --file ${app_file} \
      --group ${deployment_group} \
      --silent \
      --output json
version_code=$(echo $release_response | jq -r '.version')
version_name=$(echo $release_response | jq -r '.shortVersion')
```
 and when we run the above with --debug, the "release_response" variable gets setup with something like
```
Using appcenter-cli version: 2.7.3
logFilter, request: {
	  "rawResponse": false,
	  "queryString": {},
	  "url": "https://api.appcenter.ms/v0.1/......
```

Is there a workaround that allows us to get debugging information and the JSON response separately?

**Comment by grndvl1** [comment]
--app says it requires USER/APP_NAME does it also accept the App ID (Secret)?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
