### ISSUE TITLE
Download Latest Build\Release using Appcenter CLI

### ISSUE THREAD

**Issue by StephenMulryan** [microsoft/appcenter-cli#1261]
Hi,

I am trying to automate the process of running tests on AppCenter using the Command Line Interface. I have tried using the command mentioned in #672 but it downloaded the file but the file extension is .undefined rather than a .apk file.

The command I am using is `appcenter distribute groups download -g <group> -a <app>`.

I have already signed in to Appcenter using a token.

**Comment by russelarms** [comment]
Hi @StephenMulryan, thanks for reaching out. Please, fill in the issue according to the bug report template.

I've checked `appcenter distribute groups download -g <group> -a <app>`. It downloaded proper .apk file.

**Comment by StephenMulryan** [comment]
@russelarms Thank you. Is it correct to use the bug report template if it was a question? Although if it works for you and not for me then maybe there are other settings needed or it is an issue?!

**Comment by StephenMulryan** [comment]
### **Description**
When I use the command `appcenter distribute groups download -g <group> -a <app>` the file downloads with file extension .undefined instead of .apk

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Login to AppCenter using user token
2. Execute `appcenter distribute groups download -g <group> -a <app>` command

### **Expected behavior**
For Android: apk file is downloaded to current directory.

### **Details**
1. file with extension .undefined is downloaded.

**Comment by StephenMulryan** [comment]
Just to come back on this. It worked when I ran it using the command prompt on Windows. It was failing when I was trying to run it on the terminal on my macbook.

**Comment by russelarms** [comment]
Hi @StephenMulryan, thanks for the provided information.
Only the extension is wrong? What with the binary size? Will the file work if you change the extension: undefined > apk?
Can you run the command with logs on mac and windows:
`DEBUG="appcenter-cli:*" appcenter apps list` ?
Do you spot any difference/warnings/errors?

**Comment by StephenMulryan** [comment]
Sorry for the slow response. When my colleague ran the same shell script they could download the file correctly as a .apk file so it is something that is specific to my environment. You can mark this question as closed as it is something I will need to figure out. I will come back to you on it when I find the fix.

**Comment by Jamminroot** [comment]
@StephenMulryan  okay, thanks! Please reopen the ticked need you any assistance from our side
