### ISSUE TITLE
How to get download url for latest release binaries?

### ISSUE THREAD

**Issue by rwecho** [microsoft/appcenter-cli#1262]
There is any way to get the latest URL in the GitHub action to send the URL to my teammates?  Somebody in my team usually ignores the notification of the appcenter. 

Thanks.

**Comment by Jamminroot** [comment]
Hey!
I think you've got to create a script for that.
Those commands would be of use to get a link to the latest available release (difference in distribution groups are ignored, it's just a flat list):
`appcenter distribute releases list`
`appcenter distribute releases show -r <release_id>`
Would you need to account distribution groups, look at the command below:
`appcenter distribute groups show -g <group_name> -a <org_name/app_name>`.

There is no one-liner to get a link straight away.

**Comment by Jamminroot** [comment]
Also, if you are referring to API to provide direct download link (as in: install....something.123.apk), there's no such thing since download is handed in chunks which are "glued" together after each one of them are downloaded.

**Comment by Jamminroot** [comment]
We haven't heard from you for a while. I'm closing the issue now, but feel free to reopen.

**Comment by micaiah-effiong** [comment]
For anyone still looking for an answer.  This script will show the info for the latest release
```bash
# get the release id
RELEASE_ID=$(appcenter distribute releases list --app <APPCENTER_APP_NAME>  | grep ID | grep -m1 -o -E '[0-9]+')

# show release information 
RELEASE_INFO=$(appcenter distribute releases show --app <APPCENTER_APP_NAME> -r $RELEASE_ID)

# log release info
echo $RELEASE_ID | grep -E '(Download|Install|Icon)'
```
