### ISSUE TITLE
Unable to run AppCenter Test command in Windows Batch file

### ISSUE THREAD

**Issue by StephenMulryan** [microsoft/appcenter-cli#1272]
### **Description**
Unable to run AppCenter Test command in Windows Batch file. 

### **Repro Steps**
I have written a batch file to do the following:

1. Login to AppCenter using token
2. Download latest release of Android app file
3. Execute AppCenter Test command and use downloaded app file

### **Expected behavior**

- User is logged into App Center using token
- Latest release of Android app file is downloaded
- AppCenter Test command runs successfully referencing the latest release of the Android application and the DLL containing the Xamarin UI Tests 

### **Details**

- The Appcenter command logs in successfully
- The latest release of Android app file is downloaded successfully
- AppCenter Test command fails at the point of preparing the tests reporting the following:
"Invalid options were used to prepare the test artifacts, please try again. If you can't work out how to fix this issue, please contact support."
I have opened a support ticket through AppCenter portal but the agent cannot find any issue with the command that I have used. Here are the contents of the batch file:

`@Echo off
SET BUILD_DIR=C:\CompanyName\Git\CLA_ACQ_AgentAssist_Mobile\AgentAssist.Mobile.AcptTests\bin\Debug\

SET MyPath = %~dp0
Echo %MyPath%

Echo Logging in to AppCenter ....

Call AppCenter Login --token <Token>

Echo Starting Download of latest Android Build....

Call AppCenter distribute groups download -g "Collaborators" -a "xtc-CompanyName/New-Agent-Assist-Dev"

Echo Finished

Echo Starting Test Run

Call appcenter test run uitest --app "xtc-CompanyName/New-Agent-Assist-Dev" --devices "xtc-CompanyName/samsung-s10-plus" --app-path "C:\CompanyName\Git\CLA_ACQ_AgentAssist_Mobile\com.CompanyName.AgentAssist.dev.apk" --test-series "develop" --locale "en_US" --build-dir "C:\CompanyName\Git\CLA_ACQ_AgentAssist_Mobile\AgentAssist.Mobile.AcptTests\bin\Debug\" --include-category "updateactivities" --token <Token>

@echo off
set /p id="End of batch file, enter key to exit.... "
`

You can ignore the path variables I defined as I have tried to use absolute paths first in order to attempt to get it working. The only changes I have made above is to replace the **token** with **<Token>** and to replace the name of the company I am working for with **CompanyName**. See Output of batch file execution attached.

![Command_Output](https://user-images.githubusercontent.com/3050277/107780413-8f080700-6d3e-11eb-803b-11862f160026.png)

### **Environment, Dependencies & Tools**

- Windows Server 2016
- Node.js (v14.15.5)
- NPM (v7.5.3)
- AppCenter CLI (v2.7.4)
- Android SDK 30
- Java JDK 15.0.2

**Comment by Jamminroot** [comment]
Hey, @StephenMulryan, thanks for reaching out. Can you run the script with debug output enabled for the test command?
The argument is `--debug`. 
Also, having additional debug logs from npx should help, but that would require different invocation:
`DEBUG="appcenter-cli:commands:*" npx appcenter test run uitest`

**Comment by StephenMulryan** [comment]
Hi @Jamminroot , Thank you for responding.

When I put the **_--debug_** argument on the AppCenter Test command it gives the same output as without it.

Regarding using the `DEBUG="appcenter-cli:commands:*" npx ts-node src/index.ts test run uitest` command could you give me some help here? I have found the location where NPM stores the installed modules - **_C:\Program Files\nodejs\node_modules\npm\node_modules_** but I cannot find where AppCenter-CLI is located within that folder. I have searched the folder for terms like **_AppCenter_** and **_CLI_** but nothing comes up. I have also had a search online to try find the installation location.

![AppCenter_Test_With_Debug](https://user-images.githubusercontent.com/3050277/107965693-ba8b2b80-6fa2-11eb-8960-6dabae98d7fd.png)

**Comment by DmitriyKirakosyan** [comment]
Hi @StephenMulryan,
Please check if `%AppData%\npm\node_modules\appcenter-cli` exists for you and try to use it for the `npx` command.

Regarding your error, could you please ensure that `Xamarin.UIText.3.0.12` is the package you used to build the tests? If it's not a correct version, please specify the xamarin.uitest package manually using `--uitest-tools-dir` option (see more info [here](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/troubleshooting/#manually-specify-the-uitest-tools-directory)).

**Comment by DmitriyKirakosyan** [comment]
@StephenMulryan 

Just tested your command and it worked for me. I replaced the paths and token for my app, and also removed the `--include-category "updateactivities"` part. I was able to run the tests.

Could you also try to run the `test-cloud.exe prepare` command from your output that is starting with `Error: Cannot prepare UI Test artifacts using command:`? Please specify the `--debug` option for that command as well.

**Comment by StephenMulryan** [comment]
@DmitriyKirakosyan Thank you for your response.

When I run the Test-Cloud command with the --debug flag (from the packages folder and the bin\Debug folder) I get the following output:

![image](https://user-images.githubusercontent.com/3050277/108190798-51bec300-710a-11eb-9fac-e4ad29577369.png)

I also tried removing the `--include-category "updateactivities"` but I got the same error.

The `%AppData%\npm\node_modules\appcenter-cli` directory is available but I am still not sure what command to run. Index.ts mentioned by @Jamminroot is not located within the base directory. I have tried the following command:
![image](https://user-images.githubusercontent.com/3050277/108191966-a31b8200-710b-11eb-853b-1e2eca9478d0.png)

When I append `DEBUG="appcenter-cli:commands:*"` at the start it des not recognise the command. I have checked the log file in the output and it says that a " is missing. I combed the original command and cannot see any issue. Here is the log (I have replaced sensitive text with terms like CompanyName, ProductName and UserName):
[2021-02-17T09_15_39_063Z-debug.log](https://github.com/microsoft/appcenter-cli/files/5995157/2021-02-17T09_15_39_063Z-debug.log)

**Comment by DmitriyKirakosyan** [comment]
@StephenMulryan

My environment:

> Node: 14.15.4
> npm: 6.14.10
> appcenter-cli: 2.7.4

There is one `"` (the first one) missing in the `--uitest-tools-dir` option in your command on the first screenshot. Please fix it and try again.
If it doesn't help, could you write me your command in text, so I could copy and past it to my console. Please make sure all sensible information is replaced, like you did in the log file.

Also, please update the first image and hide your token.

**Comment by StephenMulryan** [comment]
@DmitriyKirakosyan Thank you but that did not help. Here is the command in plain text. I have removed sensitive data and replaced with terms like CompanyName, ProductName and UserName. I also removed the login token:

`npx ts-node "C:\Users\UserName\AppData\Roaming\npm\node_modules\appcenter-cli\dist\util\apis\generated\appCenterClient.d.ts" test run uitest --app "xtc-CompanyName/New-Agent-Assist-Dev" --devices "xtc-CompanyName/samsung-s10-plus" --app-path "C:\CompanyName\Git\CLA_ACQ_AgentAssist_Mobile\com.ProductName.AgentAssist.dev.apk" --test-series "master" --locale "en_US" --build-dir "C:\CompanyName\Git\CLA_ACQ_AgentAssist_Mobile\AgentAssist.Mobile.AcptTests\bin\Debug\" --include-category "updateactivities" --token "<Insert Login Token Here>" --uitest-tools-dir "C:\CompanyName\GIT\CLA_ACQ_AgentAssist_Mobile\packages\Xamarin.UITest.3.0.12\tools" --debug`

**Comment by DmitriyKirakosyan** [comment]
@StephenMulryan  Try to remove the last `\` symbol in the arg `--build-dir "C:\CompanyName\Git\CLA_ACQ_AgentAssist_Mobile\AgentAssist.Mobile.AcptTests\bin\Debug\"`.
So it should be `--build-dir "C:\CompanyName\Git\CLA_ACQ_AgentAssist_Mobile\AgentAssist.Mobile.AcptTests\bin\Debug"`.

It didn't work for me with this extra `\`. Let me know if it resolves your issue.

**Comment by StephenMulryan** [comment]
@DmitriyKirakosyan Thank you very much.

Got past that first step and now seeing this error on on the step to upload the files:

![image](https://user-images.githubusercontent.com/3050277/108217691-ca824700-712b-11eb-87be-e8739c86456c.png)

**Comment by DmitriyKirakosyan** [comment]
@StephenMulryan

This looks like the file is being accessed by another process.
Try to run `npm cache clean`.
If it doesn't help, try to remove npm cache and packages folders manually:
```
rd /s /q C:\Users\foo\AppData\Roaming\npm-cache
rd /s /q C:\Users\foo\AppData\Roaming\npm
```

If it doesn't help, check if you have any antivirus scan running.
You can also try to find what process is locking the file using [Resource Monitor](https://superuser.com/a/643312) or [Process Explorer](https://superuser.com/a/399660).

Let me know if it helps.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.
