### ISSUE TITLE
App release fails after rename

### ISSUE THREAD

**Issue by alenros** [microsoft/appcenter-cli#1279]
### **Description**
After using the API to rename the app (changing both name and display_name) running ```appcenter distribute release``` fails with both new and old name with the following error:
Error: failed to create release upload for c:\files\app.ipa. Not found. Correlation ID: 3ca37666-7223-4b45-88af-481eb8c148a6
 
### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Browse to https://openapi.appcenter.ms/
2. Authenticate
3. Using the Patch ​request for /v0.1​/apps​/{owner_name}​/{app_name} send the following payload:
{
  "display_name": "MyNewAppName",
  "name": "MyNewAppName"
}
4. In Powershell run ```appcenter distribute release --app MyOrg/MyNewAppName --file c:\files\app.ipa --group Collaborators```

### **Expected behavior**
A new release should be created for the app.

**Comment by DmitriyKirakosyan** [comment]
Hi @alenros 

The API that you are using to rename your app does not perform the changes instantly. It may take some time (a few seconds for me) for the changes to take effect. It could be the reason you are getting that error.

If it is not your case, please execute:
```
> appcenter apps list
```
and make sure that the app in `--app MyOrg/MyNewAppName`  matches one of the apps listed in the command output.

**Comment by alenros** [comment]
@DmitriyKirakosyan I have listed my apps, and it seems like the change was made, but even after a few hours it still fails.
please note the release also fails for the previous name.

**Comment by DmitriyKirakosyan** [comment]
@alenros 

Have you tried to distribute the app manually using the AppCenter portal? Would it work?

**Comment by alenros** [comment]
It's working now, can't think of anything I've done besides retrying, so the only lesson I can take from this is it might take more than a few seconds. ¯\_(ツ)_/¯
