### ISSUE TITLE
Getting random socket hang up

### ISSUE THREAD

**Issue by psaini0212** [microsoft/appcenter-cli#1280]
### **Description**
For the past few days, we are getting random "socket hang up" errors while distributing.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Use Appcenter cli to distribute the release
distribute release -f build/myApp.ipa -R releaseNotes.txt -g Collaborators -a ......

### **Expected behavior**
Release Upload should happen

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - `appcenter distribute release`
2. Which version of the App Center CLI are you using?
    - 2.7.4
3. Which OS version did you experience the issue on?
    - MacOS Catalina
4. What command line/shell are you using?
    - bash
5. What version of Node.js and NPM/Yarn are you using?
    - node-v10.13.0-darwin-x64
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, 
Release-Candidate-iOS/uploads/releases failed, reason: socket hang up
15:53:27      at ClientRequest.<anonymous> (/opt/jenkins_slave/node/node-v10.13.0-darwin-x64/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client-node/node_modules/node-fetch/lib/index.js:1455:11)
15:53:27      at ClientRequest.emit (events.js:182:13)
15:53:27      at TLSSocket.socketOnEnd (_http_client.js:425:9)
15:53:27      at TLSSocket.emit (events.js:187:15)
15:53:27      at endReadableNT (_stream_readable.js:1094:12)
15:53:27      at process._tickCallback (internal/process/next_tick.js:63:19)
15:53:27  Error: Command 'distribute release -f build/SWApp.ipa -R releaseNotes.txt -g Collaborators -a App-Center/Release-Candidate-iOS --debug --token <> --output json' failed with exception "request to https://api.appcenter.ms/v0.1/apps/<>path/uploads/releases failed, reason: socket hang up"

**Comment by DmitriyKirakosyan** [comment]
Hi @psaini0212 

Thank you for getting in touch with us!

Could you please share all logs (not only the error) from the output when using `DEBUG="appcenter-cli:*"`?
Please make sure all sensible information is removed or replaced in your logs.

Alternatively you can create a support ticket by going through **appcenter.ms -> question mark (upper right corner) -> Contact Support** and share your logs with our team there.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
