### ISSUE TITLE
failed to get release id with HTTP status: 403 - Forbidden

### ISSUE THREAD

**Issue by darkandchoco** [microsoft/appcenter-cli#1332]
### **Description**
I'm using appcenter-cli to upload builds from my CI using Bitrise, I have been using this CLI for 2 years+ with Bitrise. Today my CI builds were failing due to this error:

Release upload failed
Error: Loading release id failed with error: failed to get release id for upload id: 825a2f2c-8623-4b6c-bb73-0494e9ec6fab, error: {"succeeded":false,"errorCode":3,"errorMessage":"failed to get release id with HTTP status: 403 - Forbidden"}

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. npm install -g appcenter-cli
2. appcenter distribute release --token [REDACTED] --app MoneyMe/MoneyMeBeta --group Developers --file MoneyMe.ipa -R beta_releasenotes.txt
3. Build was uploaded but was not able to release due to error:

Error: Loading release id failed with error: failed to get release id for upload id: 825a2f2c-8623-4b6c-bb73-0494e9ec6fab, error: {"succeeded":false,"errorCode":3,"errorMessage":"failed to get release id with HTTP status: 403 - Forbidden"}

### **Expected behavior**
Should be able to upload and release a build.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - appcenter distribute release
2. Which version of the App Center CLI are you using?
    - latest from npm install -g appcenter-cli
3. Which OS version did you experience the issue on?
    - macOS 10.15.6 (Catalina)
4. What command line/shell are you using?
    - BITRISE CI

**Comment by oscarcv** [comment]
We tried to upload via the web and it failed due to the same error.

![Captura de pantalla 2021-03-16 a las 9 10 06](https://user-images.githubusercontent.com/45519/111276319-82294c80-8637-11eb-9ed9-5a8d7adcc491.png)

**Comment by oscarcv** [comment]
The status page already reflects that they are having problems in distribution

https://status.appcenter.ms/incidents/ndrll1tls1bg

**Comment by sameeragrawal** [comment]
We are facing this issue too, since March 14, 2021

Command:

`appcenter distribute release -f $IPA_FILE  -a $APP_NAME -r "NOTES" --silent -g $TARGET_GROUP --token $APPCENTER_ACCESS_TOKEN`

Tried with a newly generated token as well, no luck

AppCenter CLI version - 2.7.4
Node - latest LTS v14.16.0
MacOS - 10.15
Command Line - bash script

**Comment by TimoPtr** [comment]
Same issue with the latest release 2.8.0

**Comment by russelarms** [comment]
Hi guys, we're aware of the issue. It is related to the Azure Active Directory outage.
We apologize for the inconvenience while we work to resolve this issue.

**Comment by saikirangit** [comment]
Use curl that seems to be working but it is a 4 step process to upload to the project but so far so good

**Comment by darkandchoco** [comment]
Closing this issue since it is already resolved. Thanks to those who worked on this issue.

**Comment by barneysbro** [comment]
Thanks!
