### ISSUE TITLE
Error: failed to get active users statistics

### ISSUE THREAD

**Issue by mamift** [microsoft/appcenter-cli#1338]
### **Description**
I'm running the below command:

`appcenter analytics audience --debug --app org/app-name`

And receiving this error:

`Error: failed to get active users statistics`

(no further output)

### **Repro Steps**
Please list the steps used to reproduce your issue.

1. `appcenter login` (copy and paste the user token into the terminal)
2. `appcenter analytics audience --debug --app org/app-name`

### **Expected behavior**
**View the output for the `analytics audience` command.**

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
**`appcenter analytics audience --debug --app org/app-name`**

2. Which version of the App Center CLI are you using?
**appcenter version 2.8.1**

3. Which OS version did you experience the issue on?
**Windows 10 version 20H2**

4. What command line/shell are you using?
**PowerShell 5**

5. What version of Node.js and NPM/Yarn are you using?
**node v12.18.4, npm 6.14.8**

6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.
**There is no output with the `--debug` flag.**
I do note that I do get debug output for other commands, such as `appcenter apps  list --debug --app org/app`

**Comment by russelarms** [comment]
Hi @mamift!
Could you try running the command with `-b|--app-build` param?
Is it reproducible on versions prior to 2.8.0 (2.7.4 etc)?

**Comment by mamift** [comment]
I was able to install version 2.7.4, but the I got the same error message; the only new output was a message emitting which version:

```
Using appcenter-cli version: 2.7.4

Error: failed to get active users statistics
```

I also tried logging out and logging back in (where it generated a new user token), but still nothing. I only recently installed node.js 12.18.4 to use this CLI tool.

**Comment by russelarms** [comment]
@mamift have you tried providing `-b|--app-build` param?

**Comment by mamift** [comment]
Yes I did the first time, but it said it was running using version 2.8.1; the `-b` arg didn't seem to do anything. So I installed 2.7.4 using `npm` and it returned the same message.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
