### ISSUE TITLE
Unable to distribute build to distribution group through CLI, but works through UI

### ISSUE THREAD

**Issue by masiton** [microsoft/appcenter-cli#1343]
### **Description**
![2021-03-24_211538](https://user-images.githubusercontent.com/7767671/112377608-4270fd80-8ce6-11eb-8108-dfc3dd484b71.png)

I am trying to distribute existing build to distribution group. The request fails with "undefined" error. 

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Upload release to an App in AppCenter.
2. Use CLI to assign the release to a distribution group through `appcenter disribute releases add-destination --release-id 3 --type group --destination "mygroup"` (I have tried using group name and group ID).
3. Query will fail with error undefined.

### **Expected behavior**
I expected the release to have been distributed to the distribution group.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    See above.
2. Which version of the App Center CLI are you using?
    - 2.8.1
3. Which OS version did you experience the issue on?
    - MacOS 10.15.7
4. What command line/shell are you using?
    - Terminal.
5. What version of Node.js and NPM/Yarn are you using?
    - Don't know.
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list
[log.txt](https://github.com/microsoft/appcenter-cli/files/6200380/log.txt)
`. Include the logs here, don't forget to **omit** any personal/sensitive data.

**Comment by masiton** [comment]
I noticed I'm missing the `--app` argument. With it, it works. Please close.

**Comment by AnastasiaKubova** [comment]
Hi! Glad to hear that your problem was resolved.
Thanks for using App Center!
