### ISSUE TITLE
Getting Error 400 using appcenter_upload

### ISSUE THREAD

**Issue by dreamertheat** [microsoft/appcenter-cli#1478]
Im building a flutter project in the pipeline then suddenly i encountered an error:

 Error 400: {"status"=>400, "name"=>"Error", "message"=>"Missing required body parameter \"body\""}

I had no code change since my successful appcenter upload but when I rerun the pipeline it failed with the error.

This is my whole log https://pastebin.com/YdH8fvX4

This is a snippet of my fastfile (senstive info removed):

```
appcenter_upload(
     api_token: "xxxxxxxxxxxxxxxxx", #Your secret api token from app center
     owner_name: "xxxxxxxx", # Your username on AppCenter
     owner_type: "xxxxxxxxxxxxx",
     app_name: options[:appcenter], # Your AppCenter name
     apk: "../build/app/outputs/flutter-apk/app-"+options[:env]+"-release.apk",
     destinations: "xxxxx,xxxxxx",
     release_notes: sh("cat " + File.dirname(__FILE__) + "./../CHANGELOG.md"),
     should_clip: true,
     notify_testers: "true"
   )
```

**Comment by ryandegruyter** [comment]
Same issue here with a cURL request to fetch upload URL and ID, API seems to misbehave.

`$(curl -X POST --header 'Content-Type: application/json' \
    --header 'Accept: application/json' \
    --header "X-API-Token: ${APPCENTER_APP_TOKEN}" \
    "https://api.appcenter.ms/v0.1/apps/${GROUP}/${NAME}/release_uploads")`

**Comment by ryandegruyter** [comment]
Error has disappeared, seems to have been fixed.

**Comment by dreamertheat** [comment]
> Error has disappeared, seems to have been fixed.

same here, i just rerun the pipeline and it worked already. What seems to be the problem? I didnt see any entries from https://status.appcenter.ms

**Comment by russelarms** [comment]
The Distribute service is experiencing some issues, we are working on resolving them.
From the status page:
`Distribute: Partial Outage`

**Comment by russelarms** [comment]
@dreamertheat @ryandegruyter Our backend team deployed the fix and it must be resolved now. Feel free to reopen this issue if you encounter the problem again.
