### ISSUE TITLE
staged rollouts

### ISSUE THREAD

**Issue by alita-moore** [microsoft/appcenter-cli#1575]
**Is your feature request related to a problem? Please describe.**
I want to release a codepush to my app but I want to also control the blast radius of introducing a bug. It can be challenging as someone who's responsible for managing this process to remember to increment manually.

**Describe the solution you'd like**
The ability to, for example, release 10% at 8pm PST today, 50% at 8pm PST tomorrow, and 100% at 8pm the day following

**Describe alternatives you've considered**
I can...
- manually increment via appcenter website
- manually increment via cli
- create a cron job that uses the cli and run this either on my server or locally
- create a github action that runs to increment at appropriate times

**Additional context**
I will try to do this using an automated github action as that seems most sustainable, but it would be very nice (and likely more reliable) if this logic were backed into appcenter-cli.

**Comment by DmitriyKirakosyan** [comment]
Hi @alita-moore 

Thank you for reporting this feature request and the usage details!

We will prioritize this feature according to our load and the [Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap).
Meanwhile, let's see if anyone else is interested in this feature.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
