### ISSUE TITLE
Find the build_id of the latest release through the API?

### ISSUE THREAD

**Issue by snoopgr2** [microsoft/appcenter-cli#1588]
I've been reading through the help documentation and online and cannot seem to discover how to get a list of build_id's avaliable to my app in AppCenter.  I cannot download the .apk package without the id.  I also can't seem to find the id in the web interface.  There must be something I'm missing in the API to get access to this info.

**Comment by DmitriyKirakosyan** [comment]
Hi @snoopgr2 

Thank you for reaching out to us!

There is no CLI command for getting list of builds. You can check the latest build though using command `appcenter build branches show -b <branch> -app <app-name>`.
Also when you queue a new build, the command will return you a build Id and its URL.

**Comment by DmitriyKirakosyan** [comment]
We haven't heard from you for a while, so I'm closing this issue.
Feel free to reopen if the problem still persists.
