### ISSUE TITLE
ability to push apps to a shared distribution group instead of app specific distribution group

### ISSUE THREAD

**Issue by jsras** [microsoft/appcenter-cli#1603]
**Is your feature request related to a problem? Please describe.**
We currently have 6 apps that we share with the same group of stakeholders, developers and QA testers. This is easy to manage through the organisation distribution groups while it also allows up to make some links public, for sharing in our broader organisation. Right now all builds are distributed manually since the current CLI only supports app-specific distribution groups. When we have quite a lot of people joining and leaving our projects from time to time, it is easier to manage this from a centralised group instead of per app.

**Describe the solution you'd like**
the ability to distribute through CLI to an organisation shared distribution group. 

**Describe alternatives you've considered**
an alternative would be to be able to add a shared group as a reference or link to an app and thus enabling the current implementation in CLI to find the group based on ID.

**Additional context**
If more context is needed just let me know.

**Comment by aleksandr-dorofeev** [comment]
Hi, @jsras 
Thank you for getting in touch with us! 
We will take a look and get back to you with an update.

**Comment by DmitriyKirakosyan** [comment]
Hi @jsras 

You can actually manage distribution groups at an organisation level. Go to `Your Org -> People -> Distribution groups`. Then you can create a shared distribution group on that page and add apps to that group (tab `Apps`).
Is this what you are asking for?

**Comment by jsras** [comment]
@DmitriyKirakosyan actually that is what I have already done - but in the CLI you can only push new apps to a distribution group directly attached to the app - not the other way around, and that is kinda what I need, since I have multiple pipelines in Azure pushing multiple apps to the same distribution group, I would like to avoid having to push to different groups depending on what app I am pushing. Does that make sense?

**Comment by DmitriyKirakosyan** [comment]
Hi @jsras 

Once you create a distribution group in `org -> People -> Distribution groups` and add apps to it, that distribution group will be attached to all added apps there. So if you distribute then a release to a specific app to this group, it will actually be distributed to your shared group and all testers from that group will be notified.
So basically, the group in your app and the group in 'org -> People' is actually the same.

Please correct me if I got something wrong.

**Comment by jsras** [comment]
Hi @DmitriyKirakosyan 

That is exactly what I have done - but when pushing an app through the CLI to the distribution group, I get an error back:
``{"code":"bad_request","message":"Error: Distribution Group with id ... does not exist."} ``

So I did expect it to behave as you are also describing, but it seems there's a link missing, which is what my feature request is all about :)

**Comment by DmitriyKirakosyan** [comment]
Hi @jsras 

So, let's say, you are distributing a release of your app `App1` to distribution group `SharedGroup1`.
Can  you confirm that you can see the distribution group `SharedGroup1` on the Portal under `App1 -> Distribute -> Groups`?

**Comment by jsras** [comment]
Hi @DmitriyKirakosyan 

So your feedback had me go through our entire setup once more, since I did not immediately see our shared distribution group in the apps group (thanks for bringing that to my attention), and it does actually seem to work now, after reassuring the app was correctly added to the group!

Sorry for the confusion around this, and thanks for the help!

Closing this as it has been resolved :)
