### ISSUE TITLE
Please release new versions with security vulnerabilities fixed more often

### ISSUE THREAD

**Issue by PGHM** [microsoft/appcenter-cli#1616]
You disabled the REST API and forced us to use this CLI program. I think now you have a responsibility to actually update it more often if you have one zillion dependancies and many of them have vulnerabilities. Our repo now has 6 high severity alerts, all from AppCenter-CLI, some of them already fixed in your repo, but could you actually make releases more often?

**Comment by DmitriyKirakosyan** [comment]
Hi @PGHM 

Thank you for getting in touch with us!

Could you please clarify what REST API are you referring to? App Center Open API is working as expected and there is no plans for disabling it.

Regarding the releases frequency, you point absolutely makes sense to me. We will start CLI release process right after the App Center SDK Release which is in progress right now. 

I'm closing this issue but feel free to reopen it if you have additional questions.

**Comment by PGHM** [comment]
I am referring to this case: https://twitter.com/AppCenterStatus/status/1336163721073238016

After that it was said that API is being "deprecated" https://twitter.com/AppCenterStatus/status/1336433781721321472 (but really it was just turned off without warning)

Then I asked the support and they answered "The REST API endpoints corresponding with release_uploads are no longer available for use." and then this https://status.appcenter.ms/incidents/f4s6fdplt9qm

So from all those messages I got the picture that REST API for uploading is now going to be disabled, please use CLI in the future.

If the API is still usable, I would be glad to use that instead of the CLI client in our scripts.

**Comment by DmitriyKirakosyan** [comment]
Thanks for the clarification, now I understand what you mean.

Have you tried using this API: https://docs.microsoft.com/en-us/appcenter/distribution/uploading#upload-new-release?

As per status.appcenter.ms:

> - If you are using the API directly and cannot use the CLI, we have now also updated our documentation to outline the steps you need to take to update existing direct API clients:
> https://docs.microsoft.com/en-us/appcenter/distribution/uploading#upload-new-release

**Comment by PGHM** [comment]
Ok, thanks, this was the first time I heard that there was a new API, in the original "App Center Release Upload API Deprecation Update" notice there was no mention about the new API, there sure is now. We would have never changed to use the CLI if we knew this was a possibility back then. The support reply also indicated that the API was just going to be removed. So better communication next time would be appreciated.

But anyway, thanks for the clarification now and we'll try the new API instead of the CLI.
