### ISSUE TITLE
Allow Distribution to Organisation-Level Groups with an App Token

### ISSUE THREAD

**Issue by slarti-b** [microsoft/appcenter-cli#1647]
As I understand it (and I'm fairly new to the App Center, although an experienced programmer), you can create distribution groups in two ways
* Create an organisation-level group and then associate it with the relevant apps
* Create an app-specific group

That's fine.  For example, I might have an organisation-level group with my internal testers in, and then an app-specific group with any testers from my client who are only relevant for that specific app.

I am automating deploying/distributing the apps, using the AppCenter CLI.  This means I need a token.  Again, tokens come in two flavours:
* App Tokens specific to a particular app
* User Tokens tied to my user

Since I am automating from a CI system (Jenkins in my case), I clearly want to use App Tokens because
* The deployment is being run automatically, by the CI system, so is not being run by an individual user
* If this leaks it only affects one app, so on basic security principles of minimising access I should use app tokens

However, it appears that I cannot distribute to an organisation-level group if I authenticate using an App Token!  I would like to run `appcenter distribute release --token "$APP_TOKEN" --group "$ORG_GROUP"` where `$APP_TOKEN` is an App Token and `$ORG_GROUP` is an organisational-level group. (Some parameters were removed for brevity in the example - this should work either when uploading (so also with `--file`, etc.) or when using an existing build with `add-destination`, etc.)

I can see that this should be restricted to those organisation-level groups already connected to the app in question (but assume that would be the case anyway, even with a User Token).  

As it stands I am left with a choice of either maintaining multiple, identical, application-level groups or using user tokens for CI processes which are not done by that user.  Neither option seems right to me.

To be honest, I see this as a bug rather than a feature request (for the reasons above, none of the functional options seem correct). However, it was mentioned in #856 that this was deliberate but that _"it's [allowing what I describe here] something that we're currently talking about"_.  However, I couldn't find an actual issue on it (and #856 was closed) so creating this.

**Comment by wisdeom** [comment]
Hi there, let's discuss this topic on the existing feature request on the main repository. Sharing the link for your visibility. Thanks again for sharing your feedback. We don't take it for granted. 

https://github.com/microsoft/appcenter/issues/2219#issuecomment-883193309
