### ISSUE TITLE
Question: distribute release vs distribute stores/groups publish

### ISSUE THREAD

**Issue by SebastianRumohr** [microsoft/appcenter-cli#1663]
Hi there,  
I'm confused. What's the difference between the command  
`appcenter distribute release --store "Alpha" ...`  
and
`appcenter distribute stores publish --store "Alpha" ...`.

Same for  
`appcenter distribute release --group "..." ...`  
and
`appcenter distribute groups publish --group "..." ...`.

Thank you very much.

**Comment by DmitriyKirakosyan** [comment]
Hi @SebastianRumohr ,

Thank you for reaching out to us!

The commands are identical and do the same job. The only difference is in their specification. You can use either of them.
You can see [here](https://github.com/microsoft/appcenter-cli/blob/master/src/commands/distribute/stores/publish.ts#L64) that `distribute stores publish` calls `distribute release` without any additional logic.

I'm closing this issue but feel free to reopen if you have additional questions.

**Comment by SebastianRumohr** [comment]
Thank you for the fast response 😊
