### ISSUE TITLE
Error: Failed to create release upload for ***Pathoofzip***.zip. Backend response: The server is busy now. Try again later

### ISSUE THREAD

**Issue by trshyam01** [microsoft/appcenter-cli#1769]
### **Description**
Please describe the issue you are facing using the CLI.
Error: Failed to create release upload for ***Pathoofzip***.zip. Backend response: The server is busy now. Try again later

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Upload using CLI

### **Expected behavior**
Upload fails immediately with the message : Error: Failed to create release upload for ***Pathoofzip***.zip. Backend response: The server is busy now. Try again later

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - e.g. `appcenter tokens list`
2. Which version of the App Center CLI are you using?
    - e.g. 2.7.4
3. Which OS version did you experience the issue on?
    - e.g. Windows 10 + appcenter Version 2.10.6
4. What command line/shell are you using?
    - e.g. Shell 5.8 /bin/zsh
5. What version of Node.js and NPM/Yarn are you using?
    - e.g. node v12.19.0, npm 6.14.8
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.

**Comment by ugurcany** [comment]
same error here as well. I guess you couldn't fully resolve the problem from the previous week.

**Comment by aleksandr-dorofeev** [comment]
Hi @trshyam01 @ugurcany 
At the moment there are some problems on the backend side. The team is working on resolving the problem. You can track the status of the service on the [status page](https://status.appcenter.ms).

**Comment by ugurcany** [comment]
We are leaving app center because of recent down situations. Unfortunately, doesn't worth it anymore.

**Comment by lucen-ms** [comment]
@ugurcany we are sorry but we have to limit the current high load of our free distribution service - there is simply too many requests to process at this moment.
