### ISSUE TITLE
When using appcenter CLI in scripts, CLI's errors are not reported to stderr

### ISSUE THREAD

**Issue by sameeragrawal** [microsoft/appcenter-cli#1777]
### **Description**

When using appcenter CLI in scripts, CLI's errors are not reported to stderr
This causes error stream logs to be missed out.

The script reports all errors to stdout

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. run an invalid command e.g.
  `appcenter distribute releases list --app <invalid-app-identifier>    1>out.txt    2>err.txt`
2. when command complete, check the out.txt and err.txt files

### **Actual behavior**

err.txt is empty
out.txt has the error log

### **Expected behavior**

err.txt should have the actual error message

### **Details**

1. Is there a particular beacon/command that you are having trouble with?
    - No, happening with all commands upon error
2. Which version of the App Center CLI are you using?
    - 2.10.7
3. Which OS version did you experience the issue on?
    - Mac
4. What command line/shell are you using?
    - Shell 5.8 /bin/zsh
5. What version of Node.js and NPM/Yarn are you using?
    - node v12.22.8 (npm v6.14.15)
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.

**Comment by AnatolyPristensky** [comment]
Hello @sameeragrawal and thank you for your contribution!
I've tested and merged your [PR](https://github.com/microsoft/appcenter-cli/pull/1778).
