### ISSUE TITLE
IOS - Error: The asset cannot be uploaded. Try creating a new one

### ISSUE THREAD

**Issue by phuocantd** [microsoft/appcenter-cli#1802]
### **Description**
Error when codepush upload react native ios when I update appcenter-cli yesterday

# Version
- appcenter-cli: 2.10.8
- react-native-code-push: 7.0.1

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Could you please share some more details about your issue:
- Which command caused this issue?
- Could you please share the logs?
- Did you get this error before updating `appcenter-cli`?
- Did you try to clean the project cache?

**Comment by phuocantd** [comment]
> Hi! Thanks for getting in touch with us! Could you please share some more details about your issue:
> 
> * Which command caused this issue?
> * Could you please share the logs?
> * Did you get this error before updating `appcenter-cli`?
> * Did you try to clean the project cache?

good use when in appcenter-cli 2.10.7

**Comment by aleksandr-dorofeev** [comment]
Hi @phuocantd 
For more efficient assistance we need more information.
Could you please answer the questions Anastasia asked in her last message.

**Comment by phuocantd** [comment]
Hello @aleksandr-dorofeev 
 - cmd: appcenter codepush release-react -a <project> -d Staging
 - log: Error: The asset cannot be uploaded. Try creating a new one
 - error when I update version 2.10.8
 - I haven't cleaned cache yet

**Comment by aleksandr-dorofeev** [comment]
I was not able to reproduce this issue, the command worked as expected for me. Do you face this error message each time you run the command or periodically?

**Comment by phuocantd** [comment]
> I was not able to reproduce this issue, the command worked as expected for me. Do you face this error message each time you run the command or periodically?

downgrade version 2.10.7 working for me
