### ISSUE TITLE
upload sourcemaps

### ISSUE THREAD

**Issue by pvinis** [Microsoft/appcenter-cli#181]
we can upload symbols with this. can you add uploading of sourcemaps too? so we can use this tool to upload everything needed for a react native app to mobile center.

**Comment by amchew** [comment]
@pvinis thanks for the feature request, are you available for a quick call to discuss this? I'd like to hear your feedback. I just DM-ed you via your email

**Comment by sharnik** [comment]
I remember it was possible in the previous version of the CLI (when it was named `mobile-center`). I had a script like that for iOS releases:

```ruby
    Dir.chdir("..") do
      sh 'unzip FirstScreen.app.dSYM.zip && zip -r mobile-center-symbols.zip FirstScreen.app.dSYM index.ios.map'
      sh 'yarn run mobile-center crashes upload-symbols -- -s "mobile-center-symbols.zip" --app "my-account/my-app-ios"'
      sh 'rm -rf FirstScreen.app.dSYM index.ios.map mobile-center-symbols.zip'
    end
```

Is it still possible? How can I send symbols for an Android release?

I tried consulting the documentation about uploading the symbols manually here: https://docs.microsoft.com/en-us/appcenter/crashes/react-native, but it talks about an "Incoming" page that is not visible anymore.

**Comment by lxcid** [comment]
I am having issue with this too. Does the file of the sourcemap affect?

**Comment by amchew** [comment]
Hi @pvinis, @sharnik and @lxcid , I'm sorry for the delayed reply on this. @pvinis we support react-native source maps for iOS. You can do this by adding the mapping file to the symbol.zip (see documentation [here](https://docs.microsoft.com/en-us/appcenter/crashes/react-native). @sharnik thanks for pointing out about the outdated "incoming" page! We've made the improvements to the documentation and pending for the [PR](https://github.com/MicrosoftDocs/appcenter-docs/pull/79) to be merged (thanks @gordey4doronin for the quick work!). 

@sharnik I'm checking if you can send symbols for an Android release - will update again. 

@lxcid , could you elaborate on what you mean by "if the file of the source map affects"?

**Comment by amchew** [comment]
Hi @sharnik, sending symbols for an Android release is not supported yet. Is this a feature request that you’re looking at? (FYI @saraford)

**Comment by amchew** [comment]
Hey @pvinis , @sharnik and @lxcid , 

We haven't heard back from you in some time, and I'll be closing this ticket for now. Please reach back again if you have questions anytime, and we'll reopen this ticket again.

@sharnik, also we've submitted a PR to update the documentation. This will be live in the next week. 

Thank you for your support!
Amanda
