### ISSUE TITLE
appcenter build branches update

### ISSUE THREAD

**Issue by anthonycmain** [microsoft/appcenter-cli#1813]
**Is your feature request related to a problem? Please describe.**
We would like to be able to set the build configuration for our branches

**Describe the solution you'd like**
Being able to supply either via scripted args or imported directly from an environment file it would be great if we could import env variables via the CLI so we don't have to paste them in (we have about 20 for each project)

**Comment by AnatolyPristensky** [comment]
Hello, @anthonycmain !
Thanks for getting in touch with us!

This is not an SDK issue, please open a [support ticket](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) on the App Center portal.

**Comment by anthonycmain** [comment]
Did you mean this is an SDK issue? This issue is raised regarding the CLI not the SDK

**Comment by AnatolyPristensky** [comment]
@anthonycmain sorry for misunderstanding. I mean that this is not a CLI issue, so please open a [support ticket](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) on the App Center portal.
