### ISSUE TITLE
appcenter distribute groups download is downloading the wrong build

### ISSUE THREAD

**Issue by kuyazee** [microsoft/appcenter-cli#1815]
### **Description**
When running the command `appcenter distribute groups download` it is not downloading the latest release but rather the build with the highest build number.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Upload a build with the ff version code 1.0.0 (100)
2. Upload another build with the ff version code 1.0.0 (20)
3. Run the command below
```
appcenter distribute groups download \
   -a "sample-app" \
   -g "sample group"
```

### **Expected behavior**
Since there are 2 builds

Build 1: 1.0.0 (100)
Build 2: 1.0.0 (20) << this is the latest

Build 1.0.0 (20) should be the one being downloaded

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - appcenter distribute groups download
2. Which version of the App Center CLI are you using?
    - appcenter version 2.10.8
3. Which OS version did you experience the issue on?
    - MacOS
4. What command line/shell are you using?
    - zsh
5. What version of Node.js and NPM/Yarn are you using?
    - 8.3.1

**Comment by AnatolyPristensky** [comment]
Hello @kuyazee,
Thank you for getting in touch with us. 
We will investigate it further and update this thread once get results.

**Comment by alexnekrashevich** [comment]
Hello @kuyazee!

```
...it is not downloading the latest release but rather the build with the highest build number.
```

Is there a chance that you may create another release with the same sort version, but with higher build version, like 1.0.0 (120)? 

Our team has fixed this issue with sorting by build version a long time ago, so I suppose that sorting by date may go wrong sometimes. 
We will appreciate it much if you check if it still downloads the earliest release of this sort version. Thank you!

**Comment by cdubwisdom** [comment]
I am also currently seeing this issue with multiple builds of varying versions
Release | Version     | Date        |
154        | 5.1.0(100) | 10/27/23 |
153        | 5.1.0(99)   | 10/26/23 |
.......
135        | 5.1.1(74)   | 09/15/23  | <---- This will be the default download even though it is a month old

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this issue in the next year, I'm closing it.
