### ISSUE TITLE
Promote is promoting the oldest matching release not newest

### ISSUE THREAD

**Issue by nhannah** [microsoft/appcenter-cli#1821]
### **Description**
Promote is now promoting oldest codepush build for a given version

### **Repro Steps**
1. Create code push to staging
2. Promote code push to release
3. Create 2nd code push to staging
4. Promote code push to production via cli (you will get an error)
5. promote 2nd codepush to production via UI
6. Create 3rd code push to staging
7. Promote code push to production via cli

### **Expected behavior**
Code push should promote the latest matching release, not the first.

### **Details**
Upon completing step 7 the first code push, created in step 1, promoted in step 2, will now be in production, creating a regression. I believe this could be related to the #1179 fix as the timing coincides with the change and relates to the same.

**Comment by seankwalker** [comment]
+1, we're seeing the same issue

**Comment by alexnekrashevich** [comment]
Hello @nhannah!

We have already encountered some issues that are similar to yours. We hope that we will come with a solution quickly, and we will surely keep you informed on this! Thank you for your report!

**Comment by seankwalker** [comment]
Any updates here?

**Comment by telmen** [comment]
anything?

**Comment by liaojiwei666** [comment]
any solution?

**Comment by DmitriyKirakosyan** [comment]
Hi team, we are tracking this item on our board, but unfortunately no ETA yet.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
