### ISSUE TITLE
Replace azure-storage per deprecation notice

### ISSUE THREAD

**Issue by owjsub** [microsoft/appcenter-cli#1822]
Replace azure-storage per deprecation notice: "Please note: newer packages @azure/storage-blob, @azure/storage-queue and @azure/storage-file are available as of November 2019 and @azure/data-tables is available as of June 2021. While the legacy azure-storage package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Migration guide can be found: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/MigrationGuide.md"

**Comment by AnatolyPristensky** [comment]
Hello @owjsub ,
Thank you for your proposal. I've marked it as a feature request on our internal dashboard.

**Comment by DanBrown-TechSmith** [comment]
There are several other deprecated packages as well it seems:

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated superagent@5.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue as fixed. The azure-storage package was replaced in version 3.0.0.

@DanielBrown-ranger1968, all mentioned packages were removed or updated except formidable@1.2.6 and superagent@5.1.0. We don't have plans to update them at this moment.
