### ISSUE TITLE
Invite User via CLI

### ISSUE THREAD

**Issue by corytrese** [microsoft/appcenter-cli#1847]
**Is your feature request related to a problem? Please describe.**
Add an CLI command that invites a user to a Distribute group.

**Describe the solution you'd like**
The CLI acts just like the web does.

**Describe alternatives you've considered**
I have tried pasting thousands of emails into the web console. It performs poorly.

**Additional context**
Since you can create new apps, groups and deployments it makes sense that you can create users.

**Comment by DmitriyKirakosyan** [comment]
Hi @corytrese , thank you for reaching out to us!

Have you tried command `appcenter distribute groups update`? eg:
```
appcenter distribute groups update -g <group-name> --add-testers <emails-separated-by-space>
```
More info: `appcenter distribute groups update --help`.

If you want to invite a user to your org, you can use this command:
```
appcenter orgs collaborators update -n <org-name> --add-collaborators <list-of-users-to-invite>
```
More info: `appcenter orgs collaborators update --help`.

Please let me know if it answers your question.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue, but let you know if you have additional questions.

**Comment by nehasonakul777** [comment]
@DmitriyKirakosyan : 
I want to integrate the Appcenter CLI with Jenkins and want to pass the CLI command that invites a user to an org in Jenkins Job.

Can you please guide me how can I do that, how I can integrate and run the Appcenter CLI commands from Jenkins job.
