### ISSUE TITLE
multiple test-parameter

### ISSUE THREAD

**Issue by davidsynott** [microsoft/appcenter-cli#1883]
### **Description**
I am using the CLI via azure pipeline + command line on a windows machine. I successfully trigger a test run but I am trying to pass environment variables to the xamaring UI windows c# test application which is running. Only the last --test-parameter is passed to the application. I think we should be able to pass more than one

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Create a valid appcenter text cli command. 
2. add multiple --test-parameter switches to the command such as [ ... --test-parameter="test_env=AAA=111" --test-parameter="test_env=BBB=222"
3. When sourcing the environment variable in the c# code with Environment.GetEnvironmentVariable("AAA") = NOTHING but Environment.GetEnvironmentVariable("BBB") returns 222

### **Expected behavior**
I thought that each switch should pass the value to the test platform which could be interpreted. this page https://docs.microsoft.com/en-us/appcenter/test-cloud/environment-variables alludes to the idea that multiple switches should be passable

I cannot find anything to suggest that I am right or wrong. 

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - e.g. `appcenter --test-parameter "test-env=A=1"` with multiple values
2. Which version of the App Center CLI are you using?
    - e.g. 2.10.8
4. Which OS version did you experience the issue on?
    - e.g. Windows 11 
5. What command line/shell are you using?
    - e.g. Shell 5.8 /bin/zsh
6. What version of Node.js and NPM/Yarn are you using?
    - e.g. node v14.17.5, npm 6.17.1
7. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.

**Comment by DmitriyKirakosyan** [comment]
Hi @davidsynott , thank you for reporting this issue.

I tested this behaviour on the CLI side and it does identify the list of values properly and sends all values to the backend. I'll ask the backend team and get back to you with an update.

**Comment by davidsynott** [comment]
Hi Dima, I was advised on another forum to use the pattern

--test-parameter "test_env=KEY1=VALUE1|KEY2=VALUE2|KEY3=VALUE3"

which worked. (the use of pipe character)

I appreciate this might not be something which appcenter is parsing /
processing / dealing with, so might not be something you might be concerned
about.

Thanks
David

**Comment by DmitriyKirakosyan** [comment]
@davidsynott , thanks for the update. Yes, this format is exactly the one sending to backend. CLI converts the input array of args into such format and then sends it. I wonder if the conversion didn't work for you for some reason..

**Comment by davidsynott** [comment]
This format worked immediately. I just could not find any documentation to
suggest that this was the correct format

This may be standard format, independent of appcenter-cli, but I'm a
backend developer, falling in DevOps and I could not work out out myself.

Thanks for the confirmation.

Much appreciated

**Comment by DmitriyKirakosyan** [comment]
Hi @davidsynott , we tested the scenario with multiple `--test-parameter` args and everything worked as expected for us.
Could you please share the exact command you used to reproduce the issue and the way you checked if all envars are present afterwards?

**Comment by davidsynott** [comment]
Yes. It works as you describe. All is well. I am agreeing with you.

There is just no documentation to point people towards this format. I could
find on thing on the internet to know that "|" acts as a delimiter.

Please close the ticket. All good.

**Comment by DmitriyKirakosyan** [comment]
@davidsynott , I mean it should also work as you initially tried. We tested the format `--test-parameter="test_env=AAA=111" --test-parameter="test_env=BBB=222"` and it worked fine for all types of tests.
That is why I'm asking you to provide the exact command you used when it didn't work for you, and the method you used to check the envars on the test side.

**Comment by DmitriyKirakosyan** [comment]
We haven't heard from you for a while, so I'm closing this issue. Please let me know if you have any questions.
