### ISSUE TITLE
Site is down https://appcenter.ms!!

### ISSUE THREAD

**Issue by billnbell** [microsoft/appcenter-cli#1913]
Site been down for hrs!!

**Comment by DmitriyKirakosyan** [comment]
Hi @billnbell , I'm sorry for the inconvenience. The portal should work as expected now.

If you encounter any similar issue in future, please use https://status.appcenter.ms/ to check the portal status, and if the status is OK but you cannot access the portal main page, please create a ticket on the https://github.com/microsoft/appcenter repository.

**Comment by billnbell** [comment]
Yeah I did that and at the time is said: All issues are resolved.

Also to submit a case the portal was down - so I could not do that either!

Good to know about https://github.com/microsoft/appcenter  but as soon as I posted a @microsoft twitter reference it was resolved in 10 minutes. Social watching works.
