### ISSUE TITLE
Feature Request: Support for managing Shared Distribution Groups in App Center CLI

### ISSUE THREAD

**Issue by jayro4ever** [microsoft/appcenter-cli#1924]
Hi,

We manage the addition of new testers to our apps' distribution groups via the App Center CLI. However, we have many apps and it would really help us to simply add shared distribution groups to an app via the CLI. It appears that this is only possible via the web portal, and I know the org-level functionality is slim, but CLI support would save us lots of time and effort. 

Thank you!

**Comment by DmitriyKirakosyan** [comment]
Hi @jayro4ever , thank you for the feature request!

**Comment by spjass** [comment]
I would also be very interested in this feature. We are using codemagic to build multiple different variants of an application and distribute them to app center test users, and it's currently very tedious to maintain multiple lists of testers for each application instead of using org-level groups.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
