### ISSUE TITLE
Command line bug after releasing and update

### ISSUE THREAD

**Issue by Rc85** [microsoft/appcenter-cli#1928]
### **Description**
After executing `appcenter codepush release-react -a <owner>/<appName>`, the command line bugs out. When pressing the arrow up or down, it doesn't show previous executed commands. It shows `^[[A` or `^[[B`. If I press backspace, it deletes the entire word rather than characters.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Execute `appcenter codepush release-react -a <owner>/<appName>`
2. Press arrow up or down or backspace.

### **Expected behavior**
CMD behaving normally.

### **Details**
App center CLI version: 2.10.10
react-native info:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 11.99 GB / 31.93 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210102.202219.0 - C:\Users\roger\watchman\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: 15.9.28307.1401 (Visual Studio Community 2017)
  Languages:
    Java: 17.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.68.1 => 0.68.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by DmitriyKirakosyan** [comment]
Hi @Rc85 , this is a normal behaviour when you perform some long lasting command. It is not related to the appcenter-cli.

I'm closing this issue, but feel free to ask any additional questions.
