### ISSUE TITLE
Publish from App Center to Intune apk as Managed Google Play

### ISSUE THREAD

**Issue by wiandrade** [microsoft/appcenter-cli#1983]
I'm currently trying to publish apps from App Center to Intune, but at publish time the object is generated as type "**Android Line of Business App**" and not as "**Managed Google play app**" which is what I really need. Is there a variable using the App Center CLI "appcenter distribute stores publish" command to tell it what type of object I want to create?

Thank you!

**Comment by aleksandr-dorofeev** [comment]
Hi @wiandrade , thank you for reaching out to us!
I'm not sure i fully understand your scenario. Could you elaborate more on the issue? 
Can you confirm that you followed this [guide](https://docs.microsoft.com/en-us/appcenter/distribution/stores/intune#publishing-through-the-cli)? 
Can you workaround the problem by publishing manually or using open API?

**Comment by aleksandr-dorofeev** [comment]
We haven't heard from you for a while, so I'm closing this issue. Please let me know if you have any questions.
