### ISSUE TITLE
Request last active time from user

### ISSUE THREAD

**Issue by Vacxe** [microsoft/appcenter-cli#2005]
**Is your feature request related to a problem? Please describe.**
We have a CLI approach for testers access management. However it really hard to manage inactive testers.

**Describe the solution you'd like**
Add to CLI possibility to request last action timestamp. 

**Describe alternatives you've considered**
Or last log in time

**Comment by AnatolyPristensky** [comment]
Hello @Vacxe, unfortunately, right now we have no this API. 
So first of all we need to add an appropriate API on backend side and then add it into the appcenter-cli. 
Right now these kind of features have lower priority and we have no any ETA. 
Let's see how many upvotes this feature will get.

**Comment by Vacxe** [comment]
@AnatolyPristensky hey mate! Do you have any updates about his feature request?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
