### ISSUE TITLE
appcenter codepush using Xamarin / Android

### ISSUE THREAD

**Issue by christiannagel** [microsoft/appcenter-cli#2015]
I'm trying to publish a .NET MAUI app using the appcenter CLI.

using `appcenter codepush release` with the options `--update-contents-path`, `-a`, and `--target-binary-version` I get the error **Deployment "Staging" does not exist**.

When I try to create a deployment (`appcenter codepush add Staging`), the command fails with **Not supported platform / OS combination: Xamarin / Android**. 

It looks like the deployment name is required with `appcenter codepush release`, but not supported with this platform / OS combination.

AppCenter CLI version: 2.10.10

**Comment by DmitriyKirakosyan** [comment]
Hi @christiannagel , thank you for reaching out!
AppCenter CodePush supports ReactNative and Cordova only. See [docs](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/#2-codepush-ify-your-app).
Unfortunately, there is no way to use codepush with Xamarin.

You can use `appcenter distribute release` for your app.

I'm closing this item, but feel free to ask any additional questions.
