### ISSUE TITLE
Integrate the AppCenter CLI with Jenkins

### ISSUE THREAD

**Issue by nehasonakul777** [microsoft/appcenter-cli#2056]
**Is your feature request related to a problem? Please describe.**
I want to integrate the AppCenter CLI with Jenkins and want to pass the CLI command in Jenkins Job that invites a user to an org.

**Describe the solution you'd like**
please guide me, how I can integrate AppCenter CLI - > Jenkins and run the Appcenter CLI commands from Jenkins job.
I am precisely looking for inviting user to an organisation via Jenkins job.

**Describe alternatives you've considered**
Not Any.

**Additional context**
As AppCenter has a CLI, it can be integrated with Jenkins like any other CLI.

**Comment by AnatolyPristensky** [comment]
Hello @nehasonakul777, unfortunately, right now we have no this API.
So first of all we need to add an appropriate API on backend side and then add it into the appcenter-cli.
Right now these kind of features have lower priority and we have no any ETA.
Let's see how many upvotes this feature will get.

**Comment by nehasonakul777** [comment]
@AnatolyPristensky  : 
I am aware of these commands.
I wanted to know how we can integrate them with Jenkins and automate the same.

Can you let me know, how we can integrate APP-Center Cli with Jenkins and execute these commands.

**Comment by AnatolyPristensky** [comment]
@nehasonakul777 Please refer to the jenkins [documentation](https://www.jenkins.io/doc/book/getting-started/) on how to install app on the job agent and run shell command/script. Actually appcenter-cli is a common CLI application which will run whenever you install it.

We doesn't own Jenkins service. 
Please contact jenkins support if you get difficulties on the installation/run step.

**Comment by nehasonakul777** [comment]
Thank you.
