### ISSUE TITLE
release-react command no longer produces hermes byte code bundle when hermes is enabled

### ISSUE THREAD

**Issue by jdrorrer** [microsoft/appcenter-cli#2070]
### **Description**
`release-react` command no longer produces hermes byte code bundle when hermes is enabled. I no longer see the "Converting JS bundle to byte code via Hermes..." message and you can tell the bundle is not hermes because it takes longer to install + the app startup time is taking longer. React native version 0.64.2 with hermes enabled.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. run appcenter `release-react` command
2. observe the output from cli
3. check out the js bundle in appcenter
4. observe that the bundle is not hermes byte code

### **Expected behavior**
I would expect to see the "Converting JS bundle to byte code via Hermes..." message when running `release-react` command with hermes enabled. I would also expect the js bundle to include hermes byte code rather than being a strictly javascript bundle.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - e.g. `appcenter tokens list`
    - `appcenter release-react`
2. Which version of the App Center CLI are you using?
    - e.g. 2.7.4
    - 2.11.0
5. Which OS version did you experience the issue on?
    - e.g. Windows 10 version 20H2, Ubuntu 20.04.1 LTS, macOS BigSur 11.1
    - macOS BigSur 11.5.2
6. What command line/shell are you using?
    - e.g. Shell 5.8 /bin/zsh
    - whatever version is run on github actions
7. What version of Node.js and NPM/Yarn are you using?
    - e.g. node v12.19.0, npm 6.14.8
    - node v14.20.0, npm v6.14.17
8. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.

**Comment by DmitriyKirakosyan** [comment]
Hi @jdrorrer , thank you for this report!

Is it iOS? Can you show your Podfile? I'm interested in the part with hermes config.
Have you tried to revert CLI to 2.10.10 and check if it works?

**Comment by jdrorrer** [comment]
Hey @DmitriyKirakosyan it is for both iOS and android. I just ran the command with appcenter-cli v2.10.10 and it is bundling with hermes.

Here's the relevant parts of our Podfile if it helps:
```
platform :ios, '12.1'

...

target 'snackpass' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

...

end
```

**Comment by AnatolyPristensky** [comment]
Hello @jdrorrer, thank you for the information. I've filed an item on our internal dashboard to check and test your case. 
Will update this thread once get results.

**Comment by think-divergent** [comment]
After upgrade to RN 69, we noticed this behavior as well. 

In particular, there seems to be several more attributes now so the extra comma at the end of the hermes_enabled line causes [this regex](https://github.com/microsoft/appcenter-cli/blob/master/src/commands/codepush/lib/react-native-utils.ts#L504) to fail.

Here's relevant section in the pod-file. 

```
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
```
As a workaround, we changed that line to test the whole file on a line by line basis 
```
      return podFileContents.split('\n').map(l=>l.trim()).filter(line=>
        /^([^#\n]*:?hermes_enabled(\s+|\n+)?(=>|:)(\s+|\n+)?true\,?(\s)*)$/.test(line)
      ).length>0
```

**Comment by DmitriyKirakosyan** [comment]
This PR https://github.com/microsoft/appcenter-cli/pull/2113 should help in such case. You can specify manually if hermes is enabled.

As for the regex improvement, a contribution PR is very welcome :)
