### ISSUE TITLE
Unknown error when trying to create a new app with special characters in display name

### ISSUE THREAD

**Issue by denissb** [microsoft/appcenter-cli#2073]
### **Description**

When trying to generate a new apps with the `appcenter-cli` our previously written script that was using it started having errors. The API fails with  `Name containing characters apart from alphanumeric, hypen, space and underscore are not allowed.`, however the `app-name` is not a required argument for this command and the `display-name` should support special characters (It did before)

### **Repro Steps**
1. Use the cli command, e.g :`appcenter orgs apps create -p React-Native -n "MY-ORG" -o "iOS" -d "APP+ (iOS)" --output json`
2. Get an error from the CLI:
```
{"succeeded":false,"errorCode":3,"errorMessage":"the request was rejected for an unknown reason"}
```
API response behind the call (logged from `node_modules/appcenter-cli`)
```
{"statusCode":400,"request":{"rawResponse":false,"queryString":{},"url":"https://api.appcenter.ms/v0.1/orgs/MY-ORG/apps","method":"POST","headers":{"Content-Type":"application/json; charset=utf-8","user-agent":"appcenterCli/2.11.0 NodeJS/v16.10.0 darwin/21.5.0","x-api-token":"a61e92ca2db02079492ef12d1b6c24f55b01933e","internal-request-source":"cli","diagnostic-context":"7f1f1641-b35e-407d-9943-8a1f69fe9e54","cli-command-name":"orgs apps create"},"body":"{\"display_name\":\"APP+ (iOS)\",\"os\":\"iOS\",\"platform\":\"React-Native\"}","strictSSL":false,"agent":{"options":{"proxy":{"host":"dk.proxy.mid.dom","port":"80","protocol":"http:"}},"proxyOptions":{"host":"dk.proxy.mid.dom","port":"80","protocol":"http:"},"maxSockets":null,"requests":[],"sockets":[],"_events":{},"_eventsCount":1}},"response":{"body":"{\"error\":{\"code\":\"BadRequest\",\"message\":\"Validation error: Name containing characters apart from alphanumeric, hypen, space and underscore are not allowed.\"}}","headers":{"date":"Mon, 29 Aug 2022 16:37:49 GMT","x-powered-by":"Express","access-control-allow-origin":"*","access-control-allow-methods":"GET, POST","access-control-allow-headers":"","access-control-allow-credentials":"false","access-control-max-age":"0","strict-transport-security":"max-age=15724800; includeSubDomains","content-length":"158","content-type":"application/json; charset=utf-8","via":"1.1 syswsa1-dk1.mid.dom:80 (Cisco-WSA/12.0.3-007)","connection":"close"},"statusCode":400},"code":"BadRequest","body":{"error":{"code":"BadRequest","message":"Validation error: Name containing characters apart from alphanumeric, hypen, space and underscore are not allowed."}}}
```

### **Expected behavior**
The application should be created with the specified display name and serialised application name

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    `appcenter orgs apps create -p React-Native -n "MY-ORG" -o "iOS" -d "APP+ (iOS)" --output json`
2. Which version of the App Center CLI are you using?
    -2.11.0
4. Which OS version did you experience the issue on?
    macOS Monterey 12.5.1
5. What command line/shell are you using?
    `/bin/zsh`
6. What version of Node.js and NPM/Yarn are you using?
    `v16.10.0`

**Comment by AnatolyPristensky** [comment]
Hello @denissb,
This change was made to sanitize input fields for users, orgs and apps.
I've contacted appropriate team, will update this thread once get more information.

**Comment by AnatolyPristensky** [comment]
@denissb 
We've got response from the appropriate team and they confirmed that this behaviour of appcenter-cli is а security feature. Currently they have PR in-review to add characters like + ( ) to the permitted characters list. It should be fixed soon from backend side, so I'm closing this issue.

**Comment by AnatolyPristensky** [comment]
@denissb, JFYI, the fix of your issue has been deployed to production.

**Comment by denissb** [comment]
Thank you @AnatolyPristensky 🎸🚀
