### ISSUE TITLE
Support for scope when creating new API tokens

### ISSUE THREAD

**Issue by michaelhahn-doka** [microsoft/appcenter-cli#2120]
**Is your feature request related to a problem? Please describe.**
Creating app or user api tokens allows to define the scope of the token (full, viewer [named readonly in the UI]) when doing that via the UI. Right now this is not supported when creating api tokens via the appcenter cli.

**Describe the solution you'd like**
The _appcenter tokens create_ should accept a new parameter -s/--scope which accepts either full or viewer.
The _appcenter tokens list_ adds another attribute to the response (json or table) that displays the scope that is defined for the api token.

**Describe alternatives you've considered**
n.a.

**Additional context**
n.a.

**Comment by AnatolyPristensky** [comment]
Hello @michaelhahn-doka and thank you for your request!
Right now these kind of features have lower priority and we have no any ETA.
Let's see how many upvotes this feature will get.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
