### ISSUE TITLE
Bitrise x CodePush: Error code 3

### ISSUE THREAD

**Issue by Alaa-Ben** [microsoft/appcenter-cli#2136]
### **Description**
Hi !
I've been using Bitrise to deploy OTA updates for a while now. And suddenly, it doesn't work  anymore.
I'm getting an error code 3, with no much information.
OTA deployments work though if launched on my local machine
![Capture d’écran 2022-11-09 à 14 52 01](https://user-images.githubusercontent.com/26058727/200848253-d04d6d38-5ee7-4f2c-9bb7-0cdecb7c64fc.png)
I tried --debug for more logs, but nothing suspicious. All HTTP calls have a 200 response. 
For info, latest call before the 403 error:
![Capture d’écran 2022-11-09 à 14 58 09](https://user-images.githubusercontent.com/26058727/200849208-5f8340a7-3ba8-47a5-940a-6340121c173c.png)

### **Repro Steps**
1. Setup a classic bitrise OTA workflow
2. Launch OTA deployment

### **Expected behavior**
OTA  deployment is successful

2. Which version of the App Center CLI are you using?
    - 2.11.0
4. Which OS version did you experience the issue on?
    -  Ubuntu 20.04.1
5. What command line/shell are you using?
    - e.g. Shell 5.8 /bin/zsh
6. What version of Node.js and NPM/Yarn are you using?
    - node v14.19.1, npm 6.14.16

**Comment by aleksandr-dorofeev** [comment]
Hello @Alaa-Ben 
Unfortunately we dont support 3rd party CI systems. If the same task works locally for you, then please contact `Bitrise` for support.
Also, since you mentioned `error code 403`, please make sure the `AppCenter` token you use on `Bitrise` is not expired and it does not belong to a recently left user.

**Comment by Alaa-Ben** [comment]
I thought so but I posted here because that contain api-token that return a 200, which means the token is good.
and the full command is shown on the screenshots, which is basically a releas-react -t -k, nothing shady so i'm out of clues :'(
