### ISSUE TITLE
Add Collaborator to Apps Via CLI

### ISSUE THREAD

**Issue by jconnerly-foreflight** [microsoft/appcenter-cli#2165]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
As an AppCenter manager for my company, I get requests to add developers as collaborators to certain Apps.  I see it is possible to add collaborators via cli to an organization but not to a specific app.  My feature request is to add a way to add users as collaborators to specific apps within an organization

**Describe alternatives you've considered**
N/A

**Additional context**
Something like this:
`appcenter apps update --app team-xxxx/CIConfigTest --add-collaborators "jlebowski@urbanachivers.com" --permission-level "Developer"`

**Comment by AnatolyPristensky** [comment]
Hello @jconnerly-foreflight and thank you for your request!
Right now these kind of features have lower priority and we have no any ETA.
Let's see how many upvotes this feature will get.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
