### ISSUE TITLE
[Question] - How to update an existing release with a new apk file using cli?

### ISSUE THREAD

**Issue by dinbtechit** [microsoft/appcenter-cli#2166]
How to update an existing release with a new apk file using cli?

Say I don't want to create a new release but just want to update Release version 10 with a new apk file. How can I do that?

> Note - I tried using the `-b 0.0.1` and `-n 2`. But it does not work.

![image](https://user-images.githubusercontent.com/17984781/206751168-e87f082e-2510-452f-a996-8059484ae682.png)

My current command

```
appcenter distribute release -f app/android/app/build/outputs/apk/release/app-release.apk -b 0.0.1 -g Collaborators --app [project]/[app name]
```

**Comment by shadyabarada** [comment]
Hi @dinbtechit, there isn't the option to update an APK for an existing release. For your case, It is advisable remove the current and create a new release with your new apk file.
