### ISSUE TITLE
Missing valid authentication token

### ISSUE THREAD

**Issue by yashpanchal-n** [microsoft/appcenter-cli#2182]
Missing valid authentication token. Correlation ID: 72862846237864224237423... error. while login app center using terminal
i'm implementing codepush using appcenter.

**Comment by AnatolyPristensky** [comment]
Hello @yashpanchal-n, could you please share more information about your issue? Logs or more detailed error message will be helpful.

**Comment by DevRedaKhalaf** [comment]
same issue here

**Comment by kinanahirani** [comment]
Make sure that the code which you are getting on the browser is pasted properly in your terminal. You can try by writing instead of copy-paste to check if it's copying or not.
