### ISSUE TITLE
Add detailed logs for `mobileapp.app` zip file upload/release failure

### ISSUE THREAD

**Issue by jayshah123** [microsoft/appcenter-cli#2183]
**Is your feature request related to a problem? Please describe.**
**When I try to upload/release my `.app` file which is zipped, I should get detailed logging on what went wrong and how to fix it**

App compile/Build step:
```
xcodebuild -workspace ios/app_mysheet.xcworkspace -scheme app_mysheet -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build
```

ZIpping process:
```
cd ios/build/Build/Products/Debug-iphonesimulator && zip -r expo_dev_client_mysheet_app.zip 
```

Appcenter cli release command:
```
appcenter distribute release --app MyOrg/MyApp-iOS --build-version 1 --file ios/build/Build/Products/Debug-iphonesimulator/expo_dev_client_mysheet_app.zip --group "Expo Dev Client Simulator" --token tokenValue
```

Logs show following:
```
Release upload failed

Error: Loading release id failed: A problem occured while extracting your app. (Correlation ID: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
```
**Describe the solution you'd like**

**Only After a discussion with support team, I got to know the full reason being:**
```
{\"code\":\"bad_request\",\"message\":\"Error: Missing required params from body: version, build_version, minimum_os_version\"}"},
```

**Describe alternatives you've considered**
Ideally this error message should be shown at the cli usage itself, instead of reaching out to support for the same.
Also docs can be updated on how to achieve this task.

**Additional context**
Trying to release simulator builds for development.

**Comment by DmitriyKirakosyan** [comment]
Hi @jayshah123 , thank you for reporting this issue!

May I ask if the error message `Missing required params from body: version, build_version, minimum_os_version` helped you? Have you fixed the issue?
Have you tried to build and release for a device?

**Comment by jayshah123** [comment]
No adding params to the cli command does not work,

Moreover alternatively I also tried with fastlane plugin [here](https://github.com/microsoft/fastlane-plugin-appcenter#usage):

```
    appcenter_upload(
      api_token: "mytoken",
      owner_name: "OrgName",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: "AppName",
      destinations: 'Group for testing',
      destination_type: 'group',
      version: "my-build-9",
      file: "ios/build/Build/Products/Debug-iphonesimulator/my_app.app",
      notify_testers: false # Set to false if you don't want to notify testers of your new release (default: `false`)
    )

```

Error fetching release: A problem occured while extracting your app. (Correlation ID: 146e1e9f-41ac-414f-9803-5b667ecbfa03)

**Comment by DmitriyKirakosyan** [comment]
Hi @jayshah123 , sorry for the delay. I've just got a confirmation from the backend team, that we don't support distributing simulator builds.

Please try to build for device and let me know if it works for you.
