### ISSUE TITLE
Hermes not working with react native 0.71 on Android

### ISSUE THREAD

**Issue by sontruongna** [microsoft/appcenter-cli#2212]
Command `appcenter codepush ...` working but not show message
> Converting JS bundle to byte code via Hermes ...

- appcenter-cli: 2.31.1
- react-native: 0.71
- react-native-code-push: 7.1.0 with patch [https://github.com/microsoft/react-native-code-push/issues/2418#issuecomment-1426484628](https://github.com/microsoft/react-native-code-push/issues/2418#issuecomment-1426484628)

**Comment by IlyaBausovAkvelon** [comment]
@sontruongna Thank you for reporting this issue. Could you provide more information about this error?
Is it blocking you?

**Comment by sontruongna** [comment]
> @sontruongna Thank you for reporting this issue. Could you provide more information about this error? Is it blocking you?

For previous react native versions, when I run "appcenter codepush ..." command, on my log screen appears the line "Converting JS bundle to byte code via Hermes, running command:". That means hermes worked. When I upgraded to react native version 0.71.2 two problems occurred. First I cannot run android with react-native-code-push@7.1.0.
I have to use patch-package like in the following link [https://github.com/microsoft/react-native-code-push/issues/2418#issuecomment-1426484628](https://github.com/microsoft/react-native-code-push/issues/2418#issuecomment-1426484628). Then I can run on Android. But I found out now that when I run appcenter codepush in command line, on my log screen there is no longer the line "Converting JS bundle to byte code via Hermes". That means the bundle just contains the regular js code. And I've seen performance drop on app startup because this package didn't come with hermes.

**Comment by DmitriyKirakosyan** [comment]
Hi @sontruongna , do you have the property `enableHermes` set to `true` in your `android/app/build.gradle` file? If not, does it exist in any other build.gradle files?

- If your `build.gradle` file is located in different place, try to specify it using `gradleFile` argument for the `codepush` command.
- If it doesn't exist in any of your `build.gradle` files, then try to add the following lines to your `android/app/build.gradle` file:
```gradle
project.ext.react = [
      enableHermes  :   true
]
```

If the suggestions above don't work for you, try to bypass the hermes check by providing the argument `useHermes` for the `codepush` command.

Please let me know if it solves your issue.

**Comment by sontruongna** [comment]
> Hi @sontruongna , do you have the property `enableHermes` set to `true` in your `android/app/build.gradle` file? If not, does it exist in any other build.gradle files?
> 
> * If your `build.gradle` file is located in different place, try to specify it using `gradleFile` argument for the `codepush` command.
> * If it doesn't exist in any of your `build.gradle` files, then try to add the following lines to your `android/app/build.gradle` file:
> 
> ```groovy-gradle
> project.ext.react = [
>       enableHermes  :   true
> ]
> ```
> 
> If the suggestions above don't work for you, try to bypass the hermes check by providing the argument `useHermes` for the `codepush` command.
> 
> Please let me know if it solves your issue.

Thanks you. Hermes worked when I added these lines to `android/app/build.gradle`
```
project.ext.react = [
      enableHermes  :   true
]
```
So I think the problem is in React Native version 0.71.2. This version default has removed the above lines. The way to check on off hermess has changed. There is only one configuration `hermesEnabled=true` in `gradle.properties`. I think appcenter cli will need another way to check on off hermes on android.

**Comment by DmitriyKirakosyan** [comment]
@sontruongna, Thank you for the information! I'll keep this issue open as a feature request.

**Comment by DmitriyKirakosyan** [comment]
We have decided not to implement this feature in the foreseeable future. However, we truly appreciate and welcome your contribution!
