### ISSUE TITLE
Allow downloading .apk instead of .aab from the CLI

### ISSUE THREAD

**Issue by Hegemege** [microsoft/appcenter-cli#2223]
**Is your feature request related to a problem? Please describe.**
Currently, using `appcenter distribute groups download` hardcodes the main download URL (see Additional context below), which for us is the .aab. However, we would need the .apk instead of .aab, while installing our app to test devices automatically. The .apk path is available in the `secondary_download_url` field of the response from `v0.1/apps/{owner_name}/{app_name}/distribution_groups/{distribution_group_name}/releases/{release_id}`

**Describe the solution you'd like**
There should be a command line option to specify using the secondary download URL instead of the primary URL. The secondary URL should be available in `GetLatestByDistributionGroupOKResponse`.

**Describe alternatives you've considered**
We can use buildtool to extract apks from the .aab file, but it adds unnecessary steps and can result in a different .apk file than the one downloaded from AppCenter.

**Additional context**
https://github.com/microsoft/appcenter-cli/blob/5b89015223f09dc86369d0c6c79b199b4f02977c/src/commands/distribute/groups/download.ts#L101

**Comment by DmitriyKirakosyan** [comment]
Hi @Hegemege , thank you for the report. I've created an item on our board. Feel free to contribute if it is critical for you.

**Comment by agudelod** [comment]
Hi @DmitriyKirakosyan Do you have any updates on this issue?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
