### ISSUE TITLE
[feature request] cancelling build

### ISSUE THREAD

**Issue by dodicandra** [microsoft/appcenter-cli#2226]
**Is your feature request related to a problem? Please describe.**
I hope the feature canceling the build is available

**Describe the solution you'd like**
when pushing changes, the build will automatically run, but I hope the build can be aborted soon via the cli

**Describe alternatives you've considered**
I used to try [this alternative](https://github.com/microsoft/appcenter/issues/54#issuecomment-760151939), but now it doesn't seem to work anymore

**Additional context**
[ X ]

**Comment by vvechkanov** [comment]
Hello @dodicandra!
Thank you for the feature request. I will add this request on our internal board. Unfortunately I could not give you any ETA for this.

**Comment by dodicandra** [comment]
Hi @vvechkanov!
thanks for the reply, I hope this feature will be available earlier

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
