### ISSUE TITLE
Codepush release-react Internal Server Error

### ISSUE THREAD

**Issue by svtags** [microsoft/appcenter-cli#2251]
### **Description**
`appcenter codepush release-react -a` 
response status code: 500

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. appcenter codepush release-react -a <project_name> -d Production -t '5.0.0' --debug

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - `appcenter codepush release-react`
2. Which version of the App Center CLI are you using?
    - 2.13.3
3. Which OS version did you experience the issue on?
    - macOS Monterey 12.5
4. What command line/shell are you using?
    - /bin/zsh
5. What version of Node.js and NPM/Yarn are you using?
    - node v14.20.0, yarn 1.22.19
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.

Using appcenter-cli version: 2.13.3
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/_/_/deployments/Production",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.13.3 NodeJS/v14.20.0 darwin/21.6.0",
    "x-api-token": "059aac467630082ab5ab039327c25ee156623074",
    "internal-request-source": "cli",
    "diagnostic-context": "2fb1c4a9-c65b-4309-81bb-a11a64344f61",
    "cli-command-name": "codepush release-react"
  },
  "body": null
}
Response status code: 500
Body: Internal Server Error

**Comment by mrvyldzr** [comment]
+++

**Comment by yunusemreayar** [comment]
Same here...

**Comment by svtags** [comment]
It works now. Thanks!
