### ISSUE TITLE
Release-react command not finding path to Info.plist or project.pbxproj files automatically when app name is capitalized in Azure DevOps pipelines

### ISSUE THREAD

**Issue by danieldunderfelt** [microsoft/appcenter-cli#2252]
### **Description**
The name of our React-native app is capitalized in the ios files, and when running the codepush release-react command in Azure DevOps pipelines, it is looking for the Info.plist and project.pbxproj files in paths where the app name is all lower case.

For example, if the app name is App and the path to the Info.plist is `ios/App/Info.plist`, the command looks for the file in the path `ios/app/Info.plist`.

The command works locally on my macbook, so this problem is only present in the pipeline environment.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Create a react-native app where the name is capitalized
1. Set up a pipeline in Azure Devops that calls the `codepush release-react` command
2. 

### **Expected behavior**
I expect the command to find the required files regardless of the capitalization of the app name. Alternatively, I need an option to set the app name.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - `appcenter codepush release-react`
2. Which version of the App Center CLI are you using?
    - 2.13.0
3. Which OS version did you experience the issue on?
    - Azure Devops Pipelines with vmImage of value `ubuntu-latest`
4. What command line/shell are you using?
    - Azure Devops pipeline shell (probably Bash?)
5. What version of Node.js and NPM/Yarn are you using?
    - Node 18

**Comment by DmitriyKirakosyan** [comment]
Hi @danieldunderfelt , thank you for reaching out!

Have you tried using `xcode-project-file` and `plist-file-prefix` parameters? I think it will be a solution in your case.

**Comment by danieldunderfelt** [comment]
> Hi @danieldunderfelt , thank you for reaching out!
> 
> Have you tried using `xcode-project-file` and `plist-file-prefix` parameters? I think it will be a solution in your case.

Yes, those work. It also works if I set the vmImage to macOS. But I think it should work for ubuntu and without the extra parameters as well since inferring the version is one of the main points of using `release-react`.

**Comment by DmitriyKirakosyan** [comment]
Thank you for the update and I'm glad you are unblocked. Let's keep it as feature request.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
