### ISSUE TITLE
App centre CLI getting stuck

### ISSUE THREAD

**Issue by Azeem00786** [microsoft/appcenter-cli#2254]
Hi Team Microsoft,

Executing the command appcenter login opens up my browser and I can paste in the token.

Then, it stuck at | Getting user info ...
After that i did tried to login with user api token appcenter login --token xxxxxxxx but still facing same issue.

Mac minii m1
Node v18.12.1
appcenter version 2.13.3

Regards,

Azeem.

**Comment by AnatolyPristensky** [comment]
Hello @Azeem00786, I've just checked the functionality of appcenter-cli and found that it's logging in without any issues. Also the [status page ](https://status.appcenter.ms)saying that Account management service is operational.

This issue could be related with your network settings or geographical location.
