### ISSUE TITLE
Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by bgoldfine** [microsoft/appcenter-cli#2259]
### **Description**
Hello, we are running into issues on new MacOS AWS Instances when trying to distribute releases to appcenter via the CLI. 

Our environment is MacOS Monterey 12.6.3
The node version is - v14.21.2
The appcenter-cli version is the latest - 2.13.4

When running the distribute release command for our .ipa, we get a failure with the following reason:
"self signed certificate in certificate chain"

I have checked a few other threads on this issue, and can confirm that there is no firewall running on this instance. What is the root cause of this issue? What options are available for resolution?

**Comment by AnatolyPristensky** [comment]
Hello @bgoldfine,

This issue can happen for various reasons, such as using a corp proxy server that intercepts and decrypts SSL traffic or corp VPN. In this case, one of the certificates in the certificate chain is self-signed, which is generally considered insecure and may cause security issues.

If you are using a corporate proxy server, consult your admin for assistance or information on properly using certificates with the appcenter-cli, or you can temporarily bypass the certificate check by adding the NODE_TLS_REJECT_UNAUTHORIZED=0 before running the cli-command or adding it into the envars. 

Please let me know if you still facing this issue.

**Comment by bgoldfine** [comment]
@AnatolyPristensky

Thank you very much for getting back to me so quickly!

I confirmed with our security team that we are not behind any proxy/firewall/vpn. As a temporary measure, we have disabled the SSL check. Can you please suggest another approach that doesn't involve disabling the SSL check? Do you have a quick way to identify which certificate is causing the issue in appcenter cli?

**Comment by AnatolyPristensky** [comment]
@bgoldfine I suppose that you can use openssl for detecting self-signed certificate:
For example - `openssl s_client -connect [HOST]:[PORT] -showcerts` Replace [HOST] and [PORT] with the appropriate values for the endpoint you are connecting to.

Once you identify the problematic certificate, you can manually add it to your system's certificate store or contact the certificate issuer to resolve the issue.

Actually - this is not issue of appcenter-cli, but your local configuration, so I'm closing this issue.
