### ISSUE TITLE
Add option to add a team to app distribution groups

### ISSUE THREAD

**Issue by ahujamanish** [microsoft/appcenter-cli#2277]
**Is your feature request related to a problem? Please describe.**
Please add an option to specify name/id of a team while updating a distribution group. Right now via CLI, you can only add users via their email addresses, and we're forced to login on web and add the team to app's distribution groups. It would be nice if there is a way we can add a team via CLI. 

**Describe the solution you'd like**
`appcenter distribute groups update --group some_group_name --app owner/app_name --team team_name_to_add`

**Describe alternatives you've considered**

**Additional context**

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
