### ISSUE TITLE
DOCTYPE html PUBLIC

### ISSUE THREAD

**Issue by swlkkk** [microsoft/appcenter-cli#2278]
### **Description**
DOCTYPE html PUBLIC
### **Repro Steps**
1.Run command to push new version code
2.I got an error

### **Expected behavior**
Code update new version successfully

### **Actual Behavior**
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span>0C2w2ZAAAAABeAJ1srDFCQr6a6ce+uTEJVFlPMDFFREdFMjMyMgBmZGMzYmE0Ny0zODk2LTQyNjAtYjFlNC02MDJmM2I2YzQwYmI=</span></div></div></body></html>

### **Details**
I use:
appcenter version 2.13.4
react-native-code-push 7.1.0
"react-native": "0.67.3"

**Comment by dshourek** [comment]
The same here trying to push a new release through the app center cli.
Response status code: 403
Error: failed to set release notes for release
Process exited with code 3

**Comment by MikhailSuendukov** [comment]
As you can see on [status page](https://status.appcenter.ms/) -  AppCenter code push service is experiencing some issues due to overload right now.
Please, check the status page and try again later, once the status page will be green.
