### ISSUE TITLE
appcenter distribute throws exception occasionally

### ISSUE THREAD

**Issue by psstevenchan** [microsoft/appcenter-cli#2316]
### **Description**
appcenter distribute throws exception occasionally start from 2023-05-10

### **Repro Steps**
execute appcenter distribute 

### **Expected behavior**
no exception

### **Details**
distribute release --release-notes-file changelog.txt --group none --app playstudiosasia/MX-IOS-TRUNK --token XXX --file myvegas.ipa --disable-telemetry --output json

{
	"message": "request to https://api.appcenter.ms/v0.1/apps/playstudiosasia/MX-IOS-TRUNK/uploads/releases failed, reason: read ECONNRESET",
	"type": "system",
	"errno": "ECONNRESET",
	"code": "ECONNRESET"
}

appcenter version = v2.13.4
OS = macOSX 12.5.1
shell = sh
node = v15.14.0
npm = 7.24.2

**Comment by MikhailSuendukov** [comment]
Could you please attach the logs of these commands and a simple example of a demo application with such a file that reproduces this error. Also have you tried using the latest version of `appcenter-cli`?

**Comment by psstevenchan** [comment]
`Using appcenter-cli version: 2.13.4
| Loading prerequisites...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/playstudiosasia/MX-IOS-TRUNK/distribution_groups/none/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.13.4 NodeJS/v15.14.0 darwin/21.6.0",
    "x-api-token": "xxx"
  },
  "body": null
}
/ Loading prerequisites...Error from response, message: connect ECONNRESET 13.107.238.39:443
\ Loading prerequisites...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/playstudiosasia/MX-IOS-TRUNK/distribution_groups/none/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.13.4 NodeJS/v15.14.0 darwin/21.6.0",
    "x-api-token": "xxx"
  },
  "body": null
}
| Loading prerequisites...Response status code: 200
Body: []
Command Failure at FetchError: request to https://api.appcenter.ms/v0.1/apps/playstudiosasia/MX-IOS-TRUNK/uploads/releases failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/opt/local/lib/node_modules/appcenter-cli/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:369:20)
    at TLSSocket.socketErrorListener (node:_http_client:472:9)
    at TLSSocket.emit (node:events:369:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Error: Command 'distribute release --release-notes-file /Volumes/External/jenkins/workspace/MX_IOS_Pipeline/Slots/builds/resign/changelog.txt --group none --app playstudiosasia/MX-IOS-TRUNK --token xxx --file /Volumes/External/jenkins/workspace/MX_IOS_Pipeline/Slots/builds/resign/myvegas_65315_TRUNK.ipa --disable-telemetry --debug' failed with exception "request to https://api.appcenter.ms/v0.1/apps/playstudiosasia/MX-IOS-TRUNK/uploads/releases failed, reason: read ECONNRESET"

`

**Comment by AnatolyPristensky** [comment]
Hello @psstevenchan, your log indicates that your local environment having an issues. 
Try to reinstall node or use node 14.16.0. Also this can be related to your network setting - please contact your system administrator. 

I'm closing this issue, but feel free to reopen it in case if my suggestions will not help.
