### ISSUE TITLE
Deprecation of the library request

### ISSUE THREAD

**Issue by andres-diaz10** [microsoft/appcenter-cli#2325]
### **Description**

I tried to solve a dependabot security issue in my project related to the [request](https://www.npmjs.com/package/request?activeTab=readme) library and it seems to be deprecated.

![Screenshot 2023-05-19 at 12 49 50 PM](https://github.com/microsoft/appcenter-cli/assets/98330551/c8bd4c7b-25dc-4144-a06d-cd2c7f1887e2)

When I searched on npm, it informed me that the request library is deprecated.

![Screenshot 2023-05-19 at 12 51 02 PM](https://github.com/microsoft/appcenter-cli/assets/98330551/e210f41f-0f60-4199-9650-74448a1d41be)

I already tried to update the appcenter and the issue is not fixed yet. Are you planning to release a new version addressing this issue?

### **Repro Steps**
Please list the steps used to reproduce your issue.
1.  Use appcenter-cli library in any github project to be scanned by Dependabot.
2. Wait for the vulnerability to come up.

### **Expected behavior**

Dependabot should not raise any alert

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
   - N/A
2. Which version of the App Center CLI are you using?
    - 2.11.0
3. Which OS version did you experience the issue on?
    - macOS Ventura 13.4
4. What command line/shell are you using?
    - Shell /bin/zsh
5. What version of Node.js and NPM/Yarn are you using?
    - node v16.13.1, npm 8.1.1

**Comment by DmitriyKirakosyan** [comment]
Hi @andres-diaz10 , yes we are working on replacing `request`. However, the replacement is not straightforward. There are lots of affected files and additional library depending on it. Unfortunately, I don't have ETA for this change.

Note, the severity of the vulnerability is `Moderate`, so is not a high priority for the project.
Related https://github.com/microsoft/appcenter-cli/issues/761
