### ISSUE TITLE
Getting stuck with "Preparing tests..."

### ISSUE THREAD

**Issue by ryanalford-suzy** [microsoft/appcenter-cli#2334]
### **Description**
I'm attempting to run a Xamarin.UITest suite of tests in AppCenter using the CLI. I believe I have all of the commands correct, but the CLI just gets stuck on "Preparing tests...", and never completes. I've tried both the `prepare` and `run` commands, and both get stuck. In the `prepare`, it does create the artifacts directory, but nothing ever shows up in that directory.

Using `--debug` doesn't show anything except for the version of the npm package.

I am on the latest version as of May 26, 2023, version 2.13.8.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1.
2.

### **Expected behavior**
A test series to show up in AppCenter.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    `appcenter test prepare uitest` and `appcenter test run uitest`
2. Which version of the App Center CLI are you using?
    2.13.8
3. Which OS version did you experience the issue on?
    MacOS 12.6.1 Monterey
4. What command line/shell are you using?
    Just using Terminal
5. What version of Node.js and NPM/Yarn are you using?
    Node - v20.2.0, NPM - 9.6.7
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.
[ui-test-logs.txt](https://github.com/microsoft/appcenter-cli/files/11578529/ui-test-logs.txt)

**Comment by AnatolyPristensky** [comment]
Hello @ryanalford-suzy, I've checked provided logs and found the following: 
Your build directory is: 
`/Users/ryan/code/suzy-native-forms/source/Suzy.Native/Suzy.Native.UITests/`

Your UITest tools dir is:
`/users/ryan/code/ui-tests/tools`

Could you please share an information on what version of XamarinUITest package is used in `Suzy.Native.UITests` project and what version of this package is stored in`/users/ryan/code/ui-tests/tools` directory?

Also, most likely this is not an appceter-cli issue, but rather a test-cloud and the project configuration related problem, so I would recommend you reaching out to our support team as they can help you faster in this case.

**Comment by MikhailSuendukov** [comment]
Okay, then I'll close this issue. If you have any other questions about this topic, you can freely reopen it.
