### ISSUE TITLE
Loading release id failed: A problem occured while extracting your app.

### ISSUE THREAD

**Issue by chandrunmanchur** [microsoft/appcenter-cli#2342]
While publishing the package to AppCenter via Azure pipelines, I see this error.
 (Correlation ID: 8ce7fecc-48ea-4595-937b-894b825d40f7)

I have confirmed uploading the same package manually and it works. Can you please check and confirm what might be the issue.

**Comment by AnatolyPristensky** [comment]
@chandrunmanchur, could you please provide more information? What are you doing exactly and what is your workflow, also it would be useful to describe repro steps for your issue.

**Comment by chandrunmanchur** [comment]
Thank you for the response @AnatolyPristensky. I am using Task AppCenterDistribute@3 in Azure pipelines to publish the build to a specific App. This task throws error as mentioned in the title. App created in AppCenter has OS as Mac. If we change the OS to custom, I do not see any error. For now, I have changed the OS and proceeding.
