### ISSUE TITLE
Use of mvn commands with App Center CLI

### ISSUE THREAD

**Issue by pramodKarande** [microsoft/appcenter-cli#2353]
Hi team,

I have more than 50 test cases in my automation suite and to run specific test methods I use the below sample command
`mvn clean test -Dtest=LoginPageTest#*verifySuccessfulLogin` 
while executing tests on local

How can I achieve the same while executing tests on App Center? where and how should I mention this filter?

I am unsure if we already have support for this feature, hence adding it as a feature request.
If anyone knowns the solution please comment here.
Thanks in advance!!

**Comment by IlyaBausovAkvelon** [comment]
@pramodKarande Hi!
Can you try to put the filter in the runOptions?

**Comment by pramodKarande** [comment]
Hi @IlyaBausovAkvelon 
I am not aware of a filter in the runOptions.
do you have any sample code on how to use that or a link to documentation where I can find more details about this?

**Comment by IlyaBausovAkvelon** [comment]
@pramodKarande Could you please provide more details?
We need to know what testing framework you're using.

**Comment by pramodKarande** [comment]
@IlyaBausovAkvelon 
Hi I am using the Appium test framework

**Comment by pramodKarande** [comment]
@IlyaBausovAkvelon  
any update?

**Comment by IlyaBausovAkvelon** [comment]
@pramodKarande,
https://learn.microsoft.com/en-us/appcenter/test-cloud/frameworks/appium/#3-upload-to-app-center-test

**Comment by pramodKarande** [comment]
@IlyaBausovAkvelon 
I don't see anything here related to grouping the test cases

**Comment by IlyaBausovAkvelon** [comment]
@pramodKarande before uploading test package to Appcenter you're running command
`mvn -DskipTests -P prepare-for-upload package`
Here you can specify the tests filters.

**Comment by pramodKarande** [comment]
@IlyaBausovAkvelon Thank you for updating :)
will try this

**Comment by pramodKarande** [comment]
@IlyaBausovAkvelon 
I tried what you said in the previous command and it is not working
command:  mvn -DskipTests -Dtest=LoginPageTest#*verifySuccessfulLogin -P prepare-for-upload package

let me know if I am doing it correctly or not.

**Comment by IlyaBausovAkvelon** [comment]
@pramodKarande Hi,
Could you please describe what exactly you want to do?

**Comment by IlyaBausovAkvelon** [comment]
Also could you please share what output did you get with running of the suggested command?

**Comment by pramodKarande** [comment]
@IlyaBausovAkvelon , what was your understanding of the problem statement while suggesting the above solutions?

**Comment by pramodKarande** [comment]
let me simplify it for you.
Refer to the below hierarchy of  test classes and test methods

TestClassA
      TestMethodA1
      TestMethodA2
      TestMethodA3
TestClassB
      TestMethodB1
      TestMethodB2
      TestMethodB3
TestClassC
      TestMethodC1
      
Here, whenever I prepare and run test cases on the app center it executes all test methods.
But, I want to execute only a few test methods instead of all, like sometimes I want to execute TestMethodA1, TestMethodC1 or sometimes  TestMethodA1, TestMethodA2, TestMethodC1.
How can I achieve this while executing test on App Center?

**Comment by IlyaBausovAkvelon** [comment]
@pramodKarande I apologize for long reply.
I've investigated the appcenter-cli tool and I've found out that it's not possible to filter tests for Android Espresso.

We will add it as feature request.

**Comment by pramodKarande** [comment]
@IlyaBausovAkvelon 
np 
and Thanks for your continuous support.

**Comment by vpuonti** [comment]
+1 this needs to be fixed. 
Is there any timeline for this? We started transitioning to AppCenter for running Espresso tests but the lack of test filtering makes us doubt our choices. 
We should be able to pass `android.testInstrumentationRunnerArguments` to the runner.

**Comment by lucen-ms** [comment]
As we do not have plans to add support for this feature in the next year, I close the issue.
