### ISSUE TITLE
Test results take long time to come back

### ISSUE THREAD

**Issue by Hackmodford** [microsoft/appcenter-cli#2354]
### **Description**
When using the CLI it takes a long time for the test results to come back.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Use the CLI to run a UI test
2. See that it finishes in appcenter.ms but CLI tool acts as if it's still running

### **Expected behavior**
CLI should report results in a timely fashion

**Comment by MikhailSuendukov** [comment]
Hi @Hackmodford and thank you for reporting this issue. To help us better understand and diagnose the issue, could you please provide the following additional information?

- Could you please tell us which version of the App Center CLI you are currently using?
- Could you provide more details about the UI test that you're running? This includes the type of test (e.g., unit test, integration test), the test framework used, and any other details that might help us understand the context of the test.
- How often does this issue occur? Is it happening every time you run a test, or is it intermittent?
- If there are any logs or error messages displayed in the CLI when the issue occurs, could you please share them with us? This could offer valuable clues about what's going wrong.
- Could you describe your network conditions when running the tests? Are you on a slow or unreliable network that might be causing delays?

**Comment by AnatolyPristensky** [comment]
@Hackmodford, we haven't heard from you for a while, so I'm closing this issue. 
Please, feel free to reopen it in case of new information.
