### ISSUE TITLE
Could not determine the dependencies of task ':app:lintvitalrelease'. > appcenter

### ISSUE THREAD

**Issue by v-tonguyen** [microsoft/appcenter-cli#2358]
### **Description**
Could not determine the dependencies of task ':app:lintvitalrelease'. > appcenter

### **Error**
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.fresco:fresco:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.54.0
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.54.0 > com.facebook.fresco:flipper:2.2.0
   > Could not find com.facebook.fresco:stetho:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/stetho/2.2.0/stetho-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/stetho/2.2.0/stetho-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/stetho/2.2.0/stetho-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/stetho/2.2.0/stetho-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/stetho/2.2.0/stetho-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/stetho/2.2.0/stetho-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/stetho/2.2.0/stetho-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/stetho/2.2.0/stetho-2.2.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.54.0
   > Could not find com.facebook.fresco:imagepipeline:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.54.0 > com.facebook.fresco:flipper:2.2.0
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.54.0 > com.facebook.fresco:flipper:2.2.0 > com.facebook.fresco:memory-type-ashmem:2.2.0
   > Could not find com.facebook.fresco:imagepipeline-native:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/imagepipeline-native/2.2.0/imagepipeline-native-2.2.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.54.0 > com.facebook.fresco:flipper:2.2.0
   > Could not find com.facebook.fresco:memory-type-native:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/memory-type-native/2.2.0/memory-type-native-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/memory-type-native/2.2.0/memory-type-native-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/memory-type-native/2.2.0/memory-type-native-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/memory-type-native/2.2.0/memory-type-native-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/memory-type-native/2.2.0/memory-type-native-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/memory-type-native/2.2.0/memory-type-native-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/memory-type-native/2.2.0/memory-type-native-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/memory-type-native/2.2.0/memory-type-native-2.2.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.54.0 > com.facebook.fresco:flipper:2.2.0
   > Could not find com.facebook.fresco:memory-type-java:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/memory-type-java/2.2.0/memory-type-java-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/memory-type-java/2.2.0/memory-type-java-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/memory-type-java/2.2.0/memory-type-java-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/memory-type-java/2.2.0/memory-type-java-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/memory-type-java/2.2.0/memory-type-java-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/memory-type-java/2.2.0/memory-type-java-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/memory-type-java/2.2.0/memory-type-java-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/memory-type-java/2.2.0/memory-type-java-2.2.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.54.0 > com.facebook.fresco:flipper:2.2.0
   > Could not find com.facebook.fresco:fresco:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/fresco/2.2.0/fresco-2.2.0.pom
     Required by:
         project :app > project :react-native-vector-icons > com.facebook.react:react-native:0.64.4
   > Could not find com.facebook.fresco:fbcore:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.54.0 > com.facebook.fresco:flipper:2.2.0 > com.facebook.fresco:memory-type-ashmem:2.2.0
   > Could not find com.facebook.fresco:fbcore:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/fbcore/2.2.0/fbcore-2.2.0.pom
     Required by:
         project :app > project :react-native-vector-icons > com.facebook.react:react-native:0.64.4 > com.facebook.fresco:imagepipeline-okhttp3:2.0.0
   > Could not find com.facebook.fresco:imagepipeline:2.2.0.
     Searched in the following locations:
       - file:/Users/runner/.m2/repository/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - https://maven.google.com/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - https://www.jitpack.io/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
       - file:/Users/runner/work/1/s/node_modules/@notifee/react-native/android/libs/com/facebook/fresco/imagepipeline/2.2.0/imagepipeline-2.2.0.pom
     Required by:
         project :app > project :react-native-vector-icons > com.facebook.react:react-native:0.64.4 > com.facebook.fresco:imagepipeline-okhttp3:2.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.2/***guide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 56s
Error: /Users/runner/work/1/s/android/gradlew failed with return code: 1
    at ChildProcess.<anonymous> (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/1.128.0/node_modules/vsts-task-lib/toolrunner.js:569:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
##[error]Error: /Users/runner/work/1/s/android/gradlew failed with return code: 1

**Comment by MikhailSuendukov** [comment]
Hi @v-tonguyen and thanks for reaching us. Based on the error message you've shared, it seems like the issue is related to the Gradle build configuration of your Android project. Please make sure you set up your Gradle dependencies correctly, or try to reproduce the bug on a new base project. If that doesn't help, we need the following information to further investigate your error:

- Steps for reproducing this error
- Which version of the App Center CLI are you using?
- Which OS version did you experience the issue on?
- What command line/shell are you using?
- What version of Node.js and NPM/Yarn are you using?
- What version of Gradle are you using?

**Comment by v-tonguyen** [comment]
Looks like the error is caused by the app center failing to load Gradle. I built it successfully this morning and didn't edit anything
