### ISSUE TITLE
VM2 discontinuity, replace library

### ISSUE THREAD

**Issue by cchampou** [microsoft/appcenter-cli#2375]
**Is your feature request related to a problem? Please describe.**
2 key contributors of this library explain [in an issue](https://github.com/patriksimek/vm2/issues/533), that despite their efforts, they won't be able to fix the critical vulnerabilities affecting the lib. That's why they choose to discontinue it, and mark it as deprecated.

**Describe the solution you'd like**
In this same issue they suggest to migrate to [isolated-vm](https://www.npmjs.com/package/isolated-vm) which is allegedly serving the same purpose. Do you think considering migrating to this library is a good option ?

**Describe alternatives you've considered**
We may just find another package.

**Additional context**
In case you, as I do, consider migrating is pretty necessary, we may work together to do this migration.

**Comment by cchampou** [comment]
Obviously we can also work with `proxy-agent` to solve this issue at a higher level. Check this conversation:
https://github.com/TooTallNate/proxy-agents/issues/218

**Comment by AnatolyPristensky** [comment]
Hello @cchampou, thank you for the information. We've filed an item on our internal dashboard.
Will update this ticket once issue is fixed.

**Comment by blumk** [comment]
Latest `proxy-agent` removed the dependency on vm2.

Manually patching the `package.json` file with solved the issue.

```
  "overrides": {
    "appcenter-cli": {
      "proxy-agent": {
        ".": "6.3.0"
      }
    }
  },
  ```
  
  https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by AnatolyPristensky** [comment]
This issue has been resolved in latest appcenter-cli release. Closing.
