### ISSUE TITLE
Required Version is Node >= 14 in v2.13.10

### ISSUE THREAD

**Issue by ebachle** [microsoft/appcenter-cli#2397]
### **Description**
With the version release of v2.13.10, the minimum version of node appears to have changed to no longer support Node12.  There are related changes that I can see in the `package-lock.json` that reflect this.  However, the package.json wasn't updated here: https://github.com/microsoft/appcenter-cli/blob/master/package.json#L12.

### **Repro Steps**
Please list the steps used to reproduce your issue.

Failure case:

```
$ nvm use 12
Now using node v12.18.3 (npm v6.14.6)
```

```
$ appcenter distribute release --debug --app android-redacted.com/Master-Builds --file app/build/outputs/apk/debug/app-debug.apk --group All-users-of-Master-Builds --release-notes "From Branch master - Merge pull request #6329 from redacted/SEL-10289-rewrite-gtin-popup"
Error: Command distribute release --debug --app android-redacted.com/Master-Builds --file app/build/outputs/apk/debug/app-debug.apk --group All-users-of-Master-Builds --release-notes From Branch master - Merge pull request is invalid
```

Success case:
```
$ nvm use 20
Now using node v20.5.0 (npm v9.8.0)
```

```
$ appcenter distribute release --debug --app android-redacted.com/Master-Builds --file app/build/outputs/apk/debug/app-debug.apk --group All-users-of-Master-Builds --release-notes "From Branch master - Merge pull request #6329 from redacted/SEL-10289-rewrite-gtin-popup"

<<something actually happens>>
```

### **Expected behavior**
A more clear error that the package requires a higher version of NodeJS.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - `appcenter distribute release`.  Not sure if others are affected or not.
2. Which version of the App Center CLI are you using?
    - v2.13.10
4. Which OS version did you experience the issue on?
    - MacOS
5. What command line/shell are you using?
    - fish and bash both fail.
6. What version of Node.js and NPM/Yarn are you using?
    - Failure node is in node v12
7. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.
  - Included above

**Comment by AnatolyPristensky** [comment]
Hello @ebachle,
Thank you for pointing to it. I've tested this behaviour and confirm the issue. 
An item has been filed on our internal dashboard, will update this thread once it fixed.

**Comment by AnatolyPristensky** [comment]
This issue has been fixed in the latest appcenter-cli version. Closing.
