### ISSUE TITLE
RN Build - The asset cannot be uploaded

### ISSUE THREAD

**Issue by losheredos** [microsoft/appcenter-cli#2411]
### **Description**
Error: Error: The asset cannot be uploaded. Try creating a new one

### **Repro Steps**
I just try to make a new build from 
1.  appcenter codepush release-react -a losheredos/aea-ios -d Staging
2. appcenter codepush release-react -a losheredos/aea-android -d Staging
Both ways same issue.

### **Expected behavior**
I used the same way like few hours ago and all was ok. So maybe its about the servers of Microsoft? I'm not sure.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    No
2. Which version of the App Center CLI are you using?
    2.13.10
4. Which OS version did you experience the issue on?
    macOS Venture 13.1
5. What command line/shell are you using?
    - e.g. Shell 5.8 /bin/zsh
6. What version of Node.js and NPM/Yarn are you using?
    node v14.17.5, npm 9.8.1
7. Logs(last parts)

appcenter-cli:commands:codepush:release-base } +744ms
  appcenter-cli:commands:codepush:release-base Upload client message: Setting state: New (0) +6ms
  appcenter-cli:commands:codepush:release-base Upload client message: Upload Initialized +1ms
  appcenter-cli:commands:codepush:release-base Upload client message: Setting metadata for AssetId:  30561e91-0b99-4afa-85c8-76c342f65661 +1ms
  appcenter-cli:commands:codepush:release-base Upload client message: File name: JXrkNBCrq4bmRDf.zip +0ms
  appcenter-cli:commands:codepush:release-base Upload client message: File size: 8900838 +0ms
  appcenter-cli:commands:codepush:release-base Upload client message: CorrelationId: 30561e91-0b99-4afa-85c8-76c342f65661 +0ms
  appcenter-cli:commands:codepush:release-base Upload client message: ContentType: undefined +0ms
  appcenter-cli:commands:codepush:release-base Upload client message: Setting asset metadata on server +0ms
  appcenter-cli:commands:codepush:release-base Upload client message: Set metadata failed: AssetId: 30561e91-0b99-4afa-85c8-76c342f65661, StatusCode: none, errorMessage: undefined +510ms
  appcenter-cli:commands:codepush:release-base Upload client message: Setting state: FatalError (500) +1ms
  appcenter-cli:commands:codepush:release-base Failed to release a CodePush update - Error: The asset cannot be uploaded. Try creating a new one
  appcenter-cli:commands:codepush:release-base     at fileUploadError (/opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/core/file-upload-error.js:5:17)
  appcenter-cli:commands:codepush:release-base     at FileUploadClient.onMessage (/opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/index.js:136:71)
  appcenter-cli:commands:codepush:release-base     at SingleThreadUploadController.FileUploadController.fatalError (/opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/core/controller.js:75:29)
  appcenter-cli:commands:codepush:release-base     at Object.onError (/opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/core/controller-requests/metadata.js:41:34)
  appcenter-cli:commands:codepush:release-base     at /opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/core/request.js:40:32
  appcenter-cli:commands:codepush:release-base     at runMicrotasks (<anonymous>)
  appcenter-cli:commands:codepush:release-base     at processTicksAndRejections (internal/process/task_queues.js:95:5) +2ms
Error: Error: The asset cannot be uploaded. Try creating a new one
zsh: command not found: Detecting

**Comment by furkananter** [comment]
Yes, I have the same issue ++

**Comment by AnatolyPristensky** [comment]
Hello @losheredos, 
according https://status.appcenter.ms/ - all issues have been resolved. Could you please double check it and confirm that issue is gone?

**Comment by AnatolyPristensky** [comment]
Closing issue for now. Please, feel free to reopen it in case of new repro.
