### ISSUE TITLE
Commands appcenter distribute stores publish AND distribute release IS Invalid 

### ISSUE THREAD

**Issue by RafaelWeiss** [microsoft/appcenter-cli#2424]
### **Description**
During the past month, the commands below stopped working in my Pipeline. I've tried using a different version of the appcenter-cli, but the commands still don't work.

Does anyone know what happened and why these commands are invalid? Is there an alternative solution?

- appcenter distribute release --app MyApp/MyApp-PRD --file ./app-release.aab --group "Collaborators"
AND 
- appcenter distribute stores publish --file ./app.ipa --store "App Store Connect Users" --app MyApp/MyApp-PRD-1 --release-notes-file ./releaseNotes.txt

Error: Command distribute release --app MyApp/MyApp-PRD --file ./app-release.aab --group Collaborators is invalid

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. appcenter distribute release --app MyApp/MyApp-PRD --file ./app-release.aab --group "Collaborators"
OR
2. appcenter distribute stores publish --file ./app.ipa --store "App Store Connect Users" --app MyApp/MyApp-PRD-1 --release-notes-file ./releaseNotes.txt

**Comment by RafaelWeiss** [comment]
I discovered that the latest update of the package "appcenter-file-upload-client-node@1.2.11" three weeks ago caused this error.

Since the dependency of "appcenter-file-upload-client-node" within "appcenter-cli" is set to auto-increment, simply downloading a different version of "app-center-cli" didn't resolve the issue. I needed to manually force the downgrade of the "appcenter-file-upload-client-node" version to 1.2.10 directly in the folder where the "appcenter-cli" package was installed:

Example:

npm install -g appcenter-cli
cd /usr/local/lib/node_modules/appcenter-cli
npm install appcenter-file-upload-client-node@1.2.10

I hope this helps, and I believe an update to both appcenter-cli and appcenter-file-upload-client-node to version 1.2.12 should be done to prevent this issue from occurring in the future.

**Comment by AnatolyPristensky** [comment]
Hello @RafaelWeiss, could you please tell, what version of Node you are using on your pipeline?

**Comment by RafaelWeiss** [comment]
Helo @AnatolyPristensky 

I tested it on version 16.13.1.

When encountering the issue, the "appcenter distribute -h" help command is displayed as follows:

- appcenter distribute -h
```
Send builds to testers and manage distribution groups
Version 2.14.0

Usage: appcenter distribute <command>

Commands:
groups Commands for manipulating distribution groups
releases Commands for manipulating releases for your application
stores Commands to distribute to stores (App Store, Google Play, Intune)
release Unable to load
C:\Users\PC\AppData\Roaming\npm\node_modules\appcenter-cli\dist\commands\distribute\release.…
to read help"
```
The "release" subcommand fails to load due to some changes in the "appcenter-file-upload-client-node" library.

Do you think this could be related to the Node version? What would be the minimum required version?

Thanks!

**Comment by AnatolyPristensky** [comment]
@RafaelWeiss I've tested your behaviour and didn't face any issues. Here is my log:


appcenter distribute release --app XXX/test-aab-release --file XXX/sample.aab  --group "Collaborators" result:
```

Release 1.0 (1) was successfully released to 1 testers in Collaborators
```

appcenter distribute -h result:

```
Send builds to testers and manage distribution groups
Version 2.14.0

Usage: appcenter distribute <command>

Commands:
    groups               Commands for manipulating distribution groups                                                                    
    releases             Commands for manipulating releases for your application                                                          
    stores               Commands to distribute to stores (App Store, Google Play, Intune)                                                
    release              Upload release binary and trigger distribution, at least one of --store or --group must be specified 
```

Tested on Node versions 14.15.0 and 16.3.1 - both with the same result - no any issues.
I suppose that something goes wrong with your local environment.

**Comment by RafaelWeiss** [comment]
@AnatolyPristensky thank you for the verification. In my pipeline, it was running on node version 12, and that's why the issue was occurring. As for my local machine, I still don't understand how I managed to reproduce the error using version 16, but I want to believe it's some sort of cache. Anyway, thanks again for your help!
