### ISSUE TITLE
[QUESTION] CodePush compatibility with Expo managed workflow

### ISSUE THREAD

**Issue by mgscreativa** [microsoft/appcenter-cli#2425]
Hi! ¿is it possible to tell `appcenter codepush release-react` that it should add/include an specific file in the release?

I mean, Expo managed workflow apps creates a file called app.config, it contains custom app config setup by the developer, I think I can tell expo to create that file but I don't know how to tell expo that it should include that file among the assets and teh JS bundle file.

Thanks!

**Comment by DmitriyKirakosyan** [comment]
Hi @mgscreativa , thank you for reaching out!
Unfortunately there is no direct support of this scenario.
However, you can try a couple of options:
- Move the app.config to js code location manually so release-react command will pack it within the js bundle.
- Pack the bundle manually and run command `appcenter codepush release` instead, specifying the bundle location. Example:
```sh
appcenter codepush release --update-contents-path "./bundle" --target-binary-version "1.0"
```

I'm closing this but feel free to ask any additional questions.

**Comment by mgscreativa** [comment]
Hi @DmitriyKirakosyan ! I've done that, moved some updateable config settings to a js file, and left the rest not updateable config settings in the app.config file.

Thanks a lot!
