### ISSUE TITLE
Unable to Download Entire "build" Folder for Android and iOS Apps Using AppCenter CLI

### ISSUE THREAD

**Issue by rafageist** [microsoft/appcenter-cli#2433]
**Is your feature request related to a problem? Please describe.**

I am unable to download the entire "build" folder using the AppCenter CLI compared to the download that occurs from the web interface. Only the APK file is downloaded, and not the rest of the files and folders within the "build" folder.

**Describe the solution you'd like**

I would like to be able to use the AppCenter CLI to download the entire "build" folder, including all the files generated after a post-build script, similar to how I can download the entire "build" folder from the web interface.

**Describe alternatives you've considered**

I have considered exploring options within the AppCenter CLI documentation to see if there are any parameters or commands that allow the complete download of the "build" folder. I have also tried searching forums and online communities for solutions, but so far, I haven't found any working solution.

**Additional context**

```
$ appcenter build download -a "Organization/AppName" -t build
```

**Comment by MikhailSuendukov** [comment]
Hi @rafageist  and thanks for reaching out to us. Could you please tell us how you managed to solve this?

**Comment by MikhailSuendukov** [comment]
Could you please attempt using the -t bundle option and also specify the build ID with the --id parameter?

**Comment by DmitriyKirakosyan** [comment]
Closed due to inactivity. Please feel free to reopen if you continue to experience the issue.
