### ISSUE TITLE
Add support for downloading the test report for other test frameworks than Appium and uitest

### ISSUE THREAD

**Issue by JussiPekonen** [microsoft/appcenter-cli#2440]
Currently the tool allows one to download the test reports when the test framework is either Appium or uitest. This makes it impossible to publish the report when the test run is triggered from an external system like CI.

The test reports for Appium and uitest can be downloaded to the triggering system using either the `--test-output-dir` option for the `test run` command or using the `test download` command. It would be beneficial if both of these options would work also for all the other test frameworks.

**Comment by DmitriyKirakosyan** [comment]
Hi @JussiPekonen,

Thanks for getting in touch! Could you provide more details about your request? It would be helpful if you could share a real-life example. Please specify the test framework you'd like to use, the process for uploading to App Center, and your preferred method for downloading it. Your clarification will assist us in better understanding your needs.

**Comment by JussiPekonen** [comment]
Hi,

In principle the setup I would like to have is that there is a CI job (GitHub Actions, Azure Pipelines, GitLab CI, CircleCI, Jenkins, pick your poison) that would trigger a test run on AppCenter. These CI systems have the capability to report the test run results in the job results, making it "easy" to see what is possibly wrong with the tests when the CI system notifies one for the failed job. Now one must visit AppCenter to actually see the test results.

Now, if the test are using anything else than Appium or uitest such as Espresso (native Android) or XCUITest (native iOS), there is no option to get the test results in a format that the CI system supports (such as jUnit test result XML output). What I would like to have in the CLI tool to have an option to get the test results downloaded to the triggering system if one wants to get the test results from the test run. This could be achieved by having the `--test-output-dir` option to define a job to where the test outputs are written.

Furthermore, when one has a mix of tests that are run both on the CI host (such as unit tests) and on AppCenter, there is no possibility to see the aggregated test results from all tests. With this option one could get the AppCenter test results to the CI host and the aggregated test results would be available on the CI host.

**Comment by DmitriyKirakosyan** [comment]
@JussiPekonen , We support downloading test results for all the supported test frameworks.

Do I understand correctly that you were able to successfully run your uitests on App Center, and couldn't download the test report? To assist you better, could you provide additional information? Specifically, what test framework was used, the command you used to start the test run and the command you used trying to download the report.

Regarding the task of aggregating test results gathered from both your CI system and App Center, this process would require creating a consolidated report manually. You'll need to convert the test report formats from both sources into a unified format to achieve this.

**Comment by JussiPekonen** [comment]
Okay, so is this then a documentation issue? Because according to the `test download` command help this would be available only for UITest and Appium:
```
$ appcenter help test download

Download the report artifacts, unpack and merge them. This command is only available for UITest and Appium test runs.
```

I can of course test this myself with the Espresso/XCUITest runs I have done, but if it is indeed documentation issue, then the documentation should be updated accordingly.

**Comment by JussiPekonen** [comment]
Did a quick test with the download command using an old Espresso test run and it failed with the following error (fetched using `--output json` for more verbose output):
```json
{"succeeded":false,"errorCode":3,"errorMessage":"XML reports have not been created"}
```

The command did return the overall status of the run just fine, the message rows match what the test run report on AppCenter says.

**Comment by JussiPekonen** [comment]
Any updates on this? According to the `test run` documentation there is way to define that the test report XMLs would be generated for Espresso or XCUITest frameworks.

**Comment by DmitriyKirakosyan** [comment]
@JussiPekonen , I'm sorry for the confusion. We only support xml reports for uitest and appium. There is only status report for others, as you already figured out.

**Comment by lucen-ms** [comment]
@JussiPekonen we do not have plans to add support for more report types in the next year, so I'm closing this issue.

**Comment by JussiPekonen** [comment]
Thanks. Knowing that it is in the plans is enough for us. Do you have a preliminary schedule for that update? Just asking, so that we know when to expect it to be available.

**Comment by lucen-ms** [comment]
We have no plans.
