### ISSUE TITLE
[breakingchange] --sourcemap-output arguments broken

### ISSUE THREAD

**Issue by kopax-polyconseil** [microsoft/appcenter-cli#2462]
### **Description**

We use to have our react native code push android/ios configured with sentry without issue since july 17th.

It seems that the command  `appcenter codepush release-react` stopped to generate sourcemaps properly.

`--sourcemap-output` was used before but without any params, as a true/false flip, in order to generated source map.

![image](https://github.com/microsoft/appcenter-cli/assets/77674046/bec5aa4b-ea65-44c7-9e90-015905074ee6)

Source : https://learn.microsoft.com/en-us/appcenter/distribution/codepush/cli

Problem : the parameter seems now to expect a parameter and does not work as expected, if I pass a value, such as `--sourcemap-output ./build/CodePush/index.android.bundle.map`, it will fail with the following error (with `DEBUG="appcenter-cli:*"`) : 

```ruby
$ DEBUG="appcenter-cli:*" yarn appcenter codepush release-react --token $ANDROID_APPCENTER_API_TOKEN --deployment-name Production --app pass-Culture/passculture-prod-android --target-binary-version "1.256.0" --description "(PC-24621) fix(useSearchVenueOffers): fix sentry error (#5353)" --disable-duplicate-release-error --sourcemap-output --output-dir ./build --sourcemap-output ./build/CodePush/index.android.bundle.map

Running "react-native bundle" command:

node node_modules/.bin/react-native bundle --assets-dest build/CodePush --bundle-output build/CodePush/index.android.bundle --dev false --entry-file index.js --platform android --sourcemap-output ,./build/CodePush/index.android.bundle.map
warn Package react-native-appsflyer contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-flipper contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
Mapping the following sym linked packages:
{}
Welcome to Metro v0.72.4
              Fast - Scalable - Integrated
info Writing bundle output to:, build/CodePush/index.android.bundle
info Writing sourcemap output to:, ,./build/CodePush/index.android.bundle.map
error ENOENT: no such file or directory, open ',./build/CodePush/index.android.bundle.map'.
Error: ENOENT: no such file or directory, open ',./build/CodePush/index.android.bundle.map'
info Run CLI with --verbose flag for more details.
  appcenter-cli:commands:codepush:release-react Failed to release a CodePush update - Error: "react-native bundle" command failed (exitCode=1, signal=null).
  appcenter-cli:commands:codepush:release-react     at ChildProcess.<anonymous> (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/appcenter-cli/dist/commands/codepush/lib/react-native-utils.js:269:24)
  appcenter-cli:commands:codepush:release-react     at ChildProcess.emit (node:events:513:28)
  appcenter-cli:commands:codepush:release-react     at maybeClose (node:internal/child_process:1091:16)
  appcenter-cli:commands:codepush:release-react     at ChildProcess._handle.onexit (node:internal/child_process:302:5) +0ms
Error: Failed to release a CodePush update.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command

```

I have found by reading appcenter-cli source code that it can work using `--sourcemap-output-dir` instead, to generate the source map

### **Repro Steps**

This used to generate source map using  `--sourcemap-output` without value:

```ruby
git clone git@github.com:pass-culture/pass-culture-app-native.git
cd pass-culture-app-native
git checkout hotfix-production-v1.256.0-1
yarn appcenter codepush release-react --token $ANDROID_APPCENTER_API_TOKEN --deployment-name Production --app pass-Culture/passculture-prod-android --target-binary-version "1.256.0" --description "(PC-24621) fix(useSearchVenueOffers): fix sentry error (#5353)" --disable-duplicate-release-error --sourcemap-output --output-dir ./build
npx sentry-cli react-native appcenter pass-Culture/passculture-prod-android android ./build/CodePush   --deployment Production  --dist 10256000-android   --release-name  1.256.0-android+codepush:v76
```

Adding `--sourcemap-output ./build/CodePush` fail 

### **Expected behavior**

We expect `--sourcemap-output` to not break

### **Details**

1. Is there a particular beacon/command that you are having trouble with?
    - e.g. `appcenter codepush release-react`
3. Which version of the App Center CLI are you using?
    - 2.14.0
4. Which OS version did you experience the issue on?
    - Linux debian 5.8.0-0.bpo.2-amd64
5. What command line/shell are you using?
    - bash 5.1.4
6. What version of Node.js and NPM/Yarn are you using?
    - v18.7.0 / yarn 1.22.15

**Comment by kopax-polyconseil** [comment]
Working with `--sourcemap-output-dir` instead doesn't generate this issue, ie: `--sourcemap-output-dir build/CodePush`

**Comment by DmitriyKirakosyan** [comment]
@kopax-polyconseil , sorry for the confusion with `,` character. It was not your typo actually, but it is how `appcenter-cli` works. You specified the argument `--sourcemap-output` twice, so it thought it is an array :)

**Comment by kopax-polyconseil** [comment]
No I didn't, and it used to work, the only way arround we found was to use `--sourcemap-output-dir`. It use to work well with `--sourcemap-output`, this is a regression and the issue was due to the wrapping done here. I had no time to dig further, but I suggest you consider to reopen this :)

**Comment by DmitriyKirakosyan** [comment]
@kopax-polyconseil The reason it worked for you is that the --sourcemap-output option was effectively bypassed due to the lack of a specified value. Despite this, the sourcemap was still generated because of the presence of the --output-dir option. This, however, is not the intended behavior of these commands. To correctly generate the sourcemap, you should either use the --sourcemap-output-dir option or provide a specific path for the --sourcemap-output.
