### ISSUE TITLE
Which signature is used by AppCenter Distribute for AAB distributed to Groups?

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter-cli#2468]
Hi,

Could you please clarify the following?

At https://learn.microsoft.com/en-us/appcenter/distribution/uploading#android

It says

<img width="888" alt="Screenshot 2023-12-08 at 16 52 25" src="https://github.com/microsoft/appcenter-cli/assets/1186282/c1f1aa7e-6ca3-46aa-939d-fe8c49e2844c">

➡️ 
> When you distribute Android Application Bundle (AAB), App Center generates a universal APK, signs it with a generated signing key, and distributes it to a device.

It's not clear to me which signing key is used.

If I am already distributing APKs signed with my own key, and switch to AAB, won't there be a signing key incompatibility if I am not controlling the signature to generate the APKs from the AAB file?

Thank you

**Comment by DmitriyKirakosyan** [comment]
@fabiendem, thanks for getting in touch!

This query doesn't pertain to appcenter cli, so I recommend contacting our support team for assistance. They will be able to help you shortly.

**Comment by fabiendem** [comment]
Hey, indeed my bad.
Answers from Support are sometimes a bit too simplistic and follow the script, so I wanted to reach out to the devs.
I'm happy to close this, though. I understand.
Let me know if https://github.com/microsoft/appcenter-sdk-android is worth a try, I don't intend to spam.

**Comment by DmitriyKirakosyan** [comment]
@fabiendem , thank you for understanding! There's no need to duplicate your post in the SDK repo 🙂 I already reached out to the appropriate dev team, and will get back to you in this thread if there is any valuable information!

**Comment by DmitriyKirakosyan** [comment]
@fabiendem , I discussed it with the team. All I can share is that we are using `apksigner` on our end. Hope it helps.
If it doesn't, please reach out to the support team and they we help with any issues you are facing with apk/aab signing.

**Comment by fabiendem** [comment]
OK cheers
