### ISSUE TITLE
The `punycode` module is deprecated in Node.js v21.x

### ISSUE THREAD

**Issue by aliaksandr-s-customgamesstudio-com** [microsoft/appcenter-cli#2470]
### **Description**
When run any command with **--output json** the warning message is appear:
> [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
and json becomes invalid.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. appcenter tokens list --output json
2. any appcenter command with **--output json**

### **Expected behavior**
Valid json output.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - e.g. `appcenter tokens list --output json`
3. Which version of the App Center CLI are you using?
    - e.g. 2.14.0
4. Which OS version did you experience the issue on?
    - e.g. Ubuntu 22.04.3 LTS
5. What command line/shell are you using?
    - e.g. Shell 5.8 /bin/bash
6. What version of Node.js and NPM/Yarn are you using?
    - e.g. node v21.5.0, npm 10.2.4

Moreover, there are a lot of warns when the appcenter is installing:

> npm install --location=global appcenter-cli
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated superagent@5.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
changed 489 packages in 8s
87 packages are looking for funding
  run `npm fund` for details

**Comment by MikhailSuendukov** [comment]
Hello and thank you for reaching out to us. Does this warning appear when using the latest version of `appcenter-cli`?

**Comment by aliaksandr-s-customgamesstudio-com** [comment]
Yes. Also, it appeares in the latest version to:

> appcenter --version
appcenter version 2.14.0
(node:74424) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by MikhailSuendukov** [comment]
It appears the issue originates externally, rather than from our end. You can monitor this issue in this [thread](https://github.com/yarnpkg/yarn/issues/9013).

**Comment by aliaksandr-s-customgamesstudio-com** [comment]
> It appears the issue originates externally, rather than from our end. You can monitor this issue in this [thread](https://github.com/yarnpkg/yarn/issues/9013).

I don't use `yarn`. So, the link you are presenting is not valid for me.

The appcenter-cli has the dependence to `punnycode` 
https://github.com/microsoft/appcenter-cli/blob/master/appcenter-file-upload-client-node/package-lock.json#L2311
So, the warning appears when I run the appcenter-cli.

**Comment by NPSconsultingLLC** [comment]
I am also having the issue that @aliaksandr-s-customgamesstudio-com  is reporting, and I also do not use YARN, this is a dependency of AppCenter CLI that is apparently depricated.

**Comment by MikhailSuendukov** [comment]
I apologize for the misunderstanding, I have created a ticket to resolve this issue on our dashboard. You can see the progress of this task in this issue.

**Comment by DmitriyKirakosyan** [comment]
Closing as fixed.
