### ISSUE TITLE
Feature Request: CLI support for webhooks

### ISSUE THREAD

**Issue by araphiel-nf** [microsoft/appcenter-cli#2471]
**Describe the solution you'd like**

Adding CRUD operations for working with AppCenter webhooks.

```
/api/v0.1/apps/${{ APP_OWNER }}/${{ APP_NAME }}/alerts_webhooks
/api/v0.1/apps/${{ APP_OWNER }}/${{ APP_NAME }}/alerts_webhooks/${{ WEBHOOK_ID }}
```

https://github.com/microsoft/appcenter-cli/blob/9930a9d5171a780290c99f617a651d13023ed3e6/src/util/apis/generated/src/operations/webhooks.ts#L17

**Comment by MikhailSuendukov** [comment]
Hello @araphiel-nf and thank you for reaching out to us, could you please clarify what exactly do you mean? Do you mean the command for this [request](https://openapi.appcenter.ms/#/alerting/webhooks_list)?

**Comment by araphiel-nf** [comment]
Hi @MikhailSuendukov — essentially porting the already generated openapi client for use in the webhooks - (listing, creating, deleting) into the CLI

**Comment by MikhailSuendukov** [comment]
Hi @araphiel-nf this API is not documented and is not officially supported, so we do not plan to add it to the CLI yet. So I'm closing this issue, but if you have any questions, feel free to reopen it.
