### ISSUE TITLE
unable to login appcenter

### ISSUE THREAD

**Issue by cheriviralakarthik** [microsoft/appcenter-cli#2472]
### **Description**
when i am using command appcenter login  getting interactive question enable telemetry when i enter y or n getting fileerrors i have seen these in mac but in windows it is working perfectly 

output:
  appcenter login                 
    ? Enable telemetry?  (Y/n) (node:26807) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use 
   a userland alternative instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    ? Enable telemetry?  Yes
    **Error: Command 'login' failed with exception "ENOENT: no such file or directory, open '/Users/karthikcherivirala/.appcenter- 
   cli/telemetryEnabled.json'"**

and another issue 

when i install the appcenter there are so many warnings
 output:
  npm install -g appcenter-cli 
    npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: 
  https://bit.ly/2ZEqIau
    npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain 
  circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain 
  circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm WARN deprecated superagent@5.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with 
   streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the 
  releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
    
    added 489 packages in 24s

### **Repro Steps**
Please list the steps used to reproduce your issue.
1.appcenter login
2.y or n

### **Expected behavior**
appcenter login should open the browser automatically for token 

### **Details**
1. appcenter login or any command related to appcenter
2. appcenter version 2.14.0
3. macbook air m2 macos sonoma
4. zsh
5.node v21.3.0 ,npm 10.2.4

**Comment by AnatolyPristensky** [comment]
Hello @cheriviralakarthik, I've tried to reproduce your issue, but all works as expected:

```
user@MacBook-ProM1Pro /dev % appcenter login
Opening your browser... 
? Visit https://appcenter.ms/cli-login?hostname=MacBook-ProM1Pro.local and enter the code:
? Access code from browser:  61004466b86447333481bf*******
Logged in as v-an***-microsoft.com
```

Other commands also works as expected:

```
user@MacBook-ProM1Pro /dev % appcenter help 

Visual Studio App Center helps you build, test, distribute, and monitor mobile apps.
Version 2.14.0

Usage: appcenter <command>

Commands:
    analytics                      View events, audience info, sessions, and  
                                   other analytics for apps                   
    apps                           View and manage apps                       
    build                          Start builds, get their status, and        
                                   download artifacts                         
    codepush                       View and manage CodePush deployments and   
                                   releases                                   
    crashes                        Upload symbols for better crash reports    
    distribute 
```

Please make sure that appcenter-cli installed correctly. 

Regarding your second question - we already have such issue and working on it - https://github.com/microsoft/appcenter-cli/issues/2470

**Comment by mmckinley8** [comment]
I'm having this same issue
