### ISSUE TITLE
List of command changes between versions

### ISSUE THREAD

**Issue by MihaMarkic** [microsoft/appcenter-cli#2480]
As the author of [Cake.AppCenter](https://github.com/cake-contrib/Cake.AppCenter) I wonder whether is there a list of changes between versions, specially major ones like the recent 3.0.0 which would help me updating the addin.

**Comment by DmitriyKirakosyan** [comment]
Hi @MihaMarkic , you can find the list of changes on https://github.com/microsoft/appcenter-cli/releases/tag/v3.0.0.

The biggest update was upgrading `autorest` and getting rid of `request`, see https://github.com/microsoft/appcenter-cli/pull/2370

**Comment by MihaMarkic** [comment]
Hi, yes, I looked at that but there is no mention about CLI command syntax changes. Perhaps there are none and it's just about internal changes? Do you usually list those as well?

**Comment by DmitriyKirakosyan** [comment]
@MihaMarkic, there are no changes in the command syntax. Please reopen the issue if you find any commands not working as expected.
