### ISSUE TITLE
The test runner failed to start. The XCUITest-Runner failed to start.

### ISSUE THREAD

**Issue by Pignatar0md** [microsoft/appcenter-cli#2482]
### **Description**
Please describe the issue you are facing using the CLI.
When I run the command "appcenter test run xcuitest --app ..." tests fails in appcenter, but runs ok locally using xcode.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. create the xcuitest
2. run it
3. run in terminal "xcrun xcodebuild build-for-testing -configuration Release -workspace..."
4. run in terminal  "appcenter test run xcuitest --app ..."

### **Expected behavior**
The UI tests in appcenter "tests" section should run OK.

### **Details**
    appcenter test run xcuitest --app "APP_NAME" --devices "USER/DEVICE_SET" --test-series "TS_NAME" --locale "LOCALE" --build-dir PATH

App Center CLI version:
    2.14.0
OS version:
    macOS Sonoma 14.2

command line/shell:
    Shell 14.2 /bin/zsh 5.9

Node.js and NPM:
    node v18.19.0, npm 10.2.3

Logs:
![Captura de pantalla 2024-03-01 a la(s) 12 03 57](https://github.com/microsoft/appcenter-cli/assets/8237423/a7d7eff4-9b54-44f8-b25e-24c175dd01d0)
<img width="1421" alt="Captura de pantalla 2024-03-01 a la(s) 12 04 48" src="https://github.com/microsoft/appcenter-cli/assets/8237423/7da6cd3d-17b5-4d41-a3db-f6f5204dde27">
<img width="1416" alt="Captura de pantalla 2024-03-01 a la(s) 12 05 19" src="https://github.com/microsoft/appcenter-cli/assets/8237423/bdd70bb2-caf2-437e-ba79-633d832abd9b">

Please help, I don't know what else to try.

**Comment by nikita-potashev** [comment]
Could you please contact support?
https://learn.microsoft.com/en-us/appcenter/help

**Comment by Pignatar0md** [comment]
Ok, thank you for your response. I will do it. Could you tell me what is related to?

**Comment by nikita-potashev** [comment]
Please escalate it via portal, we will check it. Thanks a lot.
