### ISSUE TITLE
Using appcenter-cli version: 3.0.0 Error: Failed to create release upload for build/app/outputs/flutter-apk/app-blastgolf-release.apk. Backend response: Not found. Correlation ID: 6d547d0e-497e-4231-8aa4-a9ca8641fdf2

### ISSUE THREAD

**Issue by eekesh2thapa** [microsoft/appcenter-cli#2483]
### **Description**

I am getting the following error in gitlab ci logs

Using appcenter-cli version: 3.0.0
Error: Failed to create release upload for build/app/outputs/flutter-apk/app-blastgolf-release.apk. Backend response: Not found. Correlation ID: 6d547d0e-497e-4231-8aa4-a9ca8641fdf2

### **Here is the code **
flutter_build_android:
  when: manual
  stage: build
  before_script:
    - flutter clean
    - flutter packages get
    - flutter gen-l10n
    - npm install -g appcenter-cli@latest
  script:
    - |
      if [ $FLAVOR == "blastgolf" ]; then
        FLAVOR_PATH="blastgolf"
        FLAVOR_TARGET="lib/blast_golf/main_blast_golf_staging.dart"
        APP_NAME="Blast Golf"
      elif [ $FLAVOR == "blastbaseball" ]; then
        FLAVOR_PATH="blastbaseball"
        FLAVOR_TARGET="lib/blast_baseball/main_blast_baseball.dart"
        APP_NAME="Blast Baseball"
      else
          echo "No Flavour provided"
      fi
       flutter build apk --release --target $FLAVOR_TARGET --flavor $FLAVOR_PATH
      echo "FLAVOR_PATH: $FLAVOR_PATH"
      echo "APP_NAME: $APP_NAME"
      APK_PATH="build/app/outputs/flutter-apk/app-$FLAVOR_PATH-release.apk"
      #APK_PATH="build/app/outputs/apk/blastgolf/release/app-$FLAVOR_PATH-release.apk"
      echo "APK PATH: $APK_PATH"
    - echo "logs"
    - appcenter login --token $token
    # - appcenter distribute release -f "$APK_PATH" -g "Android-QA" -a admin-bjzg/NextGen-Blast-Golf-Android --release-notes "Version $buildNumber" --debug
    - FILE_URL="https://gitlab.thewitslab.com/wil-workspace/wil-blastmotion/blastgolf-mobile-flutter/-/jobs/${CI_JOB_ID}/artifacts/build/app/outputs/flutter-apk/app-blastgolf-release.apk"
    - echo "$FILE_URL"
    - echo "FILE_URL success"
    - |
    #  curl -X POST -H 'Content-Type: application/json' 'https://chat.googleapis.com/v1/spaces/AAAAZiRX1w8/messages?key=AIza***qsHI&token=QP***3jDI' -d '{"text": "'"${APK_NAME}"' Android Build\nBuild executed by: '"${GITLAB_USER_NAME}"'\nBuild Name: '"${BUILD_NAME}"'\n'"${FILE_URL}"'"}' -exportPath ./build
    # - echo "Success chat"
    - appcenter distribute release -f "$APK_PATH" -g "Android-QA" -a admin-bjzg/NextGen-Blast-Golf-Android --release-notes "Version $buildNumber" --debug
    - echo "appcenter distribute chat"   

  artifacts:
    paths:
      - build/app/outputs/flutter-apk/

**Comment by DordeDimitrijev** [comment]
Hello @eekesh2thapa thank you for reaching out. Have you tried using any of the previous versions of the cli, does the issue occur then?  Could you please enable additional debug logging  by setting the environment variable like this and post the output here to further analyze it.
`DEBUG="appcenter-cli:commands:distribute:release" appcenter distribute release ...`

**Comment by DordeDimitrijev** [comment]
Closing due inactivity.
