### ISSUE TITLE
appcenter-cli 3.0.0 network issues

### ISSUE THREAD

**Issue by Titozzz** [microsoft/appcenter-cli#2488]
Disclaimer: this bug report is something to find if anyone else has the same issue, or any idea of what's happening. It lacks a clear repro. In the meantime a simple downgrade fixed the issue

### **Description**
After updating to 3.0.0, our CI was unable to make any network request with the CLI, so something happened with that relase but not sure what.
-> It works locally
-> It work on a similar Docker image to CI
-> On CI: `Error: {"message":"Failed to initialize file upload process."}`
### **Repro Steps**
This only happens within our CI, sorry

### **Expected behavior**
Should work 🤷🏻 

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - appcenter codepush release-react
2. Which version of the App Center CLI are you using?
    - 3.0.0
3. Which OS version did you experience the issue on?
    - Docker Node 20
4. What command line/shell are you using?
    - bash
5. What version of Node.js and NPM/Yarn are you using?
    - e.g. node v20

**Comment by DordeDimitrijev** [comment]
Hello [@Titozzz](https://github.com/Titozzz) thank you for reporting this issue. Could you please set environment variable and run codepush like this
`DEBUG="appcenter-cli:*" appcenter codepush release-react`
and share the debug logs. Also are there  any differences between the docker container where it works and the CI where it fails such as os version, network connection  etc.

**Comment by DordeDimitrijev** [comment]
HI @Titozzz can you please try updating node-fetch and let me know if it helps. Take a look https://github.com/microsoft/appcenter-cli/pull/2497

**Comment by DordeDimitrijev** [comment]
Closing due inactivity.
