### ISSUE TITLE
appcenter login not working properly on macOS

### ISSUE THREAD

**Issue by nandowastaken** [microsoft/appcenter-cli#2490]
### **Description**
When I type appcenter login, I get redirect to the appcenter page generating the token, however, when I come back, the terminal process is no longer available for me to paste the token, see the image below to get my view after getting redirect to appcenter page.

<img width="718" alt="Captura de Tela 2024-03-30 às 12 02 45" src="https://github.com/microsoft/appcenter-cli/assets/79945109/499a5bbd-3876-4389-94c8-0b3433a8ad91">

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. npm i -g appcenter-cli
2. appcenter login

### **Expected behavior**
I expect to type appcenter login, get redirect to the page, and when I come back to the terminal, I would be able to paste the token in it.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - appcenter login
3. Which version of the App Center CLI are you using?
    - 3.0.0
4. Which OS version did you experience the issue on?
    - MacOS.
5. What version of Node.js and NPM/Yarn are you using?
    - node 21.6.0, npm 10.2.4

**Comment by mikepaszkiewicz** [comment]
@nandowastaken can confirm same behavior for 3.0.0 with below versions on MacOS

however, installing `appcenter-cli@2.14.0` and logging in allows the interactive terminal to persist and successfully login with token.

node: 18.19.0
npm: 10.2.3

**Comment by nandowastaken** [comment]
@mikepaszkiewicz Thanks for the reply, downgrading appcenter to 2.14.0 worked for me! 

I also have 2 apps at my machine from 2 different accounts, and it was right after adding the second app that the issue started, however, I need them both so it may be more interesting for me to keep using 2.14.0 for a while.

**Comment by batuhanbag** [comment]
@mikepaszkiewicz thanks downgrading worked me as well.
