### ISSUE TITLE
Implement Zstandard Compression for Smaller and Faster Updates

### ISSUE THREAD

**Issue by sean5940** [microsoft/appcenter-cli#2492]
Issue: Enhance Bundle Compression with Zstandard

Hello CodePush Maintainers,

I am currently developing a React Native app utilizing CodePush for updates and have been exploring ways to optimize the update experience for our users. One significant factor that impacts the update process is the size and speed of the deployment bundles.

**Suggestion: Zstandard Compression**

After researching various compression algorithms, I suggest considering the integration of Zstandard (zstd) as an alternative to the existing ZIP compression method. Developed by Facebook, Zstandard offers several advantages:
- Higher Compression Ratios: Zstandard can significantly reduce the bundle size compared to ZIP compression, potentially leading to smaller update payloads for end-users.
- Faster Decompression Speed: Zstandard provides much faster decompression times, which could accelerate the update installation process and enhance the overall user experience.
Adjustable Compression Levels: It allows for a fine-tuned balance between compression ratio and speed, accommodating different deployment scenarios.

**Benefits for CodePush:**
- Data Usage: Smaller update sizes would save users' data, which is particularly valuable for those on limited data plans.
- Update Speed: Quicker decompression on the client side means faster update installations, making the process less intrusive.
- User Experience: Enhanced update speed and reduced download sizes contribute to a smoother and more positive user experience.

I believe that adopting Zstandard could be a valuable enhancement for CodePush. I would love to hear your thoughts on this and discuss the feasibility of such an integration.

Thank you for considering this suggestion.

**Comment by DmitriyKirakosyan** [comment]
@sean5940 , thanks for reaching out! Since the standalone version of [code-push-server](https://github.com/microsoft/code-push-server) is out, feel free to create a fork or contribution and implement this feature.
