### ISSUE TITLE
 Error "unable to get local issuer certificate" during "appcenter login" on macOS

### ISSUE THREAD

**Issue by nullmicgo** [microsoft/appcenter-cli#2493]
### **Description**
I encountered an error while trying to use the `appcenter login` command on macOS. After pasting the access code from the browser, I received the following error message: "Error: unable to get local issuer certificate."

### **Repro Steps**
To reproduce the issue, follow these steps:
1. Open the terminal on macOS.
2. Execute the command `appcenter login`.
3. Proceed with the login process and copy the access code from the browser.
4. Paste the access code into the terminal.

### **Expected behavior**
I expected the `appcenter login` command to authenticate successfully and grant access to the App Center CLI.

### **Details**
1. Is there a particular command that you are having trouble with?
    - No, the issue occurs during the login process.
2. Which version of the App Center CLI are you using?
    - Please provide the version number. For example, 2.7.4.
3. Which OS version did you experience the issue on?
    - Please provide the specific macOS version. For example, macOS Big Sur 11.1.
4. What command line/shell are you using?
    - Please specify the shell you are using. For example, `/bin/bash` or `/bin/zsh`.
5. What version of Node.js and NPM/Yarn are you using?
    - Please provide the version numbers of Node.js and either NPM or Yarn. For example, Node.js v12.19.0, npm 6.14.8.
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command. For example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, but remember to **omit** any personal or sensitive data.

**Comment by nullmicgo** [comment]
version 3.0.0

**Comment by DmitriyKirakosyan** [comment]
@nullmicgo thank you for the report! What Nodejs version do you use? Does this command work on appcenter@2 for you?

**Comment by nullmicgo** [comment]
sorry, i fixed.
i think it is VPN issue, after i disconnected the VPN, then it works.
Thanks
