### ISSUE TITLE
Tell me if an update is available, and how to update

### ISSUE THREAD

**Issue by dvdsgl** [Microsoft/appcenter-cli#251]
Please let me know if there's a new release of `mobile-center-cli` and how to update.

```shell
$ mobile-center help
*An update is available* Install it with: mobile-center update
```

**Comment by amchew** [comment]
@dvdsgl thanks for the good suggestion, and we'll discuss this feature in our CLI yellow padding session on 11/03 and update again.

**Comment by christav** [comment]
Consider integrating https://www.npmjs.com/package/update-notifier

**Comment by amchew** [comment]
Hi there @dvdsgl ! Thanks for your feedback, and yes we've incorporated this functionality in the latest CLI v1.1.0 release today. To do this, you have to install CLI v1.1.0, and then you will see the update when we release v1.2.0. The earlier versions don't have the code to check for updates in them, and in the future users will get update notifications.
