### ISSUE TITLE
test espresso: Appending tilde to --build-dir

### ISSUE THREAD

**Issue by kamstrup** [Microsoft/appcenter-cli#272]
I am not able to upload an espresso test at all. No matter how I format the arguments ithe m-c cli always appends a '~' to the --build-dir argument. Thus pointing at a non-existing directory.

Example. I have an app and corresponding test apk in /home/kamstrup/Downloads:
```
$ mobile-center test run espresso --app "kamikkel/MyApp" --devices 31be1403 --app-path Downloads/myApp.apk  --test-series "master" --locale "en_US" --build-dir Downloads
\ Preparing tests... events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open 'Downloads/~'
    at Error (native)
```

(~this is with m-c cli version 0.9.1, there seem to have been 2 releases since then, but I can not update via npm for some reason?~ (just tried with 0.11.0 and still have the issue))

**Comment by kamstrup** [comment]
In a desperate effort to get something running I copied the APKs to ~/ to have the files show up at the malformed path. Now I just get another seemingly unrelated error:

```
$ mobile-center test run espresso --app "kamikkel/MyApp" --devices 31be1403 --app-path myApp.apk  --test-series "master" --locale "en_US" --build-dir .
/ Preparing tests... events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENXIO: no such device or address, open '.config/Code/1.10.2-shared.sock'
    at Error (native)
```

**Comment by krukow** [comment]
@kamstrup is this on linux only?

**Comment by john7doe** [comment]
I've tried to reproduce the problem. I do not get the same error, but do get an error:

node /Users/john7doe/src/mobile-center-cli/dist/index.js test run espresso --app "john7doe/foo" --devices 31be1403 --app-path build/outputs/apk/XTCAndroidSample-debug.apk  --test-series "master" --locale "en_US" --build-dir build/outputs/apk/ --debug
Preparing tests... done.
Validating arguments... done.
| Creating new test run... logFilter, request: WebResource {
  rawResponse: false,
  queryString: {},
  url: 'https://api.mobile.azure.com/v0.1/apps/john7doe/foo/test_runs',
  method: 'POST',
  headers:
   { 'Content-Type': 'application/json; charset=utf-8',
     'user-agent': 'mobile-centerCli/0.11.0 NodeJS/v7.5.0 darwin/16.7.0',
     'x-api-token': 'b8acdac0c70a541bc6f1622b70312779494745b0',
     'internal-request-source': 'cli',
     'diagnostic-context': 'da3d223e-7c52-48a6-8144-a9bf5e3c0562',
     'cli-command-name': 'test run espresso' },
  body: null }
- Creating new test run... Response status code: 404
Body: {"message":"","code":"Not Found"}
Creating new test run... failed.
Error: {"message":"","code":"Not Found"}

Not sure whats happening, but is not a TypeScript expert. I think we should get someone else to look at it? @skovsboll

**Comment by kamstrup** [comment]
Yeah, this is on Ubuntu 17.04 @krukow

**Comment by kamstrup** [comment]
Reproduced as described today (ensuring that i was logged into prod this time)

**Comment by owenniblock** [comment]
I can't replicate using:
Ubuntu 16.04
Node: v8.6.0
NPM: v5.3.0
mobile-center: v0.11.0

**Comment by owenniblock** [comment]
Also works locally from me on a fresh linux using:
`vagrant init bento/ubuntu-17.04-i386`

**Comment by kamstrup** [comment]
tested with nodejs 6.11.0 and 6.11.4 (from nodesource package repo). Will try the 8.* series now

**Comment by kamstrup** [comment]
Also reproduced with nodejs 8.7.0 from the nodesource package repo - maybe it is triggered by something weird in the package name of the app...

**Comment by kamstrup** [comment]
I can successfully submit our Test Cloud integration tests with NodeJS 8.7.0 - so it must be something particular to the first app I tested with...

**Comment by owenniblock** [comment]
I'll test using the app you sent me.

**Comment by owenniblock** [comment]
I'm getting a different error after upload with those apps:

```
mobile-center test run espresso --app "v-ownibl/Mikkel-Test-App" --devices 31be1403 --app-path Downloads/app-is24Tests-alpha-androidTest.apk  --test-series "master" --locale "en_US" --build-dir Downloads
Preparing tests... done.
Validating arguments... done.
Creating new test run... done.
Validating application file... done.
Uploading files... done.
Starting test run... failed.
Error: Error "Unexpected token I in JSON at position 4" occurred in deserializing the responseBody - "500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong." for the default response.
```

Suggest we add some more logging around the `--build-dir` and run it against your local system to try and see what it's doing.

**Comment by amchew** [comment]
Hi @kamstrup and @owenniblock, following up on this thread, do you both still have any issues with the bug?

**Comment by amchew** [comment]
Hi @kamstrup and @owenniblock, could you let me know if there are still any issues with the bug by Dec 22? Else I'll proceed to close this issue by then. Thanks.

**Comment by kamstrup** [comment]
Just tested the old problematic Espresso test with appcenter 1.0.6 and nodejs version 8.9.3 on Ubuntu 17.10 and everything seems to work. Closing. :+1:

**Comment by amchew** [comment]
Thanks @kamstrup !
