### ISSUE TITLE
Confusing package names

### ISSUE THREAD

**Issue by kamstrup** [Microsoft/appcenter-cli#273]
If you install 'mobile-center' with npm you get an outdated version of the cli available on the command line (0.9.1 I believe) and no amount of npm updating mobile-center will give you the latest version. If you install 'mobile-center-cli you get the latest. This is really confusing.

**Comment by christav** [comment]
I'm surprise the `mobile-center` package installs the CLI - that package is the React Native SDK for mobile center. The CLI package has always been named `mobile-center-cli`.

@elamalani Any ideas on these naming issues?

**Comment by amchew** [comment]
@kamstrup, just had a chat with @christav, we tried to reproduce the error, and installing `mobile-center` with npm does not give you the CLI, installing `mobile-center-cli` with npm should give you the latest version of the CLI. Are you still facing any issues?

**Comment by christav** [comment]
Closing this - package names are following usual NPM conventions.

**Comment by kamstrup** [comment]
Yep, can confirm that the mobile-center package no longer install the cli tool :+1:
