### ISSUE TITLE
OS X: setup-autocomplete - breaks file tab-completion

### ISSUE THREAD

**Issue by krukow** [Microsoft/appcenter-cli#285]
System: OS X Sierra 10.12.6, `mobile-center version 0.11.0`, `zsh`

Installing `setup-autocomplete` causes <tab> to complete filenames to stop working.

It would be great to get both autocomplete and tab-complete file names.

Example:
```
➜  espresso ls
total 69864
drwxr-xr-x@  4 krukow  staff   136B Oct 10 14:44 ./
drwx------+ 89 krukow  staff   3.0K Oct 10 15:59 ../
-rw-r--r--@  1 krukow  staff   2.4M Oct 10 14:44 gc-androidTest.apk
-rw-r--r--@  1 krukow  staff    32M Oct 10 14:44 gc.apk
```

```
➜  espresso mobile-center test run espresso --app "karl.krukow/Example-espresso" \ 
    --devices any_top_1_device \ 
    --app-path gc.ap<TAB> \ 
    --build-dir ./  \ 
     --debug --test-series master --output --test-parameter test=test
```

the <TAB> here does not complete the filename `gc.app`

here <TAB> does not complete file.

**Comment by RIDE55** [comment]
gc.appespresso ls
total 69864
drwxr-xr-x@  4 krukow  staff   136B Oct 10 14:44 ./
drwx------+ 89 krukow  staff   3.0K Oct 10 15:59 ../
-rw-r--r--@  1 krukow  staff   2.4M Oct 10 14:44 gc-androidTest.apk
-rw-r--r--@  1 krukow  staff    32M Oct 10

**Comment by christav** [comment]
Tab completion only supports bash at this time, not zsh.

**Comment by christav** [comment]
Reopening now that I understand the behavior better.

**Comment by amchew** [comment]
Hey @krukow and @RIDE55 , thanks for flagging this out! We've discussed this and working on fixing this in the next sprint. Will update again when it's completed.

**Comment by amchew** [comment]
Hi @krukow! The bug is now fixed in CLI v1.1.14. Please download the new version of the CLI, and test this out. Let us know if you run into any issues. Thank you for the patience!

**Comment by owenniblock** [comment]
@krukow I can't seem to replicate here. Although it looks like I'm on an older `node` version to you (not sure how that would lead to a `JSON` parsing error though!

**Comment by krukow** [comment]
Hey @owenniblock I've reproduced it on several networks today. I've also tried to uninstall appcenter-cli. I'm not a node or npm expert, so I'm not sure how to do a completely clean install which also uninstalls dependencies.

**Comment by owenniblock** [comment]
[This suggests maybe an npm cache issue](https://github.com/vuejs-templates/webpack/issues/990)

Suggestion is to try this:
> npm cache clean --force

**Comment by krukow** [comment]
It worked!

```
➜  ~ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing. (I didn't )

➜  ~ npm install -g appcenter-cli
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/local/bin/appcenter -> /usr/local/lib/node_modules/appcenter-cli/bin/appcenter.js
+ appcenter-cli@1.1.4
added 273 packages from 232 contributors in 12.081s
```

**Comment by amchew** [comment]
Yess @krukow 👯‍♂️ ! Have a good weekend.
