### ISSUE TITLE
Error: this.fixture.forEach is not a function - when using single parameters in arrays on uitest

### ISSUE THREAD

**Issue by owenniblock** [Microsoft/appcenter-cli#295]
## Steps To Replicate
On mobile-center-cli v0.12.0
Run a `mobile-center test run uitest` command with a single `--fixture`, `--include-category` or `--exclude-category` parameter

Outputs: `Error: this.fixture.forEach is not a function`

## Workaround
Include the command twice. E.g. `--fixture Tests --fixture Tests`

## Solution
A fix for this issue is [in this PR](https://github.com/Microsoft/mobile-center-cli/pull/294)

**Comment by christav** [comment]
Fixed in appcenter-cli 1.0.0.
