### ISSUE TITLE
Line endings in launch script

### ISSUE THREAD

**Issue by roland-chernov-akvelon** [Microsoft/appcenter-cli#305]
Currently, `appcenter` script doesn't work on Linux. It looks like `.gitattributes` need to be updated after renaming b5cc6612bafc4703e62f4cffe182d0852cfade4c.

##### Steps to reproduce

```
# npm install -g appcenter-cli
$ appcenter
/usr/bin/env: ‘node\r’: No such file or directory
```

##### Expected results

`appcenter` script should work on Linux.

**Comment by roland-chernov-akvelon** [comment]
Also, it seems that [this require](https://github.com/Microsoft/appcenter-cli/blob/master/src/util/apis/index.ts#L1) doesn't work because actual file name begins with the small "a".

**Comment by eddiekerr** [comment]
Same thing happening on OSX

**Comment by christav** [comment]
Argh - I'd gotten sporadic reports of the line-ending issue and had been unable to track it down. NPM 5 appears to generate the line endings correctly regardless of line endings of script, which would be a workaround until the gitattributes fix.

Thanks, should have a new release asap.

**Comment by christav** [comment]
Please try appcenter-cli@1.0.1 - this should now be fixed. I'll keep this issue open until I get verification the problem is solved.

**Comment by christav** [comment]
Have gotten verification that 1.0.1 fixes the issue.

**Comment by eddiekerr** [comment]
Thanks Chris, can confirm the update fixes it!
