### ISSUE TITLE
Error: App <AppName> does not exist for collaborators

### ISSUE THREAD

**Issue by thecachedbyte** [Microsoft/appcenter-cli#324]
Unable to push release from collaborators account. Only owners account is working for release.

**Comment by christav** [comment]
@max-mironov Are you looking at this?

**Comment by southerneer** [comment]
@thecachedbyte a coworker was having the same problem on an app I set up. A temporary workaround:

1. `npm i -g appcenter-cli && appcenter --version` -> appcenter version 1.0.4
2. `appcenter apps set-current <owner/app>`
3. `appcenter codepush release-react`

**Comment by max-mironov** [comment]
@christav yep, I'm looking at this.
@thecachedbyte, @southerneer 
Could you guys please confirm that you are still unable to release code-push update on appcenter 1.0.4 with the following command:
`appcenter codepush release-react -a <owner/app>`?

**Comment by southerneer** [comment]
@max-mironov that command did (unexpectedly) work for me while codepushing from a collaborator account. There seems to be flag(s) that cause it to break though. Usually what I see is...

Running "react-native bundle" command:
...
Releasing update contents to CodePush:
...
 Error: App <AppName> does not exist

**Comment by max-mironov** [comment]
@southerneer good to know that it is working now. I think it may be that it was not working previously due to you were using appcenter 1.0.3 version.

**Comment by buptkang** [comment]
@thecachedbyte @southerneer can you use the epicenter 1.0.4 version to re-verify if this issue has been resolved?

**Comment by carloscuesta** [comment]
Had the same problem but the `v1.0.6` version fixed it

**Comment by christav** [comment]
Had one response that this is fixed, others have not responded one way or the other. I'm going to close this under the assumption it's working with current release. If people are still having issues with this please either reopen this bug or create a new one.

**Comment by abdemirza** [comment]
I was facing the same issue then I logged into the appcenter again using `appcenter login` and then logged into my account and now new apps are showing up, verified it using `appcenter apps list`
