### ISSUE TITLE
React Native - Deleting output folder after release

### ISSUE THREAD

**Issue by renatoagds** [Microsoft/appcenter-cli#328]
Hi!

Today I migrated from `code-push-cli` to `appcenter-cli`, but I'm having a problem, I use the generated bundle and sourcemap to upload them for `sentry`:

https://docs.sentry.io/clients/react-native/codepush/

But, in the final of the release process the `appcenter-cli` delete the generated folder:

https://github.com/Microsoft/appcenter-cli/blob/master/src/commands/codepush/release-react.ts#L153

I want to propose a flag to avoid delete the output dir, so I could keep the files after a release.

**Comment by ruslan-bikkinin** [comment]
Hi @renatoagds and thanks for submitting the issue. I've been fixed it here: #329 Do you have a chance to take a look at it and check whether it works for you or you have any more issues with that?

**Comment by henrikra** [comment]
Please fix this :D It does not make sense that we are defining output directory and then it is deleted at the end :O We want also send our sourcemaps to Bugsnag

**Comment by renatoagds** [comment]
@ruslan-bikkinin hey! thanks for the quick response! I'll test today it and send the feedback. 👍

**Comment by renatoagds** [comment]
@ruslan-bikkinin tested your branch and worked like a charm, waiting for a new release. 🚀

**Comment by sergey-akhalkov** [comment]
Hi @christav, could you please merge this PR in addition to this one https://github.com/Microsoft/appcenter-cli/pull/331 and probably make a new CLI release?

**Comment by christav** [comment]
I merged the PR, I'll do a new release on Monday.

**Comment by christav** [comment]
Release 1.0.6 is out with this fix. I'm closing this, if 1.0.6 doesn't fix the issue please reopen this.
