### ISSUE TITLE
Wrong error message in case all API tokens have been removed

### ISSUE THREAD

**Issue by sergey-akhalkov** [microsoft/appcenter-cli#334]
Hi, I've found issue with very rare repro steps, but I believe it should be fixed due to server returns correct response.

**Environment:**
```
$ appcenter -v
appcenter version 1.0.5
```

**Repro steps:**
1.  `appcenter login`
2. go to the https://appcenter.ms/settings/apitokens and remove appcenter-cli token
2. `appcenter tokens list` or another command that requires authorization

**Actual:**
`Error: Command 'tokens list' failed with exception "apiTokensResponse.result.map is not a function"`

**Expected:**
`Error: Command 'appcenter tokens list' requires a logged in user. Use the 'appcenter login' command to log in.`

**Comment by amchew** [comment]
Hey @sergey-akhalkov, thanks for calling this out and the clear repro steps. I repro-ed and received the response `Error: Command token list not found`. The error message can be clearer and improved on. We've taken the feedback and will update again when this is fixed.
