### ISSUE TITLE
Build download problem

### ISSUE THREAD

**Issue by emrah-dautbegovic-sn** [Microsoft/appcenter-cli#335]
I am using the following command:

appcenter build download -t build -i "my-id" -a "my-app-name" --token "my-token"

and I'm getting this error message:
failed with exception "Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html"

If I try this command without specifying the app-name I get error message:
failed with exception "End of data reached (data length = 71699727, asked index = 1583568238). Corrupted zip ?"

I am able to download symbols and logs for the same build but I cannot download build.

appcenter version 1.0.5

**Comment by ranterle** [comment]
Hi @emrah-dautbegovic-sn - I think we have already touched on your request in App Center support but I also wanted to give an update here: Thanks for reporting this. We have identified the issue on our end and will be rolling out a fix. I am very sorry for causing these troubles for you.

**Comment by amchew** [comment]
Hi @emrah-dautbegovic-sn , we have rolled out a fix for this. Let us know if you're still facing any issues with this! (cc @ranterle)

**Comment by emrah-dautbegovic-sn** [comment]
Hi @ranterle  and @amchew 
Thank you for your time and this issue is really fixed.
There is one new issue that I'm faced with and I hope so you can help me to fix that because I think it can be connected to this one.
I'm trying to execute UITest tests on Appcenter through appcenter-cli.
I've downloaded the application build from appcenter and when I'm executing tests, I'm getting the following error message:

Preparing tests... done.
Validating arguments... done.
Creating new test run... done.
Validating application file... failed.
Error: End of data reached (data length = 45061548, asked index = 45080808). Corrupted zip ?

Further error details: For help, please send both the reported error above and the following environment information to us by going to https://appcenter.ms/apps and starting a new conversation (using the icon in the bottom right corner of the screen)

Can you please take a look and let me know if there is some quick fix for this?

Thank in advance

**Comment by RominHalltari** [comment]
I am experiencing this issue today. I did a debug build, I downloaded the build zip file, but I can't unzip it. This issue needs to be reopened.

**Comment by ranterle** [comment]
@RominHalltari Thanks for notifying us and sorry this is happening for you. Can you share what error you're seeing with us and ideally reach out to our customer support with your app information and the build you were trying to download?

**Comment by DennisWeluDts** [comment]
@matthiaswenz I am also not able to download a build from app center. Worked last week on the 5th. Tried again today the 11th, not working. Tried on both Windows and Mac. Seems like the download is slow and the size of the zip is different every time. Error message is `Unable to expand "build.zip" into "Downloads" (Error -1 - Undefined error: 0.)`

**Comment by DennisWeluDts** [comment]
Whoops I guess I was confused by the dates. Its 2020 now not 2019. I can start a new thread...
