### ISSUE TITLE
Delete analytics events along with properties

### ISSUE THREAD

**Issue by rfreire** [Microsoft/appcenter-cli#338]
Deleting an analytics event do not delete the associated properties.
When a new event is sent with the same name, the old property values are there.

It would be great to be able to clear everything for an event (full reset).

**Comment by amchew** [comment]
Hi @rfreire thanks for letting us know! It is a bug and we've recorded this in our backlog, and plan to work on this in the next few sprints.

**Comment by blparr** [comment]
Hello @rfreire !! This should be fixed now, please try again and let us know if you're still experiencing issues. Thanks!
