### ISSUE TITLE
`--target-binary-version` does't allow describe all version name variants

### ISSUE THREAD

**Issue by Belobobr** [Microsoft/appcenter-cli#341]
Currently with `--target-binary-version` we can describe the app version as a \<major\>.\<minor\>.\<point\> string,   but actually it can be like  "1.1-build-variant".

For android we defined our flavors so:
`
 productFlavors {
    firstCustomer {
        applicationIdSuffix ".firstCustomer"
        versionNameSuffix "-firstCustomer"
    }
    secondCustomer {
        applicationIdSuffix ".secondCustomer"
        versionNameSuffix "-secondCustomer"
    }
   thirdCustomer {
        applicationIdSuffix ".thirdCustomer"
        versionNameSuffix "-thirdCustomer"
    }
}
`
For ios we are planning to use different schemas.

We want to be able to specify version code and build-variants on which release will be available.
For example: version: 1.1.0, buildVariants: [firstCustomer, secondCustomer]

**Comment by sergey-akhalkov** [comment]
Hi @Belobobr, thanks for reaching us! Could you please clarify - do you want to release an update for several build variants/schemas at once? If so, CodePush backend is designed to get an app version or range that meets the [semver rules](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter) only.
Your example actually means that we need to make 3 releases that target 3 apps with different app versions but w/ the same deployment key.
We haven't met such kind of feature requests before and your use case looks very specific, so we've added it to the backlog and going to discuss and implement it later after another high priority features. Of course, we'll prioritize this feature in case of a lot of similar requests. 

As of now you can make releases one by one using `--target-binary-version` parameter as usual.
Also I believe it won't be very too difficult to implement a node js script that will parse you build.gradle file and make needed releases automatically.

Please let us know if you have any concerns/considerations or ideas.

**Comment by Belobobr** [comment]
Hi, thanks for answers. I think such case very common for Vertical SaaS applications. 
It would be very convenient to be able to see which release currently delivered to our customers(flavors). Of course we can create an app for every customer(throught management sdk). Also we can receive deployment metrics and display it in format apropriate for us.

**Comment by Belobobr** [comment]
Sorry for incorrect issue. We will have different bundle.js for our customers so we must have different deploy keys for each customer.

**Comment by sergey-akhalkov** [comment]
Hi @Belobobr, no problem! Just let us know if you have any questions or need any help.

**Comment by amchew** [comment]
Hi @Belobobr , reading this thread, did we answer all your questions/issues? Please let us know if you have any other questions.
