### ISSUE TITLE
AppStore release from command line?

### ISSUE THREAD

**Issue by skleest** [Microsoft/appcenter-cli#353]
Wondering if it's in pipeline - thank you!

**Comment by amchew** [comment]
Hey, @skleest thanks for reaching out. That's not currently in our pipeline for Distribution. However, we're working on creating the new pipeline in the coming weeks for distribution. Could you share more on your use case?

**Comment by skleest** [comment]
Got it - we usually release to codepush + appstore at the same time and thought it'd be useful to handle both in AppCenter. Thanks for the update!
