### ISSUE TITLE
Appcenter integrations

### ISSUE THREAD

**Issue by guylando** [Microsoft/appcenter-cli#359]
I am not sure where I should ask this so please redirect me to the right place:
 We are considering microsoft appcenter and the main factor for us is if the appcenter will be able to integrate with other systems such as Segment.io, mixpanel to receive application events via direct integration or webhooks? Because we want to use the push notifications and analytics on the application events

**Comment by guylando** [comment]
Thanks!

**Comment by guylando** [comment]
@blparr Hello! just want to check, since 4 months passed, did your answer change and you now have some third party products?

**Comment by blparr** [comment]
Unfortunately not, we have had other high priority items in App Center, so we don't have any new integrations with third party products at the moment.
