### ISSUE TITLE
Unable to assign an application to an organization or create an application under an organization

### ISSUE THREAD

**Issue by Aionsphere** [microsoft/appcenter-cli#369]
Through the CLI, I can create and application or organization, however I cannot create an application in an organization or assign an application to an organization after creation.

I can create an org and then an app in it, with these two rest calls.

1. Create Org
curl -X POST "https://api.appcenter.ms/v0.1/orgs" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"display_name\": \"BPCustomer\", \"name\": \"BPCustomer\"}"

2. Create application under that organization
curl -X POST "https://api.appcenter.ms/v0.1/orgs/BPCustomer/apps" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"description\": \"TestApp\", \"display_name\": \"TestApp\", \"name\": \"TestApp\", \"os\": \"iOS\", \"platform\": \"Xamarin\"}"

**Comment by RWOverdijk** [comment]
👍 this would be very useful.

**Comment by amchew** [comment]
Hi @MicrosoftCSA and @RWOverdijk - thanks for this feedback/feature request and @MicrosoftCSA for providing the helpful workaround! I've logged this feature in our backlog. We currently don't have this yet, and there's no ETA yet.

**Comment by joan-saum** [comment]
Hi @amchew 
Any news about this feature ? It would be really useful

**Comment by matthiasleitner** [comment]
@amchew is there already a way to achieve this? I am seeing the support for this in the generated client code, not sure however how this would be exposed trough the cli api
