### ISSUE TITLE
Appcenter installed through terminal but no commands recognized

### ISSUE THREAD

**Issue by AlbaBrito** [Microsoft/appcenter-cli#404]
Hello, I'm desperate and I hope someone has experienced and solve this issue.
I have a macOS High Sierra and I installed nodejs, npm, java, ruby and other stuff for automated testing. I configured my appium and calabash tests locally and all works fine but when I try to make tests using Microsoft appcenter I can't.

I ran the command **npm install -g appcenter-cli**
and I get confirmation that appcenter was added successfully 
but when I try to run any command like **appcenter help** 
it says **-bash: appcenter: command not found**

I don't know if that's a problem with npm or with appcenter or maybe something external but I don't get any logs or specific errors.

Also when I drag and drop the file appcenter.js to the terminal, it is read perfectly well.

Any ideas??

**Comment by amchew** [comment]
Hey @AlbaBrito, one of the potential reasons is that there may be an issue with your node/npm setup (e.g. the location where the global scripts installed by NPM is not in your path). Let's confirm if this is the issue, could you run `npm install -g gulp-cli` and then run `gulp`? Let us know the results. If you get a not found error, then the path is the issue.

**Comment by AlbaBrito** [comment]
Hi I think that was exactly the problem but as I was in a hurry and didn't know how to modify this without affecting other tools, I reinstalled everything (I formatted my laptop) and that solved my problem.


Thanks anyway :)

**Comment by amchew** [comment]
@AlbaBrito - awesome! I'm glad it worked out in the end :)
