### ISSUE TITLE
Local NUnit test result file missing

### ISSUE THREAD

**Issue by applied-kevinsalot** [Microsoft/appcenter-cli#406]
Hi, I'm using the following command (some values redacted):

`appcenter test run uitest --app <myApp> --devices <deviceId> --app-path <myApk> --test-series master --locale en_US --build-dir <dir> --uitest-tools-dir <dir> --nunit-xml DroidTestResults.xml --include-category XTC`

I'm not seeing an nunit result file being generated. I tried absolute and relative paths. I use this to pass results to my CI build. 

The commmand upload and runs the test successfully. Test results are reported to the command line, but no file is created.

I believe this was possible before using Xamarin Test Cloud.

**Comment by krukow** [comment]
Hi @applied-kevinsalot  - this problem is being address currently. Follow progress in this PR: https://github.com/Microsoft/appcenter-cli/pull/400

**Comment by rmarinho** [comment]
@krukow any progress getting this in? AppCenterTask will not work as expected without this fix I think.

**Comment by christav** [comment]
@rmarinho This has been merged and will be in the next release - later this week or early next week.

**Comment by amchew** [comment]
Hey @applied-kevinsalot and @rmarinho , this has been addressed in our [CLI v 1.0.14](https://github.com/Microsoft/appcenter-cli/pull/419) released on [Apr 2](https://docs.microsoft.com/en-us/appcenter/general/changelog). Thank you again for bringing this to our attention @applied-kevinsalot ! I'll be proceeding to close this ticket now. If you have any other questions, please feel free to file a ticket again.

Thank you to @krukow , @owenniblock @erychagov and @christav for working on this! :)
