### ISSUE TITLE
crashes upload-symbols filename

### ISSUE THREAD

**Issue by yaliashkevich** [Microsoft/appcenter-cli#407]
I use following command to upload dsyms .zip file to appcenter:
`appcenter crashes upload-symbols -a test-organization-0706/testapp.ios -s D:\app.dev.2.0.2.233.dSYM.zip`

After that if I go to http://appcenter.ms I see that .zip is uploaded but filename changed to generic/auto-generated one:
`upload-2018-03-13T09-19-34Z.zip`

If I use UI to upload symbols it keeps original (friendly) filename.

It looks like appcenter api has optional parameter `file_name`:
https://openapi.appcenter.ms/#/crash/symbolUploads_create
but it is not set by `SymbolsUploadingHelper`.

`SymbolsUploadingHelper.uploadSymbolsZip(zip: string)` should set `SymbolUploadBeginRequest.fileName` value based on filename in input zip path.

**Comment by amchew** [comment]
Hi @yaliashkevich, thank you for letting us know about this! We're investigating this (cc: @saraford).

**Comment by amchew** [comment]
Hi @yaliashkevich, keeping you updated: we've currently logged this bug in our backlog to fix. There's no ETA for the fix yet, the team is going through other work items now. Will keep you updated. Meanwhile, I'll be closing this bug/conversation. Feel free to reach out again if you have any errors!

(cc @blparr)

**Comment by sheehanm** [comment]
Any update?

**Comment by afreenhossain** [comment]
Hello, any update or workaround for this?
