### ISSUE TITLE
How to run appcenter command through Jenkins

### ISSUE THREAD

**Issue by pedrokarsan91** [Microsoft/appcenter-cli#422]
In order to execute Xamarin Test Cloud tests, you have to execute an appcenter command e.g.

_appcenter test run uitest --app "appName" --devices 228faeda --app-path appPath --test-series "master" --locale "en_US" --build-dir debugFolderPath_

This works perfectly.

- I want to trigger this command via Jenkins.

- I added "Execute Windows batch Command" with the command shown above.

I execute the build.

But I get the following error in the Console Output

_"C:\Program Files (x86)\Jenkins\workspace\Xamarin Test Cloud Android>appcenter 'appcenter' is not recognized as an internal or external command, operable program or batch file."_

Why is that?

Thanks

**Comment by krukow** [comment]
Hi it looks like the execution environment for the batch command is not correctly set up (e.g., PATH does not contain the directory of the appcenter CLI).

**Comment by amchew** [comment]
Hi @pedeokarsan91, please see above ^

**Comment by amchew** [comment]
Hey @pedrokarsan91, did this issue get solved for you? We haven't heard back from you in some time, and I'll be closing this ticket for now. Please reach back again if you have questions, and we'll reopen this ticket again.

Thank you for your support!
Amanda
