### ISSUE TITLE
App Center Test --merged-file-name behavior

### ISSUE THREAD

**Issue by glennwester** [Microsoft/appcenter-cli#432]
Tweaking the “publish test results”

If the parameter --merged-file-name is used, we should automatically create a folder by default without explicitly adding this parameter --test-output-dir.

If the users wishes to change this output directory name they can add the parameter and specify the name.

**Comment by amchew** [comment]
Hi @glennwester, thanks for notifying. We chatted on this via Slack and I've logged this under our PM backlog as a feature request.
