### ISSUE TITLE
Distribute to app stores?

### ISSUE THREAD

**Issue by henninghall** [Microsoft/appcenter-cli#440]
Is there any possibility to distribute releases to App Store, TestFlight or Google Play? I might have misunderstood the docs, otherwise consider this a feature request.

**Comment by amchew** [comment]
Hey @henninghall - unfortunately, there's no way currently to distribute releases to the store yet. I've taken this feature request down in our [backlog](https://msmobilecenter.visualstudio.com/PM/_workitems/edit/40159), and we'll update our [changelog](https://docs.microsoft.com/en-us/appcenter/general/changelog) when this is done. 

Thanks again for the feedback. Let me know if you have any questions!

**Comment by henninghall** [comment]
Thanks for the answer!
