### ISSUE TITLE
Deployment list does not report install metrics

### ISSUE THREAD

**Issue by dudeinthemirror** [Microsoft/appcenter-cli#448]
I confirmed that codepush is pushing updates correctly to several devices by inspecting the codepush metadata and also by looking at the log:
```
06-08 22:50:36.488  5741  5809 I ReactNativeJS: [CodePush] Sync already in progress.
06-08 22:50:36.495  5741  5809 I ReactNativeJS: [CodePush] Sync already in progress.
06-08 22:50:36.525  5741  5809 I ReactNativeJS: [CodePush] Checking for update.
06-08 22:50:36.530  5741  5809 I ReactNativeJS: [CodePush] Reporting binary update (1.1.0)
06-08 22:50:37.482  5741  5809 I ReactNativeJS: [CodePush] Downloading package.
06-08 22:50:44.551  5741  5817 D ReactNative: [CodePush] Applying full update.
06-08 22:50:44.567  5741  5809 I ReactNativeJS: [CodePush] Installing update.
06-08 22:50:44.618  5741  5810 D ReactNative: [CodePush] Loading JS bundle from 
```
however when I do a list no install metrics are reported:'

```
appcenter codepush deployment list -a ***/***-Android
┌─────────┬───────────────────────────────────────┐
│ Name    │ Key                                   │
├─────────┼───────────────────────────────────────┤
│ RELEASE │ H2ys96***4nM │
├─────────┼───────────────────────────────────────┤
│ STAGING │ RK88HKnt***qzDnG │
└─────────┴───────────────────────────────────────┘
```

Environment:
```
$ > appcenter -v
appcenter version 1.0.16
$ > react-native -v
react-native-cli: 2.0.1
react-native: 0.54.1
```

This is happening for both our RELEASE and STAGING deployment targets
Thank you.

Some more details, hope it will help with the investigation:
Here is the code I'm using to capture the Codepush metadata:

```javascript
 static async getAppVersion(): Promise<string> {
    const version = DeviceInfo.getReadableVersion();
    const codePushVersion = await CodePush.getUpdateMetadata();
    if (codePushVersion) {
      return `${version}_${codePushVersion.label}`;
    }
    return `${version}_v0`;
}
```

and here is a snapshot of how that looks like on one of the devices:
![version](https://user-images.githubusercontent.com/981638/41194245-4a12247a-6bcd-11e8-8d18-2cff3ada4ba5.png)

Also, the bottom of the `history` command for STAGING:
![screen shot 2018-06-09 at 10 10 55 am](https://user-images.githubusercontent.com/981638/41194262-830e9c5e-6bcd-11e8-8a8b-ad12976a4ca8.png)

**Comment by Zakeelm** [comment]
Hey there! 
Install metrics aren't reported when using the `appcenter codepush  deployment list`  command. This is something we've been looking at bringing to it though. For now, the solution would be to run the ` code-push deployment list` command in the CodePush CLI rather than the App Center CLI. Also, install metrics  are visible in the App Center portal. Is that what you're referring to?

**Comment by dudeinthemirror** [comment]
hi @Zakeelm I tried running `code-push deployment list <appname>` and I get:
```
[Error]  App "<appname>" does not exist.
```
Also, I looked everywhere in the AppCenter portal, I don't see any install metrics
Please help, this is a big drawback compared to the old standalone version of codepush, we are basically sailing blindly.
BTW, in the meantime, any way to use the old standalone code-push (not part of Appcenter)? 
Thanks very much for your time!

**Comment by Zakeelm** [comment]
Is it identical to the app name of what is displayed when you run `code-push app list`? 

Also, by going to Distribute->CodePush in the Portal you can select a particular release and by clicking it you will see the install metrics. 

And yes, you can just the CodePush CLI! (it's still technically a part of AppCenter though and we do recommend using the App Center CLI, but we understand it depends on your workflow)

**Comment by dudeinthemirror** [comment]
> Is it identical to the app name of what is displayed when you run code-push app list?
It turned out that code-push was logged into something different (a previous account) than appcenter codepush. So, yes as soon as I logged out and the in with the new account `code-push deployment  list <appname>` returned the stats. Duh!

> Also, by going to Distribute->CodePush in the Portal you can select a particular release and by clicking it you will see the install metrics.
Well hidden, but yeeeey I found it! 

> And yes, you can just the CodePush CLI! (it's still technically a part of AppCenter though and we do recommend using the App Center CLI, but we understand it depends on your workflow)
👌 Nice.
Closing this. Thanks again for a great product. And yes, please bring all the awesomeness of code-push into AppCenter!
