### ISSUE TITLE
Yarnpkg is down ?

### ISSUE THREAD

**Issue by avinashwigroup** [Microsoft/appcenter-cli#453]
Hello,

I'm trying to build for iOS with Appcenter and I'm encountering the below error : 

=========================================================================
[command]/bin/sh -c if [ -f yarn.lock ]; then { yarn install && yarn list --depth=0; } else npm install; fi
yarn install v***.7.0
[***/4] Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
##[error]/bin/sh failed with return code: ***
##[error]/bin/sh failed with error: /bin/sh failed with return code: ***

============================================

Indeed the 'https://registry.yarnpkg.com/' website is down but on our side what can we do about it ? This is preventing automatic builds .

**Comment by amchew** [comment]
Hey @avinashwigroup, I spoke to our team on this error. Could you please start a conversation with us on App Center (go to App Center, and click on the blue conversation dialog button at the bottom right hand corner)? We'll assign someone to take a look at this. Sorry for that.

**Comment by amchew** [comment]
Hey @avinashwigroup, I haven't seen a conversation on this in App Center - perhaps I'm wrong. If you're still facing this issue, could you please click on the blue conversation dialog button at the bottom right-hand corner and start a conversation with us? Thanks!

**Comment by avinashwigroup** [comment]
Hello @amchew ,

This was indeed an issue caused by the yarnpkg server being down.

It is now resolved.

Thanks and Kind Regards,
Avinash

**Comment by amchew** [comment]
@avinashwigroup, great to hear that this is revolved!
