### ISSUE TITLE
Support for specifying multiple distribution groups in a release

### ISSUE THREAD

**Issue by isuda** [Microsoft/appcenter-cli#467]
Is it possible via the CLI to upload a release to multiple distribution groups?

It does not appear that there is a way to upload a release once, and share it with multiple groups using `appcenter distribute release -g`.

Example: I want to share the release with the Collaborators group, which is managed at the organization level, and then also share it with another group which includes a few additional testers which are not part of the organization, all from a CI environment, using the cli.

**Comment by amchew** [comment]
Hi @isuda, did you manage to try this our via the APIs? Let me know if you have any questions.

**Comment by isuda** [comment]
Hi @amchew - We are looking into it. Thanks for letting me know about it.

**Comment by amchew** [comment]
@isuda sounds good 👍

**Comment by amchew** [comment]
Hi @isuda, I'll be closing this ticket for now, please let us know if you face any issues, and we can reopen this ticket. 

Thanks!

**Comment by thiemf** [comment]
Hi, has this been taken up as a feature request? We have the same requirement. Using the REST API is more complex than the cli, if possible we would like to use the cli only. 
Thanks!
Regards,
Matthias

**Comment by jvnike** [comment]
Yes, please add this feature to the cli tool!

**Comment by hari331996** [comment]
Yes, It would be great if this feature is added to cli too. Also we are not able to disable notification when we use 'appcenter distribute release', so it would be really nice if all that would be available.

**Comment by liszto** [comment]
@hari331996 notification is fixed into 2.2.0 but yeah I approved the feature from this ticket !
