### ISSUE TITLE
Codepush release-react results in error

### ISSUE THREAD

**Issue by larslockefeer** [Microsoft/appcenter-cli#469]
I'm trying to push a new release to Codepush from our CI environment (Travis) using the following command:

```
appcenter codepush release-react -a {app_name} -d {deployment_name}
```

I have defined an `APPCENTER_API_TOKEN` environment variable to handle logging in. This works for commands such as `appcenter distribute release`. However, when I run `appcenter codepush release-react`, I get the following error:

```
Releasing update contents to CodePush:
Error: TypeError: Cannot read property 'accessToken' of null
error Command failed with exit code 3.
```

If I explicitly login with the following command:

```
appcenter login --token ${TOKEN}
```

Everything works as expected.

**Comment by amchew** [comment]
Hey @larslockefeer thanks for letting us know! I've created a ticket to investigate this. In the meantime, could you run the `appcenter codepush release-react` with the `--debug` switch again, and post the output/logs here? This will help us debug better. 

Thanks!

**Comment by owenniblock** [comment]
I've not yet found the reference to `APPCENTER_API_TOKEN` in the code (I'll keep digging) but I have found the Access Token environment variable: `APPCENTER_ACCESS_TOKEN` - could you try setting that and see if it behaves any differently?

**Comment by larslockefeer** [comment]
Thanks for your quick replies!

@owenniblock I'm afraid I made a mistake in my report, I meant `APPCENTER_ACCESS_TOKEN` but mixed up when writing the ticket.

I am going to do some more digging on my side as well, will try with the `--debug` option and post back my own findings later today.

**Comment by owenniblock** [comment]
Great thanks - let us know if that `--debug` options gives us any more information. I'll try to replicate here.

**Comment by owenniblock** [comment]
Just another thought - while we're investigating this to fix the error - could you try this?

`appcenter codepush release-react -a {app_name} -d {deployment_name} --token ${TOKEN}`

Which should work in the same way as when you log in prior to calling `codepush`.

**Comment by owenniblock** [comment]
Thanks @larslockefeer - we found the issue. There's a fix here: https://github.com/Microsoft/appcenter-cli/pull/471

Hoping to get it released next week along with some other stuff.

Thanks for reporting!

**Comment by larslockefeer** [comment]
Cool, thanks for the quick resolution! 💪

**Comment by amchew** [comment]
Thanks @owenniblock for the quick work! @larslockefeer we'll keep you updated again when the release comes out next week.

**Comment by amchew** [comment]
Hi @larslockefeer ! We have just released CLI v1.1.2, and the bug fix for this issue is in this new release. Please download the new CLI version and test it out; let us know if you face any issues.

**Comment by amchew** [comment]
Hi @larslockefeer, this issue should have been fixed in CLI v1.1.2, please download the new CLI version and test it out. I'll be closing this issue for now. Feel free to reopen this issue again if you run into any problems. Thanks!

**Comment by larslockefeer** [comment]
Hey @amchew, sorry for not following up earlier. I just tested the new version and everything works as expected.

Thanks for the quick fix and follow-up! 🙇‍♂️

**Comment by amchew** [comment]
No problem @larslockefeer ! Glad that it's working now. 👍
