### ISSUE TITLE
Further test-parameter specification

### ISSUE THREAD

**Issue by daniel-varela** [microsoft/appcenter-cli#484]
Hi,

Unfortunately there is no documentation about the `test-parameter` option which can be set when running `appcenter test run espresso` for example. It would be nice to know what this key-value-pair could be in order to better configure UI-tests. In our case especially if there is an option for the Android Test Orchestrator.

**Comment by owenniblock** [comment]
I agree - it would be useful to have better documentation of the `test-parameter` option - I'll pass this feedback on to my PM.

To answer your specific question: unfortunately there is currently no option for Android Test Orchestrator when using Espresso in App Center however this is recorded as a feature (it's not yet been approved to go on our backlog so I can't say if or when it's likely to be implemented).

**Comment by daniel-varela** [comment]
Thank you for clarifying my Android Test Orchestrator question.

**Comment by amchew** [comment]
Hi @daniel-varela thanks for your feedback on documentation! I'll be working on this, and will update again when it is completed by next week.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
