### ISSUE TITLE
Disable telemetry check when running `appcenter telemetry`

### ISSUE THREAD

**Issue by squirly** [microsoft/appcenter-cli#485]
When running
```
> appcenter telemetry off
```
I get the following prompt
```
App Center CLI would like to collect data about how users use CLI commands and some problems they
encounter. Participation is voluntary and when you choose to participate your device automatically sends
information to Microsoft about how you use App Center CLI.
For more information, please see our privacy policy at https://aka.ms/mobilecenterprivacy

? Enable telemetry?
```

This seems like counter intuitive behaviour and this check should should not happen when running the `telemetry` command

## Steps to reproduce
Run
```
rm ~/.appcenter-cli/telemetryEnabled.json
```
then run any `appcenter telemetry` command.

## Workaround
For now, I am adding `--disable-telemetry` to the commands. EG:
```
appcenter telemetry off --disable-telemetry
```

**Comment by amchew** [comment]
Hi @squirly, thanks for the feedback on this behavior, that the prompt should not appear when the user runs `appcenter telemetry off`. We've taken your feedback on this, and will let you know again when this is resolved. I'll keep this ticket open for now.

**Comment by grndvl1** [comment]
Can you turn if off by default when running other scripts like distribute?
