### ISSUE TITLE
Not filter by date

### ISSUE THREAD

**Issue by MaxiTalenti** [Microsoft/appcenter-cli#489]
I am wanting to filter the errors by the event date but it returns any. How do I have to assemble the URL?

My url is : https://api.appcenter.ms/v0.1/apps/{owner}/{app}/errors/errorGroups/{errorId}/errors?24top=1000&start=2018-09-02&end=2018-09-03

Response get error with timestamps:
- "timestamp": "2018-10-03T14:12:02.7178124Z"
- "timestamp": "2018-10-01T04:37:17.7989236Z"
- "timestamp": "2018-09-28T16:20:15.931282Z"
...
Etc.

**Comment by amchew** [comment]
Hey @MaxiTalenti! 

I can channel your questions about the Analytics API to our team. Could you please go to App Center, and click the blue conversation icon at the bottom right-hand side of the website and 
(i) post your question there
(ii) mention that you'll like to be transferred to Amanda Chew. 

I'll take your question to the right team there.

**Comment by amchew** [comment]
Hey @MaxiTalenti, would you have any more feedback for us?

**Comment by MaxiTalenti** [comment]
Yes, still the filter by date is not working.
