### ISSUE TITLE
Number of errors are not equal

### ISSUE THREAD

**Issue by MaxiTalenti** [Microsoft/appcenter-cli#490]
- **errorCountsPerDayAPI**
 -> /v0.1/apps/{owner_name}/{app_name}/errors/errorGroups/{errorGroupId}/errorCountsPerDay

- **errorForGroupAPI**
 -> /v0.1/apps/{owner_name}/{app_name}/errors/errorGroups/{errorGroupId}/errors

When I consult the api to get the number of errors per day (**errorCountsPerDayAPI**) of a certain group I get a number, example 100.
But when I consult the other api to get error by mistake (**errorForGroupAPI**), I never get the amount that says the first API (**errorCountsPerDayAPI**), for example i get 86 errors.

**Comment by amchew** [comment]
Hey @MaxiTalenti! Thanks for reaching out. 

For /v0.1/apps/{owner_name}/{app_name}/errors/errorGroups/{errorGroupId}/errorCountsPerDay, it returns the counts of errors by day in the time range of the selected error group with a selected version, whlist /v0.1/apps/{owner_name}/{app_name}/errors/errorGroups/{errorGroupId}/errors returns all errors for group, so the numbers will be different, and it is expected. 

Let me know if that answers your question! :)

**Comment by MaxiTalenti** [comment]
Hi @amchew,

Yes, I know, but I'm using the same **errorGroupId** and filtering the cases of **errorForGroupAPI** for a specific day I do not get the same amount that **errorCountsPerDayAPI** tells me, but I always get fewer errors.

**Comment by amchew** [comment]
Hey @MaxiTalenti, got it. 

I can channel your questions about the Analytics API to our team. Could you please go to App Center, and click the blue conversation icon at the bottom right-hand side of the website and
(i) post your question there
(ii) mention that you'll like to be transferred to Amanda Chew.

I'll take your question to the right team there.

Thanks!

**Comment by amchew** [comment]
Hey @MaxiTalenti, would you have any more feedback for us?

**Comment by MaxiTalenti** [comment]
Not yet

**Comment by amchew** [comment]
Sounds good! I'll be closing this conversation for now; feel free to re-open this conversation if you have any other questions. Thanks!
