### ISSUE TITLE
After deleting event history, new events with the same name are not visible. 

### ISSUE THREAD

**Issue by xyashapyx** [Microsoft/appcenter-cli#491]
After deleting event history, new events with the same name are not visible anymore.
I assumed that after deleting history of the event, new logged events with the same name will be visible.
Am I wrong?

**Comment by amchew** [comment]
Hi @xyashapyx, thanks for reaching out! This is by design: after deleting an event, we hide the deleted event for one hour. If the device sends the same event back, and if it is after an hour, the event becomes visible again. 
cc @blparr

**Comment by amchew** [comment]
Hi @xyashapyx , would you have any other questions for us?

**Comment by amchew** [comment]
Hi @xyashapyx, I haven't heard back from you, and will be proceeding to close this conversation. Feel free to re-open this/re-comment here if you have any other questions!

**Comment by RinseWashRepeat** [comment]
Sorry to revive such an old issue, but I just wasted time on this. Could we add to the deletion message so that it's clear that data will be deleted and the Event won't accept new instances for an hour?
