### ISSUE TITLE
How to get deployment env in cordova hooks?

### ISSUE THREAD

**Issue by hzzcc** [Microsoft/appcenter-cli#501]
I need to get deployment env in cordova hooks, When I use command "appcenter codepush release-cordova -a xxx -d Staging". Or can you keep custom arguments pass to cordova prepare command?

**Comment by alexandergoncharov** [comment]
Hi @hzzcc,
Thanks for reporting!

Could you please provide more info about `deployment env` which your need?

About keeping some arguments for `cordova prepare` command: appcenter-cli can't keep do that for now. I think that we can mark this as feature request. Could you please describe your case more detailed? why you would like to use it?

Thanks,
Alexander

**Comment by amchew** [comment]
Hey @hzzcc ! Let us know if you can provide more information above ^?

**Comment by amchew** [comment]
Hi @hzzcc I'll be closing this ticket as we've not heard back from you. Feel free to ping us again if you have any questions!
