### ISSUE TITLE
Unable to manage teams

### ISSUE THREAD

**Issue by sdebruyn** [microsoft/appcenter-cli#503]
Managing teams through the CLI is currently not possible.

**Comment by amchew** [comment]
Hi @SamuelDebruyn ! We currently don't have this feature yet, but is in our backlog. I'll leave this open as a feature request. To the community, if you'd like to see this feature supported, do add a +1 here.

**Comment by N7K4** [comment]
Any update on that topic? We need to add apps to teams, or vise versa team should have access to apps. 
Is the an API call to curl / wget it?

**Comment by russelarms** [comment]
Hi @N7K4, we have an API description here: https://openapi.appcenter.ms/#/account
Add apps to teams:
https://openapi.appcenter.ms/#/account/teams_addApp

**Comment by nehasonakul777** [comment]
Hi @DmitriyKirakosyan 
I’m looking for Appcenter Cli command to invite a user ( present in org ) to a team.

**Comment by nehasonakul777** [comment]
@DmitriyKirakosyan  : Any updates ?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
