### ISSUE TITLE
Add support to upload-symbols for breakpad 

### ISSUE THREAD

**Issue by Kudo** [Microsoft/appcenter-cli#505]
As far as I know, AppCenter did support breakpad recently.
From the [API document](https://openapi.appcenter.ms/), it seems breakpad symbol upload is supported as well.
Unfortunately, appcenter-cli upload-symbools only accepts dSYM or xcarchive.
Is it possible to add breakpad symbols?
Hopefully, Android proguard mappings.txt should be next thing to be added as well.

Thank you.

**Comment by amchew** [comment]
HI @Kudo Thanks for reaching out! We'll get back shortly.

**Comment by blparr** [comment]
Hello @Kudo , thanks for reporting this!

Breakpad symbol upload should indeed be supported. Have you tried doing this via UI? If so, does it work there? We will look into the CLI issue you reported.

Wrt Android mappings, we recently did the work to add support for that. You should see in the UI a mappings page for java/kotlin and react native. We are working on adding Cordova and Unity.

Can you please let me know if these don't work for you?

Thank you!

**Comment by Kudo** [comment]
Hi @blparr,

Currently upload breakpad symbols or Android mappings.txt seems only existed on Web UI.
I would like to upload symbols automatically from CI.
That's why to request this feature in appcenter-cli.

Thank you!

**Comment by blparr** [comment]
Thanks for confirming. I just wanted to make sure that there was an alternative way for you to do it via UI, while we fix the CLI.

We will be adding that to the CLI soon. Thanks for your patience!

**Comment by Kudo** [comment]
Thanks and looks forward to seeing this feature coming to cli.

**Comment by amchew** [comment]
Hey @Kudo ! We've created a bug in our board for this, and I'll be closing this issue for now. @blparr will contact you again once this is fixed. Thank you again, and happy hols soon!
