### ISSUE TITLE
What URLs need to be whitelisted for 'appcenter distribute release' command?

### ISSUE THREAD

**Issue by malwatte** [Microsoft/appcenter-cli#507]
Release of new app version fails,
command
`appcenter distribute release -g "Internal Testers" -f "1.apk" -r "Test release note" -a "{{app}}"`
Output
`Error: failed to create release upload for 1.apk`

I am working inside a corporate network. Same command works fine when I bypass the corporate network. I want to know the URLs being called when I do the `appcenter distribute release` command. Then I can give the list of URLs to company IT team and ask them to whitelist those URLs.

Thanks.

**Comment by maxxkrakoa** [comment]
Hi @malwatte 

The urls being used for that command should all be on the `https://api.appcenter.ms` subdomain.

I hope talking to your IT team about this URL will bring you a step closer to having a working solution.

**Comment by malwatte** [comment]
@maxxkrakoa 
Thanks. I'll work with IT team and get it whitelisted.
Hopefully it should fix the issue.

**Comment by amchew** [comment]
Hi @malwatte, let us know if that works for you, and if you have any other feedback!

**Comment by amchew** [comment]
Hi @malwatte , I'll be closing this ticket as it's been some time since we've heard back. If you have any updates, please feel free to re-open this ticket and comment here!

**Comment by rzee7** [comment]
Hey @amchew 
I'm getting the same error while uploading IPA to the appcenter.

```
Step 1/1: DeployIPAToAppCenter (Command Line) (6s)
[Step 1/1] Starting: /Work/Tools/temp/agentTmp/custom_script915767146824669477
[Step 1/1] in directory: /Work/Tools/work/2ec921dd40ce8997
[Step 1/1] Logged in as mohammed.riyaz
[Step 1/1] Error: failed to create release upload for lib/Release/Onsolve.Mobile.iOS.ipa
[Step 1/1] Process exited with code 3
[Step 1/1] Process exited with code 3 (Step: DeployIPAToAppCenter (Command Line))
[Step 1/1] Step DeployIPAToAppCenter (Command Line) failed

```
I've double checked app and organization name. I'm using following command:

```
appCenter login --token %api_token%
appCenter distribute release -f lib/%profile%/app.something.iOS.ipa -g Group-QA -a Org-Name/App-Name
```

Thanks
Riyaz

**Comment by rzee7** [comment]
Hey @amchew 
I'm getting the same error while uploading IPA to the appcenter.

```
Step 1/1: DeployIPAToAppCenter (Command Line) (6s)
[Step 1/1] Starting: /Work/Tools/temp/agentTmp/custom_script915767146824669477
[Step 1/1] in directory: /Work/Tools/work/2ec921dd40ce8997
[Step 1/1] Logged in as mohammed.riyaz
[Step 1/1] Error: failed to create release upload for lib/Release/app.something.iOS.ipa
[Step 1/1] Process exited with code 3
[Step 1/1] Process exited with code 3 (Step: DeployIPAToAppCenter (Command Line))
[Step 1/1] Step DeployIPAToAppCenter (Command Line) failed

```
I've double checked app and organization name. I'm using following command:

```
appCenter login --token %api_token%
appCenter distribute release -f lib/%profile%/app.something.iOS.ipa -g Group-QA -a Org-Name/App-Name
```

I'm able to upload android APK with similar command.

Thanks
Riyaz
