### ISSUE TITLE
Test status fails with unclear error message

### ISSUE THREAD

**Issue by SamuelDebruyn** [Microsoft/appcenter-cli#515]
`appcenter test status --test-run-id c61016cd-dbe4-492a-85c1-dc43f7001aec`

Error: Command 'test status --test-run-id c61016cd-dbe4-492a-85c1-dc43f7001aec' failed with exception "Couldn't find AppUpload with [WHERE "app_uploads"."sonoma_app_id" = $1 AND "app_uploads"."id" = $2]"

**Expected**

- The status of my UI test run OR a clear error message

**Actual**

- Exception

**Comment by amchew** [comment]
Thanks @SamuelDebruyn for giving us this feedback - indeed our error message is not clear. @glennwester, fyi on this feedback ^

**Comment by glennwester** [comment]
Hello, I'm the PM for App Center Test. Apologies for the delay in my reply. 

Can you please try seeing the current app? You can get a list of the apps with: `appcenter apps list`, then find the app you want to get status on, then you can set the current app with `appcenter apps set-current "Org/App1"`. 

You will then be able to call `appcenter test status --test-run-id "cdf23071-7932a-44219-85327-da32134b7d95d6"` and see a status similar to:

Current test status: Done!
Total scenarios: 4
0 passed
4 failed
Total steps: 4

Please let me know if this resolves the issue!

**Comment by amchew** [comment]
Thank you @glennwester !!

**Comment by SamuelDebruyn** [comment]
That works, thanks!

**Comment by amchew** [comment]
Glad to hear that @samueldebruyn! Feel free to reach out again if you have questions.
