### ISSUE TITLE
[Test] Incorrect error message displayed when attempting to upload to an unavailable organization

### ISSUE THREAD

**Issue by King-of-Spades** [Microsoft/appcenter-cli#523]
# Overview
AppCenter CLI version 1.1.9

# Description
If attempting to upload an app to an organization that cannot be found, the CLI shows an error message like so:
> The app named APPNAME does not exist in the organization or user: ORGNAME

A more correct error message would be:
> The organization ORGNAME cannot be found

Or some similar/equivalent wording.

**Comment by amchew** [comment]
Thanks @King-of-Spades for your feedback! FYI @glennwester on this feedback ^.

**Comment by amchew** [comment]
Hi @King-of-Spades, we've added this improvement to our backlog. I'll be closing this ticket for now. Thanks! 
FYI @glennwester
