### ISSUE TITLE
Upload Sourcemaps / symbols for Android?

### ISSUE THREAD

**Issue by snap608** [Microsoft/appcenter-cli#532]
Is there any progress on support for uploading Android Sourcemaps / Symbols via appcenter-cli?

**Comment by amchew** [comment]
Hey @snap608, Thanks for commenting! I'll check with the relevant PM and we'll get back again.

**Comment by amchew** [comment]
Hi @snap608 I'll be closing this ticket for now, and we've left a note in our backlog to reach out to you once this feature is completed. Let us know again if you have any other feedback!

**Comment by Bresiu** [comment]
@amchew Do you have estimated time for releasing this feature? Can you update this ticket when it will be available in new release?

**Comment by winnieli1208** [comment]
Hi @Bresiu - sorry for the delayed response. We have no updates yet but I will post in this thread when our team picks this item up!

**Comment by winnieli1208** [comment]
Hi @snap608 - just want to clarify - are you looking for a way to upload Android ProGuard mappings, Android NDK symbols or React Native Android source maps?
