### ISSUE TITLE
failed with exception "Unknown argument --displayKeys"

### ISSUE THREAD

**Issue by isaaclem** [Microsoft/appcenter-cli#534]
> Command 'codepush deployment list -a <org>/<app> --displayKeys' failed with exception "Unknown argument --displayKeys"

I'm following this but failed? 
https://docs.microsoft.com/en-us/appcenter/distribution/codepush/tutorials

**Comment by amchew** [comment]
Hi @isaaclem, could you run the --debug flag and post the results here? It will help us to debug better!

**Comment by botatoes** [comment]
@isaaclem this should work without "--displayKeys" 
--displayKeys is outdated. I'll update the docs.
