### ISSUE TITLE
Unable to run tests using Nunit category expressions

### ISSUE THREAD

**Issue by juliandesmarais** [microsoft/appcenter-cli#537]
See Nunit Category Expression section for more info: [https://nunit.org/docs/2.5/consoleCommandLine.html](https://nunit.org/docs/2.5/consoleCommandLine.html)

This may be more of a feature request, but I'm not really sure how to re-use test cases for multiplatform/multidevice type testing without using categories in this way. Currently we are unable to send tests to AppCenter (via VSTS AppCenter Test step) using Nunit category expressions, such as --include-category A+B . This covers the use case of if you have test cases that are of specific feature sets, and are to be run on specific devices.

As an example - if I have all tests that are set to be run on phone type devices marked with a category of "Phone", and a subset of those tests are marked with feature set category of "Docs", there is no way to run these tests via AppCenter without running all tests marked with either category. Currently sending category expressions via --include-category parameters is not supported via AppCenter, only multiple --include-category parameters. In practice, this would look like sending --include-category Phone --include category Docs , which would run both all of the Phone category tests, and all of the Docs category tests.

Some Nunit category expressions:

A+B+C
Selects only tests having all three of the categories assigned (scenario described above)

A+B-C
Selects tests with both A and B but not C.

A+(B|C)
Selects tests having both category A and either of B or C

etc.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
