### ISSUE TITLE
generating source maps when output-dir specified

### ISSUE THREAD

**Issue by dgobaud** [Microsoft/appcenter-cli#538]
I'm using 1.1.9 all is good thanks to https://github.com/Microsoft/appcenter-cli/blob/v1.1.9/src/commands/codepush/release-react.ts#L132

I see you've removed this though in 1.1.10.

One problem is you ask for an output-dir and then generate a bundleName based on iOS or Android.

But sourcemap param wants a filename not a bath so we need to know the bundleName ahead of time.

You should change --sourcemap-output to --sourcemap-dir and generate the sourcemap file automatically to match the output file name based on the iOS/Android platform

**Comment by dgobaud** [comment]
App Center upgraded to 1.1.11 now its broken :(

**Comment by owenniblock** [comment]
We're working on this - although it's going to take us a while to get the fix out. In the meantime I recommend you work around it (as I believe you are working on) by manually specifying the file name.

**Comment by amchew** [comment]
Hi @dgobaud we fixed the bug in [v1.1.12](https://github.com/Microsoft/appcenter-cli/releases/tag/v1.1.12). Please upgrade to the latest version, and let us know if that works for you! I'll be closing this issue for now, but feel free to comment here/re-open this if you have any other questions.
