### ISSUE TITLE
Offering help to add NativeScript support

### ISSUE THREAD

**Issue by EddyVerbruggen** [microsoft/appcenter-cli#542]
Hi friends,

As a follow-up to https://github.com/Microsoft/code-push/pull/435, I'd like to offer our help adding support for NativeScript in the AppCenter CLI. As a matter of fact, I (and others in the NativeScript team and community) would be happy to submit a PR to add support - and maintain the integration later as well. The goal here is to bring a world-class app-updating feature to the NativeScript ecosystem.

Our "Plan B" would be forking this repo and adding support, then publishing the fork to a new package on npm. We'd also have to use some sort of clone of the server bits. Suffice to say, we're not looking forward to going this route though.. so please let us know if you're interested in this proposal.

Thanks in advance for considering supporting NativeScript once again!

**Comment by yilmazyavuz** [comment]
+1

**Comment by Sharpie360** [comment]
+1

**Comment by amchew** [comment]
Hey @EddyVerbruggen @yilmazyavuz and @Sharpie360, thanks for leaving us this comment! We'll respond shortly.

**Comment by rdlauer** [comment]
@amchew is there an ETA on when we might expect an update? We have a lot of folks interested in this. Thanks!

**Comment by jdnichollsc** [comment]
@amchew any news? This would be a perfect gift for my birthday 26/08 <3

**Comment by rdlauer** [comment]
@jdnichollsc take a look at [NativeScript AppSync](https://www.nativescript.org/blog/enable-live-updates-of-your-ios-and-android-apps-using-nativescript-appsync)

It's a fork of CodePush for {N}!

**Comment by amchew** [comment]
Hi all! Apologies for the delayed response. @EddyVerbruggen, @yilmazyavuz, @rabbitwerks, @rdlauer, @jdnichollsc yes we always welcome community contributions, so feel free to do so You can make PR with your contributions, see an example here: https://github.com/microsoft/appcenter-cli/pull/627. Thanks!

**Comment by jdnichollsc** [comment]
@EddyVerbruggen @rdlauer Ok, the moon station has copied us, how can I help you guys? **MissionControl: {N} => 🚀🚀🚀 => AppCenter** 💯

**Comment by kleydon** [comment]
The addition of this capability would make AppCenter significantly more valuable.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
