### ISSUE TITLE
Unable to upload mapping for android

### ISSUE THREAD

**Issue by poldz123** [microsoft/appcenter-cli#551]
The current cli does not support uploading symbolic mapping for android. Currently right now it supports ios and breakpad. Seems this is broken not supporting android.

**Comment by amchew** [comment]
Hi @poldz123 ! Thanks for putting in this feature request, @winnieli1208 - fyi.

**Comment by winnieli1208** [comment]
Referencing #532. We have an item on our backlog to fix this. Current ETA is closer to April but I will comment on this thread when we have any updates. Thanks!

**Comment by tomquist** [comment]
Hi @winnieli1208 since April is over, do you have any update on this?

**Comment by winnieli1208** [comment]
@tomquist no updates yet. This is definitely on our roadmap, we just haven't had the bandwidth to fix this yet. Thanks for everyone's patience!

**Comment by sseyod** [comment]
I have been able to upload symbols, for some NDK-based apps, but not all of them. This is really puzzling!

Basically - if I select "Diagnostics", some apps show the "Upload Symbols" button ... and some don't!!

Pete

**Comment by ranterle** [comment]
@sseyod This sounds like something you may want to ping our customer support in the App Center portal. They might need some information about your apps which you probably want to share in a private conversation.

**Comment by ranterle** [comment]
Some updates around this request, re @tomquist and everyone who was looking for this: [v1.1.19](https://github.com/microsoft/appcenter-cli/releases/tag/v1.1.19) added support for uploading Android (ProGuard) mappings, sorry for the delay in getting the word out here, too.

**Comment by poldz123** [comment]
@ranterle Thank you for the release with this functionality. I appreciate it.
