### ISSUE TITLE
`appcenter build branches show` seems to not work when running immediately after queuing a build

### ISSUE THREAD

**Issue by matt-dalton** [microsoft/appcenter-cli#560]
I'm using appcenter-cli version 1.1.13

We have a CI script that was working until about a week ago, so I suspect this bug came in with the 1.1.13 release.

In the script, we queue a build and then _immediately_ check the latest build branch, like so:
```
appcenter build queue -b master --app my-account/app

echo `appcenter build branches show -b master --app my-account/app --debug`
```

Whenever I run the `build branches show` command normally, it works perfectly. But in the context of this script, I sometimes get `Item "\" is an invalid commit SHA`.

I think I can see why this is from the debug output...

Usually, the `build branches show` command runs 2 steps: It gets the list of builds, then gets the commit info for the first one in a separate API call.
When I run this command immediately after queueing, it (sometimes) doesn't return a `sourceVersion` key for the recently queued build. The CLI then tries to find this blank commit and errors.

Adding a sleep of 2 seconds in between the 2 commands has fixed the issue in every run since, so it seems like a timing issue.

Does that make sense? Could this functionality have changed in the last release?

**Comment by amchew** [comment]
Hey @matt-dalton! Thanks for notifying us. We'll get back shortly.

**Comment by amchew** [comment]
@matt-dalton apologies for the late reply. Checking back in, are you still facing this issue?

**Comment by matt-dalton** [comment]
I had to put a timeout in so not sure....will check in due course

**Comment by phillipleblanc** [comment]
@matt-dalton I'm going to close this issue, feel free to re-open if you are still facing this issue.
