### ISSUE TITLE
After the production version is successfully updated (the updated content is found), the background application cache version is cleared and the phenomenon is rolled back.

### ISSUE THREAD

**Issue by duanpf** [microsoft/appcenter-cli#568]

**Comment by jpeg-ms** [comment]
Hi @duanpf 
Could you please explain your issue in more details?
Thanks in advance,

**Comment by amchew** [comment]
Hey there @duanpf, we're closing this ticket as there hasn't been a response; please feel to comment here or reopen the ticket if you have any issues!
