### ISSUE TITLE
Create app if doesn't exist.

### ISSUE THREAD

**Issue by legitappsdev** [microsoft/appcenter-cli#569]
We are trying to upload an app for testing from Bitrise. We can create an app like this:

appcenter apps create

The problem is it will create the app again even if it already exists. We could use this to delete it:

appcenter apps delete

But since it runs on Bitrise we don't know how to bypass the "Do you really want to delete the app Y/N" prompt.

Is there a way to only create an app if it doesn't exist? Or to delete w/o a prompt?

**Comment by jpeg-ms** [comment]
Note: You can also pass `--quiet` to avoid the prompt.
I believe this all should answer your question, so I'll close this issue for now.
