### ISSUE TITLE
CLI Creates Duplicate React Native Releases But Code-Push CLI Does Not

### ISSUE THREAD

**Issue by jstheoriginal** [microsoft/appcenter-cli#573]
We've been using the deprecated codepush cli with the following command:

`code-push release-react [REDACTED] android -d Prototype --des "no description for release" -t 4.5.1 --noDuplicateReleaseError`

It has always prevented duplicate releases if the same bundle was already created previously.

Now we have moved to the appcenter cli with this command:

`appcenter codepush release-react --app [REDACTED] --deployment-name Prototype --target-binary-version 4.5.1 --output-dir build/android --sourcemap-output-dir build/android/CodePush --disable-duplicate-release-error`

And it's creating a new release every single time when run off of the *exact same commit*.

See history:

<img width="872" alt="Screen Shot 2019-04-24 at 4 29 09 PM" src="https://user-images.githubusercontent.com/5117473/56695215-1c7ff000-66ae-11e9-86c4-fe5866296a71.png">

I'm assuming this is a bug and not an intended change because of the `--disable-duplicate-release-error` option existing on the appcenter cli.

**Comment by raghavsangamnerkar409** [comment]
This issue is still there. @jstheoriginal Did you get any workaround for this?
