### ISSUE TITLE
403 error when running appcenter distribute release

### ISSUE THREAD

**Issue by MichaelSafro** [Microsoft/appcenter-cli#578]
Running the command:

`appcenter distribute release -f APKName.apk -g "All Devs" -a 'ApplicationName'--debug`

and getting the error message below.  Using login or token seems work fine and the permissions for the users in the appcenter are either Manager or Administrator.  Is this something that is being done wrong/missed during the setup or when composing the command, or there is a problem with the CLI? 

```\ Loading prerequisites...Response status code: 404
Body: {"message":"Not found. Context ID: XXXXXXXXXXXXXXXXXXXXXXXX","code":"Not Found"}
| Creating release upload...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Organization/ApplicationName/release_uploads",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.15 NodeJS/v8.11.3 win32/6.3.9600",
    "x-api-token": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
    "internal-request-source": "cli",
    "diagnostic-context": "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
    "cli-command-name": "distribute release"
  },
  "body": null
}
/ Creating release upload...Response status code: 403
Body: {"message":"Forbidden","code":"Forbidden"}```

**Comment by MichaelSafro** [comment]
I had to place a correct Organization and Application names using slash. Those 2 commands were helpful
```appcenter orgs list```
```appcenter orgs app list```

Closing the ticket.

**Comment by hudsonansley** [comment]
Thanks, this was very helpful!
Also, the line for listing the apps was
`appcenter apps list`
that worked for me
