### ISSUE TITLE
Deployments are unsorted in `deployment list`

### ISSUE THREAD

**Issue by christophermark** [microsoft/appcenter-cli#579]
When viewing deployments via the old `code-push cli`, they would return sorted alphabetically by name:

`code-push deployment list`
```
v1.0
v2.0
v3.0
```

It would be useful if the Appcenter CLI could sort the deployments as well, instead of the current jumbled order. 

`appcenter codepush deployment list`
```
v2.0
v1.0
v3.0
```

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
