### ISSUE TITLE
Distribute/publish app to Apple TestFlight

### ISSUE THREAD

**Issue by l3ender** [microsoft/appcenter-cli#581]
How can I use the CLI to push new native builds to TestFlight? It is available through the AppCenter website but I don't see an equivalent CLI target.

This is desirable so that we can perform publishing through our automated build process.

**Comment by jpeg-ms** [comment]
This has been implemented in #647, #656 and #657. We will publish a release shortly.

**Comment by jpeg-ms** [comment]
To answer to this question specifically, TestFlight is a just track of the Apple App Store, so you simply would need to publish to the store using the correct track name (eg. "App Store Connect").
