### ISSUE TITLE
appcenter test prepare/run fail with "Command [...] is invalid" with recent releases on Node 12.1/12.2

### ISSUE THREAD

**Issue by frankbuckley** [microsoft/appcenter-cli#583]
Running `appcenter test prepare uitest` or `appcenter test run uitest` fails with errors similar to:

    Error: Command test prepare uitest --artifacts-dir /build/a1/_w/r3/a/AppCenterTest --app-path /build/a1/_w/r3/a/Apps-Release-iOS/drop/packages/Debug/App1.ipa --build-dir Apps-Release-iOS/drop/test/App1.UITests.iOS/bin/Debug --uitest-tools-dir Apps-Release-iOS/drop/tools/test-cloud --quiet is invalid

Running `appcenter help test prepare` results in:

    Commands that creates artifacts directories for supported test frameworks.
    
    Depending on the test framework, you may need to install additional tools. For example, Xamarin UI Tests require either .NET Framework or Mono, and Calabash tests require Ruby and the Xamarin Test Cloud gem. To get more information about dependencies of selected test framework, please type "appcenter help test prepare [framework name]".
    
    Artifacts directory contains manifest and all files required to start a test run. It can be later submitted to Test Cloud, without any external, framework-specific tools.
    
    Version 1.1.16
    
    Usage: appcenter test prepare <command>
    
    Commands:
        appium               Unable to load /usr/local/lib/node_modules/appcenter-cli/dist/commands/test/prepare/appium.js to read help                                          
        calabash             Unable to load /usr/local/lib/node_modules/appcenter-cli/dist/commands/test/prepare/calabash.js to read help                                        
        espresso             Unable to load /usr/local/lib/node_modules/appcenter-cli/dist/commands/test/prepare/espresso.js to read help                                        
        uitest               Unable to load /usr/local/lib/node_modules/appcenter-cli/dist/commands/test/prepare/uitest.js to read help                                          
        xcuitest             Unable to load /usr/local/lib/node_modules/appcenter-cli/dist/commands/test/prepare/xcuitest.js to read help 

Running `appcenter help test prepare uitest` results in:

    Error: Command test prepare uitest -h is invalid

Tried:

- Uninstalling/reinstalling
- Versions 1.11.15, 1.11.14
- Node versions 12.1, 12.2

However, downgrading to 1.0.7 works.

**Comment by frankbuckley** [comment]
Fixed by switching to Node 10.15.3

**Comment by King-of-Spades** [comment]
I was able to reproduce pretty much the same symptoms using this command:
> appcenter help test run uitest

I suspect all the "help" commands reproduce the issue. Reproduced on Node.js 12.2.0, and then when I switched back to 10.15.3 it worked again, didn't even have to restart the command line.

**Comment by jpeg-ms** [comment]
The CLI indeed requires node 10 at the moment.

**Comment by amchew** [comment]
@frankbuckley seems like it's working, we're closing this issue for now. Feel free to re-open if you face any issues!

**Comment by jstheoriginal** [comment]
FYI @jpeg-ms CircleCI updated all of their public pre-built android images to node 12 eight days ago, which is now causing issues with sentry's way of using the appcenter cli for sourcemaps.

https://github.com/CircleCI-Public/circleci-dockerfiles/commit/0ff22bb914ef7e4a92ecfb864b36f86d4f2aed7b

```
Failed to load AppCenter deployment history
  caused by: The deployment Staging does not exist.
```

Don't get that failure on node 10.
