### ISSUE TITLE
build logs -continue fails for active builds

### ISSUE THREAD

**Issue by MichaelMackendMS** [microsoft/appcenter-cli#585]
```
C:\Users\user1>appcenter build logs --continue --app "Team/App" --id 35

Error: failed to get build logs because build 35 doesn't exist
```
In this particular case build #35 is an actively running build.  It seems to me that the purpose of the --continue option is to get active logs from a running build.  Otherwise what's the point of --continue?  I would like to leverage this feature to provide live build status feedback through our Jenkins node that launched this job.

Thanks!

**Comment by vitalykarasik** [comment]
Any updates on it?
IMHO it's pretty basic functionality.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
