### ISSUE TITLE
unable to start appcenter from command prompt

### ISSUE THREAD

**Issue by sc104699** [microsoft/appcenter-cli#605]
steps to reproduce 👍 
1. cmd prompt > enter command "appcenter login"
2. enter the token >press enter.
3. see the error " self signed certificate in certificate chain".

error 👍 
**Opening your browser...
? Visit https://appcenter.ms/cli-login?hostname=9XZJQV2 and enter the code:
? Access code from browser:  bb414b762a83c71ac532e049f8e18b00dd094e28
**Error: self signed certificate in certificate chain****

**Comment by lumaxis** [comment]
@sc104699 Transferred the issue to the CLI repo.

**Comment by lumaxis** [comment]
@sc104699 Would you mind adding a few further details to this issue? What OS are you running, which version of the CLI? Thanks!

**Comment by sc104699** [comment]
I am using Windows 10 Operating System and AppCenter CLI version is Version 1.1.20

**Comment by jpeg-ms** [comment]
Hi @sc104699,
This is not reproduced anymore on version 2.1.2 (the latest at the moment of writing). Could you update the version of appcenter-cli on your side and try again?
Thanks,

**Comment by greektreat** [comment]
I am getting this with v 2.1.2 using windows 10

**Comment by jpeg-ms** [comment]
Okay I'm reopening this so we can give it another try.

**Comment by greektreat** [comment]
Actually not sure it's the same problem. I am able to get the token but when I enter it in the command line I get this error. We do have a selfsigned cert proxy network configuration.

**Comment by ahdbilal** [comment]
@greektreat Were you able to resolve this issue or it still exists?

**Comment by greektreat** [comment]
> @greektreat Were you able to resolve this issue or it still exists?

I had our network guys remove the proxy for the specific domain
