### ISSUE TITLE
Not accepting `--extra-bundler-option`

### ISSUE THREAD

**Issue by wbrickner** [microsoft/appcenter-cli#607]
I'm trying to run the command:

```sh
$ codepush release-react --extra-bundler-option="--config $PWD/rn-cli.config.js" -a MY_APP_NAME -d Staging
```

It fails and tells me that:

```
Detecting ios app version:

Using the target binary version value "1.0" from "ios/SnapshotClient/Info.plist".

Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/v3/ztdl856x27q_982g8mrd05d40000gn/T/code-push119615-20073-53ekm.xbnjyw/CodePush --bundle-output /var/folders/v3/ztdl856x27q_982g8mrd05d40000gn/T/code-push119615-20073-53ekm.xbnjyw/CodePush/main.jsbundle --dev false --entry-file index.js --platform ios --config /Users/wbrickner/Dropbox/3DSnapshot/Software/ipad-client/gen2/ws-based/SnapshotClient/rn-cli.config.js
error: unknown option `--config /Users/wbrickner/Dropbox/3DSnapshot/Software/ipad-client/gen2/ws-based/SnapshotClient/rn-cli.config.js'
Error: Failed to release a CodePush update.
```

This is troubling because `--config` is a valid option to pass to `react-native bundle`, and the command appcenter claims it is running actually works (I tried it).

This flag is super important in this case because I need to tell the bundler to ignore some colliding module names, otherwise it's impossible to bundle, which in turn makes it impossible to release updates over CodePush.

I understand the CodePush team is currently focusing on core functionality only, and has stepped back from bugs they consider to be minor.

The issue here doesn't touch any real code-push code, and gets stuck at the react-native bundling phase, so I thought I'd try here.  If you think I should file an issue in the `react-native-code-push` or a similar repository instead, please let me know.

### Environment

I'm on `macOS Mojave v10.14.5`.

`$ react-native --version`:

```
react-native-cli: 2.0.1
react-native: 0.59.10
```

`$ appcenter --version`:

```
appcenter version 1.1.20
```

**Comment by owenniblock** [comment]
Could you try adding 2 `extra-bundler-option` tags? I can't see any reason why this wouldn't be working in the code but it would verify if it's treating the whole entry as a single parameter (as it appears to be).

> --extra-bundler-option="--config"  --extra-bundler-option="$PWD/rn-cli.config.js"

**Comment by owenniblock** [comment]
@wbrickner were you able to try this?

**Comment by amchew** [comment]
Hey @wbrickner, I'll be closing this issue as there's no reply. Feel free to re-open this if you have other questions!
