### ISSUE TITLE
Add "store" to the valid destinations of "appcenter distribute releases add-destination"

### ISSUE THREAD

**Issue by N7K4** [microsoft/appcenter-cli#618]
When I am using the command:
`
appcenter distribute releases add-destination -r 123456 -t store -d Beta --app company/product
`
I get an error:
`
Error: store is not a valid destination type. Available types are: group, tester
`

Why **store** is not a valid destination? On the Web-UI I can do the step, of course the google play store is linked to my app inside appcenter.

See also: https://github.com/microsoft/appcenter-cli/issues/592#issuecomment-513771485

**Comment by jpeg-ms** [comment]
Hi @N7K4, thanks for your request. We are now working on this.

**Comment by jpeg-ms** [comment]
This has been implemented, and is part of release v2.2.0.
