### ISSUE TITLE
FAQ: Appium - The "test-classes" directory inside Appium build directory "target/upload" must contain at least one "*.class" file

### ISSUE THREAD

**Issue by minhnguyenwp** [microsoft/appcenter-cli#639]
My project is react native.

1. mvn -DskipTests -P prepare-for-upload package -> **BUILD SUCCESS**
2. RUN: **appcenter test run appium --app** ... 
i got this error: 
`The "test-classes" directory inside Appium build directory "target/upload" must contain at least one "*.class" file` 
view this image. 
![appcenter-test](https://user-images.githubusercontent.com/14305088/64235691-1551d400-cf23-11e9-86f9-c32cdc24ef9b.jpg)

What's wrong in my step, i just follow appcenter in "Test > Test runs" menu

**Comment by Rishivanthya** [comment]
Getting same error

**Comment by phillipleblanc** [comment]
@minhnguyenwp @Rishivanthya - This error looks like your test project wasn't compiled properly. I see in your build command that you specified "-DskipTests" - can you try building without that flag?

**Comment by phillipleblanc** [comment]
Closing as there hasn't been a response for a while - if this is still an issue, please re-open.

**Comment by Surajrock011** [comment]
Facing same issue.. have tried with solution

**Comment by Surajrock011** [comment]
write the test cases in test scope area..
