### ISSUE TITLE
Upload Android mapping files without specifying version code / version name

### ISSUE THREAD

**Issue by philemonmerlet** [microsoft/appcenter-cli#644]
We can successfully upload our Android app builds on AppCenter automatically, by running the appcenter-cli from a script. However, when we try to upload the corresponding mapping files (`crashes upload-mappings`) , we have to provide the app version name / version code. There are ways to get this information automatically from a random apk, however this adds a lot of work and complexity into our script. Why can't we just upload the mapping file to the "current" release ? (as it is done when uploading ios or native symbols I guess)

Possible solutions :
- Make versionName / versionCode optional, and map the file to the "current" release if not provided
- Allow to pass the mapping file as an additional parameter when running the upload release command

**Comment by ahdbilal** [comment]
Thanks @philemonmerlet. We will definitely be considering this in our next iteration.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
