### ISSUE TITLE
Setting Environment variables for queue

### ISSUE THREAD

**Issue by RuudBurger** [microsoft/appcenter-cli#645]
Is it possible to pass Environment variables to the queue?

Doing `appcenter build queue --branch develop` queues it just fine, but I would like to build an app connecting it to more then 1 backend. `appcenter build queue --branch develop --variables "API=http://test.example.com/api API_KEY=xxx"` and again `appcenter build queue --branch develop --variables "ENV=http://acceptance.example.com/api API_KEY=xxx"`. From there a build script can pick it up and attach the proper api urls & keys in the app.

Could also be solved with multiple build configurations like mentioned here https://github.com/microsoft/appcenter/issues/1010

**Comment by jpeg-ms** [comment]
Hi @RuudBurger, it looks to me like this is a feature request for App Center, similar to the one you mentioned (microsoft/appcenter#1010). For now, the environment variables used for build are set in the branch configuration, and this is not something the CLI could offer you at this point.

**Comment by runlevel5** [comment]
@amchew @jp-andre I would like to follow up on the progress of this feature. To us, it is one of the most important feature that help our team integrate MS App Center with our build system.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
