### ISSUE TITLE
Azure Pipelines | Unknown argument --include-category

### ISSUE THREAD

**Issue by karthiksubramaniam** [microsoft/appcenter-cli#650]
I'm running a job (series of tasks including nuget restore, build & signing application) on Azure DevOps to build android application and Test (Xamarin.UITest) application through Appcenter.

Test runs fine, if I don't specify any arguments on "Additional options for run" on "Test with Visual Studio App Center" task. When I do that (--include-category LandingPage) task throws error saying:

`Error: Command 'test run manifest --manifest-path d:\a\12\a\AppCenterTest\manifest.json --app-path d:/a/12/b/Release/PUBLISH_PACKAGE_NAME_PHONE_ANDROID.PUBLISH_PACKAGE_NAME_PHONE_ANDROID.apk --app SampleApp/Android --devices 12345abcd --test-series DevOps --locale en_US --include-category LandingPage --quiet --token ***' failed with exception "Unknown argument --include-category"`

Same result for `--exclude-category` as well

What I'm missing?

[command works perfectly when I run `appcenter test run` from my local machine.]

**Comment by jamchengms** [comment]
I'm having the same issue. 

failed with exception "Unknown argument --exclude-category

Running visual studio app center task version 1.*

**Comment by karthiksubramaniam** [comment]
> I'm having the same issue.
> 
> failed with exception "Unknown argument --exclude-category
> 
> Running visual studio app center task version 1.*

make sure you're providing your `--include-category AppCenterTest` under **Prepare Tests** area not under **Run tests**. Additional Options under **Run Tests** have different purpose it seems.


Discussion on stackoverflow: [https://stackoverflow.com/questions/58099354/azure-pipelines-app-center-test-error-when-including-category]

**Comment by jamchengms** [comment]
Thanks  @karthiksubramaniam, that seemed to have solved the issue.

**Comment by phillipleblanc** [comment]
Looks like this issue has been resolved, so I'll close this issue - feel free to re-open if you are still facing this issue.

**Comment by prashanthvijayakumar** [comment]
Can you please share a working example? I tried providing the below option but still getting same error.
prepareOptions: '--include-category Test1'.
