### ISSUE TITLE
Allow to reach "appcenter distribute releases show" through app-secret

### ISSUE THREAD

**Issue by liszto** [microsoft/appcenter-cli#651]
Hello,
In AppCenter swagger documentation, you have this endpoint : 
`/v0.1/sdk/apps/{app_secret}/releases/{release_hash}`

From our side we never have the app_name from our app on the AppCenter (or HockeyApp before) but only the secret key (+ id on HockeyApp).

Currently it's not possible to call the command : 
appcenter distribute release with the app-secret but with the combination "owner-name/app-name" so we have to retrieve the app-name from somewhere.

We thought it could be possible with your cli system which is almost a mimic of what we can found on the swagger AppCenter endpoints.

So could it be possible to add this for your command to get informations about an app ? 
Instead of `-a|-app` allow us to use something like `-s|secret`

Thanks !

**Comment by jpeg-ms** [comment]
Note that we currently don't have any public API that would allow us to translate a secret to the app slug.

**Comment by liszto** [comment]
@jpeg-ms I know but it would be a great improvement that would allow us to don't retrieve each time the ownername/appname combo. But maybe it's a system limitation for good reason but currently I don't get them :) 

I see you tag it as a "Need API Change" so you think its a relevant change ?

**Comment by jpeg-ms** [comment]
Until we have a more stable API where the app slug can not change, I believe using the app secret would indeed be very useful. So, yeah. 👍That being said, I can not make any promise at the moment.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
