### ISSUE TITLE
Allow new options for appcenter distribute releases list

### ISSUE THREAD

**Issue by liszto** [microsoft/appcenter-cli#663]
Hello guys,
could it be possible to add some options or maybe one option with different parameters to sort the list sent by `appcenter distributes releases list` ?
for example with a --sort optionnal parameter with value : date / release-id / version / ...

Cause currently I was doing this to retrieve the most recent uploaded release id : 

`appcenter distribute releases list -a "ORGNAME/APPNAME" | head -n 1 | sed 's/[^0-9]*//g'`

but this will return 84 in my case just because the result list order is messy like this : 

```
ID:            84
Short Version: 1.11.0
Version:       1.11.0
Uploaded At:   Thu Jul 04 2019 13:32:41 GMT+0200 (heure d'été d'Europe centrale)

ID:            83
Short Version: 1.11.0
Version:       1.11.0
Uploaded At:   Tue Jun 04 2019 18:10:58 GMT+0200 (heure d'été d'Europe centrale)

ID:            89
Short Version: 1.11.0.3
Version:       1.11.0.3
Uploaded At:   Tue Oct 01 2019 16:21:56 GMT+0200 (heure d'été d'Europe centrale)
```

It's really annoying to twist the appcenter-cli to do some things that seems quite basic, useful and easy to integrate on your side.

Thanks !

**Comment by phillipleblanc** [comment]
Thanks for opening this issue @liszto! We won't be able to work on this right away, but will leave this issue open to see what interest there is from the community on having this functionality.

**Comment by liszto** [comment]
Or at least if the sorting isn't a priority could it be possible to add something to retrieve the lastest release uploaded based on the release-id ? That was what I needed in fact but I had to make all the sorting stuff to retrieve the right one.

**Comment by kirktay** [comment]
Since there is no sorting in AppCenter this would be helpful

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
