### ISSUE TITLE
Add support for macOS .dmg files

### ISSUE THREAD

**Issue by jpeg-ms** [microsoft/appcenter-cli#670]
Since microsoft/appcenter#886, support for `.dmg` files was implemented in App Center. We now should support this in the `appcenter-cli`.
We should also verify support for `.pkg` and all WinForm, WPF files as well.

**Comment by jpeg-ms** [comment]
Well this has been implemented in #683

**Comment by JunielKatarn** [comment]
@jpeg-ms Please see #686 .
