### ISSUE TITLE
changing distribution group is not supported

### ISSUE THREAD

**Issue by joeldhenry** [microsoft/appcenter-cli#680]
Node Version 10.16.1
appcenter Version 2.2.1
 
`appcenter distribute release --file [omitted].apk --group [omitted] --app [omitted] --debug`

Debug Logs

```/ Creating release upload...Response status code: 201
| Finishing release upload...Response status code: 200
| Updating release details...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "[omitted]",
  "method": "PUT",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.1.1 NodeJS/v10.16.1 darwin/18.7.0",
    "x-api-token": "[omitted]"
  },
  "body": null
}
- Updating release details...Response status code: 400
Body: {"status":400,"name":"Error","message":"Missing required body parameter \"body\""}
Error: changing distribution group is not supported```

**Comment by arunshankar87** [comment]
I spent 3 hours today with this same thing. The error message is just wrong. Went through their swagger documentation and realized they have made the "Release notes" mandatory. So basically if you ran your command `appcenter distribute release --file [omitted].apk --group [omitted] --app [omitted] --debug **-r "Release notes mandatory"**`, it will work. The missing required body parameter that they have mentioned is the "release notes"

**Comment by jpeg-ms** [comment]
Hi there!

Sorry to hear that you've spent so much time because of this.
The release notes are not required (except for Apple's App Store). What happened is that the API was misbehaving for a while, it has now been reverted to its normal working state. I will close this ticket (and #681) as this is not actually a problem in the CLI.

Best regards.

**Comment by robertoandrade** [comment]
just noticed in my case when adding the `--debug` flag to identify any errors I do have a completely unrelated issue which seems fixable but the error message you get doesn't provide you the correct insights:

```
{"code":"two_factor_authentication_error","message":"Error in fetching the Apple service connection details for managing devices. apple connection is not valid for connectionId: 39bed04f-bce6-4128-bb85-9ccf00c23cdf"}
```
