### ISSUE TITLE
Missing release notes in distribute causes "Error: changing distribution group is not supported"

### ISSUE THREAD

**Issue by jjfmarket** [microsoft/appcenter-cli#681]
run command:
appcenter distribute release -f filename.ipa -g Collaborators --app Company/app

Shows the error message: 
Error: changing distribution group is not supported

Truthfully, the issue was resolved by adding --release-notes flag to the command. Expected that the error message reflect the actual issue that occurred.

**Comment by waxym** [comment]
Same issue here and "solved" using release note too.

Just updated from appcenter-cli 2.1.1 to appcenter-cli 2.2.1.
It was fine with 2.1.1 so I guess release note is not fully mandatory ?

Would appreciate to get more precise error message please.

**Comment by jpeg-ms** [comment]
Hi there!

As mentioned in the other ticket:
> The release notes are not required (except for Apple's App Store). What happened is that the API was misbehaving for a while, it has now been reverted to its normal working state. I will close this ticket (and #681) as this is not actually a problem in the CLI.

Best regards.
