### ISSUE TITLE
Can't upload DMG

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/appcenter-cli#686]
Steps to reproduce:
```
appcenter.cmd distribute groups publish -g <group name> -f <path to DMG>  -r <notes> --build-version <valid version> -a <owner>/<app name> --token <API token>
```

I get the following error:
```
Error: --build-version and --build-number must both be specified when uploading .dmg files
```

If I add `--build-number`, then I get:
```
Error: Command 'distribute groups publish -g X -f Y.dmg -r Z --build-version V -a O/A --token T --build-number N' failed with exception "Unknown argument --build-number"
```

How can I correctly upload a DMG to App Center?
It is certainly doable using the website.

**Comment by jpeg-ms** [comment]
Hi!
You're right, this is something we missed and we only realized it afterwards. You can currently use the following command instead:
`appcenter distribute release [...] --build-number NUM --build-version VERSION`
A quick PR is on its way to fix the command you were trying to use.
