### ISSUE TITLE
release-react ios plist parsing error

### ISSUE THREAD

**Issue by sankar4n** [microsoft/appcenter-cli#689]
release-react - fails with failed with exception "The "CFBundleShortVersionString" key in the "ios/Project/Info.plist" file needs to specify a valid semver string, containing both a major and minor version (e.g. 1.3.2, 1.1).

[Current plist parsing logic written here](https://github.com/microsoft/appcenter-cli/blob/master/src/commands/codepush/lib/react-native-utils.ts#L80) is failing on xcode 11 beause xcode is persisting the version details in .pbxproj file and exposing it through env for Info.plist. That means Info.plist will not be updated when we change version in xcode from general tab.

[This SO answer](https://stackoverflow.com/a/58327335/1198882) seems to be a potential solution.

**Comment by DmitriyKirakosyan** [comment]
fixed by https://github.com/microsoft/appcenter-cli/pull/751
