### ISSUE TITLE
How to clone build config from master to my branch via CLI?

### ISSUE THREAD

**Issue by vitalykarasik** [microsoft/appcenter-cli#690]
I'm triggering Acc Center from Jenkins using appcenter CLI.
How I can clone build configuration from master or another branch to the current branch?

TIA,
Vitaly

**Comment by vitalykarasik** [comment]
@phillipleblanc, does "feature-request" label mean that this isn't implemented yet?

**Comment by phillipleblanc** [comment]
@vitalykarasik - That is correct. This functionality is available in the App Center Portal, but not in the CLI.

**Comment by shrikanthkr** [comment]
@phillipleblanc Any workarounds on this feature?  If we rely totally on app center this actually breaks the progress for setting up the CI

**Comment by jphilipstevens** [comment]
I would love to have this setup as well. For my use case, I think it would make sense to clone and modify. for example, my team clones a feature branch from develop but we do not want to distribute off a feature branch

**Comment by tunegov** [comment]
Any progress on this feature?

**Comment by OffensivelyBad** [comment]
+1 on this feature request! Currently we have to configure every branch manually in the web app, whereas with other build systems branches can build automatically on push by having a shared configuration being applied to each new branch.

**Comment by Jamminroot** [comment]
Hey folks, thanks for reaching out to us, and I apologise for such a big delay in response.

App Center is currently in maintenance mode, meaning no new features are going to be prioritised up until mid-2021 ([Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap)):
> Therefore, as we look to what is next, the App Center team will prioritize improving reliability and performance for the service through mid-2021. This means new feature work will be significantly reduced.

There is no ETA we can provide yet, but once there is an update - we'll keep you guys posted here, in a thread.

**Comment by darioajr** [comment]
Use AppCenter API

`#!/bin/bash

OWNER_NAME="XXXXXXX"
APP_NAME_IOS="XXXXXXXXXXX"
APP_NAME_ANDROID="XXXXXXXXXXXXXX"
NEW_BRANCH=`echo $BITBUCKET_BRANCH | sed 's/\//\%2f/g'`
CLONE_BRANCH="release%2F2.4.0"
IOS_TOKEN=XXXXXXXXXXXXXXXXXXXXXXX
ANDROID_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXX

####Clone iOS build 
if ! curl -X GET "https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME_IOS/branches/$NEW_BRANCH/config" -H  "accept: application/json" -H  "X-API-Token: $IOS_TOKEN" | grep "404 Not Found" > /dev/null
then
   curl -X POST "https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME_IOS/branches​/$NEW_BRANCH​/config" -H  "accept: application/json" -H  "X-API-Token: $IOS_TOKEN" -H  "Content-Type: application/json" --data '{"cloneFromBranch": "$CLONE_BRANCH"}'
   echo "AppCenter iOS build cloned successfully"
fi

####Clone Android build 
if ! curl -X GET "https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME_ANDROID/branches/$NEW_BRANCH/config" -H  "accept: application/json" -H  "X-API-Token: $ANDROID_TOKEN" | grep "404 Not Found" > /dev/null
then
   curl -X POST "https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME_ANDROID/branches​/$NEW_BRANCH​/config" -H  "accept: application/json" -H  "X-API-Token: $ANDROID_TOKEN" -H  "Content-Type: application/json" --data '{"cloneFromBranch": "$CLONE_BRANCH"}'
   echo "AppCenter Android build cloned successfully"
fi`

**Comment by darioajr** [comment]
> Use AppCenter API
> 
> ```
> 
> OWNER_NAME="XXXXXXX"
> APP_NAME_IOS="XXXXXXXXXXX"
> APP_NAME_ANDROID="XXXXXXXXXXXXXX"
> NEW_BRANCH=`echo $BITBUCKET_BRANCH | sed 's/\//\%2f/g'`
> CLONE_BRANCH="release%2F2.4.0"
> IOS_TOKEN=XXXXXXXXXXXXXXXXXXXXXXX
> ANDROID_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXX
> 
> ####Clone iOS build 
> if ! curl -X GET "https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME_IOS/branches/$NEW_BRANCH/config" -H  "accept: application/json" -H  "X-API-Token: $IOS_TOKEN" | grep "404 Not Found" > /dev/null
> then
>    curl -X POST "https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME_IOS/branches​/$NEW_BRANCH​/config" -H  "accept: application/json" -H  "X-API-Token: $IOS_TOKEN" -H  "Content-Type: application/json" --data '{"cloneFromBranch": "$CLONE_BRANCH"}'
>    echo "AppCenter iOS build cloned successfully"
> fi
> 
> ####Clone Android build 
> if ! curl -X GET "https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME_ANDROID/branches/$NEW_BRANCH/config" -H  "accept: application/json" -H  "X-API-Token: $ANDROID_TOKEN" | grep "404 Not Found" > /dev/null
> then
>    curl -X POST "https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME_ANDROID/branches​/$NEW_BRANCH​/config" -H  "accept: application/json" -H  "X-API-Token: $ANDROID_TOKEN" -H  "Content-Type: application/json" --data '{"cloneFromBranch": "$CLONE_BRANCH"}'
>    echo "AppCenter Android build cloned successfully"
> fi````
> ```

Need replace strings in branch name, change "/" to "%2f" and others non url friendly

**Comment by christhoval06** [comment]
```
#!/usr/bin/env bash

# Reference App Center API
# https://openapi.appcenter.ms/#/

OWNER_NAME="xxxxxx"
APP_NAME_IOS="xxxxxx"
APP_NAME_ANDROID="xxxxxx"
NEW_BRANCH=$(echo $BITBUCKET_BRANCH | sed 's/\//\%2f/g')
CLONE_BRANCH="xxxxxx"
IOS_TOKEN=xxxxxx
ANDROID_TOKEN=xxxxxx

# Colors
# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
# Reset
Color_Off='\033[0m' # Text Reset

# Regular Colors
Yellow='\033[0;33m' # Yellow

# Bold
BRed='\033[1;31m'   # Red
BGreen='\033[1;32m' # Green

function clone_build {
  local branch=$1
  local os=$2
  local owner=$3
  local app=$4
  local token=$5
  local to_clone=$6

  echo "${Yellow}Validating if config ${branch} to ${os} is currently defined${Color_Off}"
  # if ! curl -X GET "https://api.appcenter.ms/v0.1/apps/$OWNER_NAME/$APP_NAME_IOS/branches/$NEW_BRANCH/config" -H  "accept: application/json" -H  "X-API-Token:$IOS_TOKEN" | grep "404 Not Found" > /dev/null
  if [ "$(curl -sL -w "%{http_code}" -X GET "https://api.appcenter.ms/v0.1/apps/${owner}/${app}/branches/${branch}/config" -H "accept: application/json" -H "X-API-Token:${token}" -o /dev/null)" = 200 ]; then
    echo "${BGreen}AppCenter ${os} build ${branch} is currently defined${Color_Off}"
  else
    if [ "$(curl -sL -w "%{http_code}" -X POST "https://api.appcenter.ms/v0.1/apps/${owner}/${app}/branches/${branch}/config" -H "accept: application/json" -H "X-API-Token:${token}" -H "Content-Type: application/json" -d "{\"cloneFromBranch\": \"${to_clone}\"}" -o /dev/null)" = 200 ]; then
      echo "${BGreen}AppCenter ${os} build cloned ${branch} successfully${Color_Off}"
    else
      echo "${BRed}AppCenter ${os} build cloned ${branch} failed${Color_Off}"
    fi
  fi
}

####Clone iOS build
clone_build "$NEW_BRANCH" "iOS" "$OWNER_NAME" "$APP_NAME_IOS" "$IOS_TOKEN" "$CLONE_BRANCH"

####Clone Android build
clone_build "$NEW_BRANCH" "Android" "$OWNER_NAME" "$APP_NAME_ANDROID" "$ANDROID_TOKEN" "$CLONE_BRANCH"
```

**Comment by darioajr** [comment]
To start the build after that you create, you can use appcenter-cli.

   ```appcenter build queue --app $APPCENTER_OWNER_NAME/$APPCENTER_APP_NAME_IOS -b $BITBUCKET_BRANCH --token "$APPCENTER_IOS_TOKEN"```

   ```appcenter build queue --app $APPCENTER_OWNER_NAME/$APPCENTER_APP_NAME_ANDROID -b $BITBUCKET_BRANCH --token "$APPCENTER_ANDROID_TOKEN"```

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
