### ISSUE TITLE
[React-native] Purpose of compose-source-maps.js?

### ISSUE THREAD

**Issue by blueberry6401** [microsoft/appcenter-cli#694]
When building Android with react-native using Hermes, I notice that in the build file run compose-source-maps.js as seen here:
https://github.com/facebook/react-native/blob/1fb815ed4314c1396999e64354ca0b5d4ed83663/react.gradle#L199
Codepush currently doesn't run this.

At this time, to make my Bugsnag to work, I have to run this command manually after bundled by codepush.
I don't know the purpose of this command but I decided to create this issue as a question: should this be handled by Codepush after generating source map?

**Comment by motiz88** [comment]
Hi, the author of `compose-source-maps.js` here :)

This script merges two inputs:
* Source map from Hermes bytecode → bundled JS, produced by the Hermes compiler
* Source map from bundled JS → JS source files, produced by the Metro bundler (or another bundler)

into a single output:
* Source map from Hermes bytecode -> JS source files

Using the composed source map, services like Bugsnag can symbolicate/unminify stack traces produced by apps running Hermes bytecode.

As @blueberry6401 pointed out, this is all set up out of the box in the default Gradle release build for React Native apps that use Hermes. I don't know much about the specifics of CodePush, but if it manages its own bundling process and supports Hermes, it likely should run `compose-source-maps.js` as well.

**Comment by phillipleblanc** [comment]
@motiz88 - Thanks for your input!

@blueberry6401 - Does the response above answer your question?

**Comment by yujincat** [comment]
Closing this issue as no longer response.

**Comment by tom-sherman** [comment]
@blueberry6401 I came here from intense searching, trying to figure out our problem. We're seeing weird things in bugsnag after upgrading to hermes, specifically a message that sourcemaps couldn't be applied to some frames - frames such as `/tmp/hermes/staging/hermes/cmake/intlRelease/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16`

Can you elaborate on what you were seeing when you refer to making bugsnag work?

**Comment by motiz88** [comment]
@tom-sherman, AFAICT that message is correct since the `InternalBytecode.js` frames are internal to the Hermes runtime and not represented in the source map.
