### ISSUE TITLE
--test-parameter not adding environment variables

### ISSUE THREAD

**Issue by cocowalla** [microsoft/appcenter-cli#697]
I'm running Xamarin.Forms tests in App Center, and I want to know in the running application when it is running in App Center Test.

According to the [docs](https://docs.microsoft.com/en-us/appcenter/test-cloud/environment-variables), an environment variable named `RUNNING_IN_APP_CENTER` should be available in the app - but it's _not_.

The docs also say you can specify additional environment variables available to the app, using:

```bash
appcenter test run <args> --test-parameter "app_env=MYVAR=1"
```

However, when using this, `MYVAR` is not available. I've also checked all variables by looping over `Environment.GetEnvironmentVariables` - definately not there.

Is this a known issue, or is there some other means to access these environment variables other than `Environment.GetEnvironmentVariable`?

**Comment by Ajaykn21** [comment]
Hi, Is this an Android app and which test framework you are using ?

**Comment by cocowalla** [comment]
Yes, it's Android, and I'm using Xamarin.UITest (should have mentioned that :smile:)

**Comment by Ajaykn21** [comment]
Apparently, if it is Android, then values are stored in `InstrumentationRegistry`.
can you please check

**Comment by phillipleblanc** [comment]
@cocowalla - Hey! Apologies for the lack of response so far, are you still facing this issue?

**Comment by yujincat** [comment]
Closing this issue as no longer response.
