### ISSUE TITLE
Codepush deployment does not exist

### ISSUE THREAD

**Issue by ssg-luke** [microsoft/appcenter-cli#698]
i've just switched over from using codepush-cli to using appcenter-cli and I'm finding that `codepush deployment` commands are failing. 

I am able to add one but running `appcenter codepush deployment history -a <app-name> NewDeployment` results in `Error: The deployment NewDeployment does not exist`. 

Attempting to list deployments with `appcenter codepush deployment list -a <app-name>` results in `Note: To display deployment keys add -k|--displayKeys option. Error: Failed to get list of deployments for the app`. If i add the `-k` switch then it does display the deployments with keys. Any idea why its not working?

Edit: I notice that when it fails it fails on `Getting deployment releases metrics...`

Version: 2.3.0

**Comment by jstheoriginal** [comment]
We are having this issue as well.

Running with debug it shows this error:

```
| Getting CodePush releases metrics...Response status code: 400
Body: {"message":"OOM command not allowed when used memory > 'maxmemory'."}
```

**Comment by pfleidi** [comment]
This issue should have been resolved. Can you confirm that you're no longer getting these errors?

**Comment by jstheoriginal** [comment]
Confirmed it's working again. Thanks!

**Comment by pfleidi** [comment]
Awesome, thanks for confirming! I'm closing this issue for now but feel free to report a new one if you're experiencing any issues.

**Comment by christophermark** [comment]
Working perfectly @pfleidi - on both App Center and Code Push CLI tools.
Really appreciate the fix ❤️
