### ISSUE TITLE
Can't list deployments

### ISSUE THREAD

**Issue by christophermark** [microsoft/appcenter-cli#699]
I'm cross-posting this issue from the Code Push repo, as I'm having issues with both CLI tools: https://github.com/microsoft/code-push/issues/675

## Version
AppCenter CLI version `2.3.0`

## What is affected
```
appcenter codepush deployment list --app [app]
```

We're seeing a very high error rate when trying to list our deployments from the App Center CLI. We used to be able to retry a few times and get it to work, but now we only hit the message: 
```
Error: Failed to get list of deployments for the app 
```

![image](https://user-images.githubusercontent.com/6303781/68890032-186bfc00-06ec-11ea-9a15-2ba8be1850f4.png)

Perhaps a dupe of #698

**Comment by pho3nixf1re** [comment]
If you pass the command `--debug` you can see the actual API requests and responses. The error is in the metrics API. It is throwing a Redis out of memory error.

```
/ Getting CodePush deployments metrics...Response status code: 400
Body: {"message":"OOM command not allowed when used memory > 'maxmemory'."}
```

**Comment by cjonsmith** [comment]
Hey, we're aware of the issue and looking into it now. We'll let you know when we have more information. Thanks for reporting this issue!

**Comment by ribamarsantos** [comment]
Didn't hear anyone posting here but it seems we are back!!! 🎉 🎉 At least Checking here everything seems fine again. Could someone else confirm please ?

**Comment by pfleidi** [comment]
@ribamarsantos Yes. We just resolved an issue with our Redis cache. Please let us know if there are any other issues!

**Comment by christophermark** [comment]
❤️ Working really well. Thank you!

**Comment by alexkendall** [comment]
Getting this same error currently. I assume I should just wait for it to be resolved?

**Comment by hengkx** [comment]
+1

**Comment by dann95** [comment]
> If you pass the command `--debug` you can see the actual API requests and responses. The error is in the metrics API. It is throwing a Redis out of memory error.
> 
> ```
> / Getting CodePush deployments metrics...Response status code: 400
> Body: {"message":"OOM command not allowed when used memory > 'maxmemory'."}
> ```

is that the "code-push" cli? cause when i try passing --debug it says that this option does not exists.

**Comment by dann95** [comment]
+1 facing the same error here, but when try to release an app.
