### ISSUE TITLE
[feature request] Dry run option

### ISSUE THREAD

**Issue by ffflorian** [microsoft/appcenter-cli#701]
I'd like to have a dry run option or flag to be able to test my settings without actually uploading something.

**Comment by ahdbilal** [comment]
Thanks @ffflorian for the request. We will be adding this to the feature requests backlog and will consider it in the next iteration.

**Comment by MateusAndrade** [comment]
There is any update on this? 👀

**Comment by DmitriyKirakosyan** [comment]
Hi @MateusAndrade 

Thank you for bumping this thread.
This feature is clearly a nice-to-have, however we cannot provide any ETA at this moment due to other priorities.
Please check our [Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) for this year.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
