### ISSUE TITLE
npm install broken

### ISSUE THREAD

**Issue by dmcgill50** [microsoft/appcenter-cli#705]
Davids-MacBook-Air:~ dave$ npm install -g appcenter-cli
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@szmarczak%2fhttp-timer - User not found
npm ERR! 404
npm ERR! 404  '@szmarczak/http-timer@^1.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'got'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dave/.npm/_logs/2019-11-20T14_08_04_927Z-debug.log

**Comment by joabalea** [comment]
Could you try again and let us know if it persists? 
Are you using a private/cached repository? (`npm set registry https://registry.npmjs.org/`)

**Comment by ahdbilal** [comment]
Closing this because of no response. Feel free to create a new ticket if the issue still persists.
