### ISSUE TITLE
Details in Debug Mode

### ISSUE THREAD

**Issue by Baumchen** [microsoft/appcenter-cli#706]
Hi,

I'm currently trying to upload symbol files to App Center via the appcenter CLI. 
Is there a way to enable a more verbose mode? The "debug" parameter gives some details, but no specific failure reason.

```
appcenterCli/2.3.0
NodeJS/v12.13.0
```

I'm running
`appcenter crashes upload-symbols --symbol App.app.dSYM.zip --app org/appname --token [*******] --debug`

With the following output:
```
> Using appcenter-cli version: 2.3.0
> logFilter, request: {
>   "rawResponse": false,
>   "queryString": {},
>   "url": "https://api.appcenter.ms/v0.1/apps/org/appname/symbol_uploads",
>   "method": "POST",
>   "headers": {
>     "Content-Type": "application/json; charset=utf-8",
>     "user-agent": "appcenterCli/2.3.0 NodeJS/v12.13.0 darwin/18.7.0",
>     "x-api-token": "[*******]"
>   },
>   "body": "{\"symbol_type\":\"Apple\"}"
> }
> Response status code: 200
> Body: {"symbol_upload_id":"00568384-9843-1310-b0e0-b11cf2abbaaa","upload_url":"https://hogwartsprodsymbols02.blob.core.windows.net:443/hwprodapp-45c488bf-e900-4eab-8b85-40bd990101f6/upload-00568384-9843-1310-b0e0-b11cf2abbaaa...","expiration_date":"2019-11-21T16:49:16.690Z"}
> logFilter, request: {
>   "rawResponse": false,
>   "queryString": {},
>   "url": "https://api.appcenter.ms/v0.1/apps/org/appname/symbol_uploads/00568384-9843-1310-b0e0-b11cf2abbaaa",
>   "method": "PATCH",
>   "headers": {
>     "Content-Type": "application/json; charset=utf-8",
>     "user-agent": "appcenterCli/2.3.0 NodeJS/v12.13.0 darwin/18.7.0",
>     "x-api-token": "[*******]"
>   },
>   "body": "{\"status\":\"aborted\"}"
> }
> Response status code: 200
> Body: {"symbol_upload_id":"00568384-9843-1310-b0e0-b11cf2abbaaa","app_id":"45c488bf-e900-4eab-8b85-40bd990101f6","user":{"email":"someemail@email.com","display_name":"Ralf Sangl"},"status":"aborted","symbol_type":"Apple","symbols_uploaded":[],"origin":"User","file_name":"upload-2019-11-20T16-49-16Z.zip","file_size":0,"timestamp":"2019-11-20T16:54:28.342Z"}
> Error: failed to upload ZIP with symbols
```

The error message `failed to upload ZIP with symbols` doesn't help me to find the underlying reason. So it would be nice to get more details in `debug` mode.

Is there any option I can try?

Thanks!

Best,
Ralf

**Comment by jpeg-ms** [comment]
Hi, I don't know if this is related, but please use Node 10. For now the CLI does not support node 12.

**Comment by joabalea** [comment]
@Baumchen After you tried with node 10, could you also verify that your token is valid and that you have a collaborator role for the app you are trying to update the symbols too?
It seems that your error is related to a lack of permissions (401).

**Comment by Baumchen** [comment]
Hi, my main point here is not that it doesn't work - it does work with Node 10 but also with Node 12 every once in a while (with the same file). My main point is, that the error message is not helpful and I think there should be an option to get the actual debug output, when specifying the `debug` flag. 

There is more information logged, but it's not being shown:
https://github.com/microsoft/appcenter-cli/blob/master/src/commands/crashes/lib/azure-blob-upload-helper.ts#L26

So my main question remains: Is there some way to get more output, so that I could look into the actual issue.

@joabalea : As mentioned, it does work with multiple retries or on different machines with the same token, so I can rule out a permission error.

**Comment by jpeg-ms** [comment]
You can add the environment variable `DEBUG="appcenter-cli:*"` to have more debug traces than `--debug` gives. But this will not necessarily add debug for your specific request. Here's an example:
```
DEBUG="appcenter-cli:*" appcenter
```

This might give way too much output, so you can filter a bit more using:
```
DEBUG="appcenter-cli:commands:*" appcenter apps list
```

Is this what you are looking for?

**Comment by Baumchen** [comment]
> You can add the environment variable `DEBUG="appcenter-cli:*"` to have more debug traces than `--debug` gives. But this will not necessarily add debug for your specific request. Here's an example:
> 
> ```
> DEBUG="appcenter-cli:*" appcenter
> ```
> 
> This might give way too much output, so you can filter a bit more using:
> 
> ```
> DEBUG="appcenter-cli:commands:*" appcenter apps list
> ```
> 
> Is this what you are looking for?

Indeed, yes, thank you - maybe it would make sense to document this somewhere (or did I just not find it?).
So the underlying error is an EPIPE error. 
I suppose there's not much I can do except retry a couple of times in this case.

```
Body: {"symbol_upload_id":"00568318-...","upload_url":"https://hogwartsprodsymbols02.blob.core.windows.net:443/hwprodapp-...","expiration_date":"2019-11-29T09:14:30.988Z"}
2019-11-28T09:14:31.282Z appcenter-cli:commands:apps:crashes:upload-symbols Analyzing upload start request response status code
2019-11-28T09:20:04.799Z appcenter-cli:commands:apps:crashes:upload-symbols Failed to upload ZIP with symbols - Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
2019-11-28T09:20:04.799Z appcenter-cli:commands:apps:crashes:upload-symbols Uploading failed, aborting upload request
2019-11-28T09:20:04.799Z appcenter-cli:commands:apps:crashes:upload-symbols Finishing symbols uploading with desired status: aborted
2019-11-28T09:20:04.801Z appcenter-cli:util:apis:appcenter-client-credentials Getting token for request
2019-11-28T09:20:04.801Z appcenter-cli:util:apis:appcenter-client-credentials got token [*******] of type string
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/org_name/app_name/symbol_uploads/00568318-...",
  "method": "PATCH",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.3.0 NodeJS/v12.13.0 darwin/18.7.0",
    "x-api-token": "[*******]"
  },
  "body": "{\"status\":\"aborted\"}"
}
Response status code: 200
Body: {"symbol_upload_id":"00568318-...","app_id":"...","user":{"email":"...","display_name":"..."},"status":"aborted","symbol_type":"Apple","symbols_uploaded":[],"origin":"User","file_name":"upload-2019-11-28T09-14-30Z.zip","file_size":0,"timestamp":"2019-11-28T09:20:05.366Z"}
2019-11-28T09:20:05.499Z appcenter-cli:commands:apps:crashes:upload-symbols Analyzing upload end request response status code
Error: failed to upload ZIP with symbols
```

**Comment by jpeg-ms** [comment]
> > You can add the environment variable `DEBUG="appcenter-cli:*"` to have more debug traces than `--debug` gives. But this will not necessarily add debug for your specific request. [...]
> 
> Indeed, yes, thank you - maybe it would make sense to document this somewhere (or did I just not find it?).

I wrote #715 to address this lack of documentation.

> So the underlying error is an EPIPE error. [...]

You may indeed want to retry. We could also have better retry within the CLI itself. But this is another issue. Feel free to open another Issue to address that.

I will now close this Issue, as it was about debug logs.
