### ISSUE TITLE
Output the latest version of a deployment

### ISSUE THREAD

**Issue by SMJ93** [microsoft/appcenter-cli#707]
We are migrating from `code-push` to `appcenter codepush` and so far everything has gone smoothly! Good work with the docs 👍 

Is it possible to output the latest version of a deployment?

e.g. `v242` for deployment `Staging`? We did this using the old codepush api by running:

`code-push deployment history app/app-ios Staging --format json | grep -E 'label' | tail -1`

I've tried it with appcenter, but the format is very different...

**Comment by pfleidi** [comment]
Unfortunately, the JSON format that the `appcenter codepush` command is returning is not very friendly to be consumed by a shell script and there's definitely room for improvement. ;)

I think there are a few things you could solve this issue without a new release of the tool. One way would be to get the release history, grab the last element in the array of releases and select the first property which is the label:

```bash
appcenter codepush deployment history Staging --app $YOUR_APP --output json | jq '.[-1][0]'```

Another way would be to extract it from the `codepush deployment list` command:

```bash
appcenter codepush deployment list -app $YOUR_APP --output json | jq -c '.[] | select(.[0] == "Production") | .[1]' | sed -e 's/.*Label: \(v[0-9]*\).*/\1/'
```

While neither of these solutions is very elegant, it might help to unblock you for now. Let us know if this works for you.

**Comment by SMJ93** [comment]
Thanks @pfleidi that works perfectly!

**Comment by joshuapinter** [comment]
I would love to have this as well. I ended up doing something like this, which may be more brittle but it doesn't require `jq` to parse the JSON output: 

```bash
$ appcenter codepush deployment history Staging -a joshuapinter/app --output json | tail -8 | head -n1 | grep -o -E '(v[0-9]*)' | cut -c 2-
#=> 42
```

**Comment by DmitriyKirakosyan** [comment]
Hi @joshuapinter , thank you for bumping this feature request and for providing an improved workaround!

Can you confirm that this is the same feature request as https://github.com/microsoft/appcenter-cli/issues/777?
If it is so, I would like to close that one as a duplicate and reopen this one.

**Comment by joshuapinter** [comment]
Hi @DmitriyKirakosyan. #777 looks similar for sure. Not sure if it's identical but making it easy to get the latest version in a stable manner is useful for a bunch of things. Thanks.

**Comment by SMJ93** [comment]
I think the JSON output has changed as the scripts above no longer work for us.

This is the new script we use to fetch the latest codepush release version. We've change the regex to march the quotes with `"v[0-9]+"`. Then strip them out after:

```
# Get all codepush releases for the app and deployment
CODEPUSH_RELEASES="$(./node_modules/.bin/appcenter codepush deployment history -a $APP_CENTER_APP_NAME $DEPLOYMENT_NAME --output json)"

# Get the latest codepush release from the deployment history
LATEST_CODEPUSH_RELEASE_VERSION=$(echo $CODEPUSH_RELEASES | grep -o -E '("v[0-9]+")'| tail -n1 | tr -d '"')
echo "Latest codepush release version: $LATEST_CODEPUSH_RELEASE_VERSION"

# Outputs v23
```

**Comment by joshuapinter** [comment]
I just re-tested my script and it seems to work fine still.

```bash
appcenter codepush deployment history Staging -a joshuapinter/app --output json | tail -8 | head -n1 | grep -o -E '(v[0-9]*)'
#=> v42
```

Maybe you had a typo or something.

**Comment by SMJ93** [comment]
Have you done any rollbacks or promotions? 

In this scenario it returns `v41` instead of `v26` as it matches the `v41` from `Promoted v41 from Staging`:

```
 [ "v26", "Mar 29, 04:58 PM
(Promoted v41 from Staging)", "6.21.4", "Yes", "Collect null opening hours fixes", "Active: 23.3% (n of n)
Installed: n
Rollbacks: n" ]
```

**Comment by kopax-polyconseil** [comment]
Since we do not have a filter on `version` like with the deployment history http api, so we did this in our `Fastfile`:

```bash
npx appcenter codepush deployment history #{ENV['CODEPUSH_DEPLOYMENT_NAME']} -a #{ENV['APPCENTER_ORGANISATION']}/#{ENV['APPCENTER_IOS_APP_ID']} | grep \" ${VERSION} \" | tail -1 | awk -F ' ' '{print $2}'
```

It would be very welcome to have such feature.

**Comment by Dat-Mobile** [comment]
Definitely need some parameters for `appcenter codepush deployment list`

**Comment by lucifer-crybaby** [comment]
We need to get the latest version number in order to add git tag to our repo. Would be nice feature.

**Comment by DmitriyKirakosyan** [comment]
@lucifer-crybaby , please use the solution discussed above to parse json output.
We don't have plan to change the format within the next year, so I'm closing this issue.
