### ISSUE TITLE
cli is broken on node version 10.x.x

### ISSUE THREAD

**Issue by ebouJ** [microsoft/appcenter-cli#710]
I installed the cli with the following command : sudo npm i -g appcenter-cli 
The installation went well. If I run the command appcenter i got an error: appcenter is not a command

I followed this thread on SO and none of the solutions works for me. https://stackoverflow.com/questions/52894826/appcenter-cli-cant-be-installed-command-not-found

OS: macOS Mojave
node: 10.16.2

![75474194_853606805096283_2495822340567334912_n](https://user-images.githubusercontent.com/22877561/69467703-36bea100-0d57-11ea-8e7b-633a8b25cc42.png)

**Comment by ahdbilal** [comment]
@ebouJ: I am using node v12.13.0 with macOS Mojave without any issue. If it is not an issue for you, I will recommend upgrading to the latest node version. Let me know how it goes. Thanks

**Comment by ebouJ** [comment]
@ahdbilal thanks I got this issue resolved. It was an issue with npm I think. If I installed it using sudo it wasn't working for me. If I global install I have issues and it only works if I use sudo. So I tried to fix that issue and it resolved
