### ISSUE TITLE
Missing functionality - is posssible to add?

### ISSUE THREAD

**Issue by pawel757677** [microsoft/appcenter-cli#712]
Hi,
There is lack of two functions:
**1) create app for specific organization**

_example:_
curl --header "Content-Type: application/json" --header "X-API-Token:XXX-XXX" --request POST --data '{"display_name":"DISPLAY_NAME","name":"NAME","os":"Android","platform":"Java"}' https://appcenter.ms/api/v0.1/orgs/{ORGANIZATION}/apps

_solution:_
maybe add option to choose organization for "appcenter apps create" command?

**2) add distribution group**

_example:_
curl --header "Content-Type: application/json" --header "X-API-Token:XXX-XXX" --request POST --data '{"apps":[{"name":"NAME"}]}' https://appcenter.ms/api/v0.1/orgs/{ORGANIZATION}/distribution_groups/{DISTRIBUTION_GROUP}/apps

_solution:_

maybe command "appcenter distribute release -f APK_PATH -g {DISTRIBUTION_GROUP} --app {ORGANIZATION}/{NAME}" should has option to force add distribution group? cause now no working.

**Comment by jerietve** [comment]
Hi @pawel757677, thanks for your request.

Regarding 1, that sounds like a good idea to me. It could be done as you suggest and/or go under `appcenter orgs apps create`.

Regarding 2, the API you call in the example adds an app to a distribution group. The CLI example you write seems to add a distribution group to a release of an app, or to release an app to a distribution group. This is already possible, so perhaps I misunderstand what you want to do. If you want to add a distribution group to an existing release, you can use `distribute releases add-destination`. Please check whether that does what you want.

**Comment by pawel757677** [comment]
Thank you for your response!

Regarding 2. 
You are right, maybe i didn't explain well.
So maybe other example:

Situation: One app, many builds (releases)
So, first i create app (use API or CLI) and now if i run:

`appcenter distribute release -f $APK_PATH -g CustomDistributionGroup --app {ORG}/{NAME}`

Result:

`Error: Could not find group CustomDistributionGroup`

And you are right, i can use commands like this:

```
appcenter distribute release -f $APK_PATH --app {ORG}/{NAME}
LAST_RELEASE_ID=appcenter distribute releases list --app {ORG}/{NAME} | grep ID | head -1 | tr -s ' ' | cut -f2 -d ' '
appcenter distribute releases add-destination -a {ORG}/{NAME} -r $LAST_RELEASE_ID -t group -d CustomDistributionGroup -s
```

It works. But, if we first add an app to a distribution group:

`curl --header "Content-Type: application/json" --header "X-API-Token:XXX-XXX" --request POST --data '{"apps":[{"name":"NAME"}]}' https://appcenter.ms/api/v0.1/orgs/{ORG}/distribution_groups/CustomDistributionGroup/apps`

Then all we need in every next release is only:

`appcenter distribute release -f $APK_PATH -g CustomDistributionGroup --app {ORG}/{NAME}`

So, summarizing maybe add command to "add an app to a distribution group"?

**Comment by ahdbilal** [comment]
Thanks @pawel757677  for the request. We will be adding this to the feature requests backlog and will consider it in the next iteration.

**Comment by anywherepilot** [comment]
So to summarize, the request is to add two things:

- A CLI version of [create app for org](https://openapi.appcenter.ms/#/account/apps_createForOrg). Say `orgs apps create`.
- A CLI version of [add app to (org) distribution group](https://openapi.appcenter.ms/#/account/distributionGroups_addApps). Say `orgs groups add-app`.

These both do not exist at the moment and would certainly be useful. Org support in the CLI is rather limited. There is no way to do anything regarding org level groups (create, list, show, add/remove apps).

Making `distribute release` "just work" when providing the name of a distribution group which does not have the app added to it seems like a bad idea, let's not do that. It performs hidden permission operations.

**Comment by anywherepilot** [comment]
Another request #831 for this just appeared. Let's keep both, since this one concerns two issues.

**Comment by aleksandr-dorofeev** [comment]
Hello @grit96 
There is an update on your question which is related to the `--display-name` option for organisations. Unfortunately, we do not use this argument in the case of organisations, since it duplicates the meaning of the `--name` argument on the backend side. You can use this argument for a list of applications, but not through organisations. In this regard, adding this parameter to the CLI is not necessary.

**Comment by jphillips05** [comment]
Is there an update to this? I am also looking to add apps to a distribution list

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
