### ISSUE TITLE
`appcenter codepush release-react` does not handle monorepo

### ISSUE THREAD

**Issue by brandonpearcy** [microsoft/appcenter-cli#716]
Our monorepo uses yarn workspaces, and has a fairly standard layout:
```
/projectRoot
    /node_modules (most get installed here)
    /packages
        /app
        /shared
        /web
```

When running `release-react` in a monorepo the command fails with a none-too-helpful error message (see below). This command works as expected for releasing to iOS, but does not work for Android.

```
$ appcenter codepush release-react -a "$ANDROID_APP" -d Beta -t "0.1.1" --description="Just testing" --entry-file=packages/app/index.js
Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/jq/4ys69bn17876bf9sxgc6xvz40000gn/T/code-push2019112-44087-7vedqb.yw2wv/CodePush --bundle-output /var/folders/jq/4ys69bn17876bf9sxgc6xvz40000gn/T/code-push2019112-44087-7vedqb.yw2wv/CodePush/index.android.bundle --dev false --entry-file packages/app/index.js --platform android
Loading dependency graph, done.

info Writing bundle output to:, /var/folders/jq/4ys69bn17876bf9sxgc6xvz40000gn/T/code-push2019112-44087-7vedqb.yw2wv/CodePush/index.android.bundle
info Done writing bundle output
info Copying 49 asset files
info Done copying assets
Error: Failed to release a CodePush update.
```

Adding the `--debug` flag does not add any additional info.

I've been able to work around this by running `appcenter codepush release` on the intermediate bundled output of the `release-react` command, but this seems hacky and I'm not even sure its correct.

```
OUTPUT_DIR="/tmp"
$ appcenter codepush release-react -a "$APP" -d Production -t "$1" --description="$2" --entry-file=packages/app/index.js --output-dir="$OUTPUT_DIR"
$ appcenter codepush release -a "$APP" -d Production -t "$1" --description="$2" -c "$OUTPUT_DIR"
```

**Comment by ahdbilal** [comment]
Thanks for the note. We are looking into it. I will share more info once I have an update.

**Comment by tad3j** [comment]
I'm also having issue with getting cli (v2.4.0) release command working in a monoreporo setup (same folder structure as OP). When running `appcenter codepush release-react --app AppName/android` cli tool is not able to locate `node_modules` (which in monorepo case is usually located in the **root of monorepo** and **not root of the react-native application**.

The output I get when running:

```
Running "react-native bundle" command:

node node_modules\react-native\local-cli\cli.js bundle --assets-dest C:\Users\Tadej\AppData\Local\Temp\code-push2020313-12184-85hs3u.ebk8\CodePush --bundle-output C:\Users\Tadej\AppData\Local\Temp\code-push2020313
-12184-85hs3u.ebk8\CodePush\index.android.bundle --dev false --entry-file index.js --platform android
internal/modules/cjs/loader.
js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\Tadej\WebstormProjects\my_project\packages\mobile\node_modules\react-native\local-cli\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Error: Failed to release a CodePush update.

```

Btw, for `react-native-code-push` I was able to work around same issue by setting `nodeModulesPath` inside `gradle.properties`.

**Comment by wmcbain** [comment]
@tad3j I'm doing the following:

1. Bundle the JavaScript from the package directory in the monorepo:

```
rm -rf codepush
mkdir codepush
cd {ROOT OF MONOREPO}
node node_modules/react-native/local-cli/cli.js bundle --platform ios --dev false --entry-file {PACKAGE_PATH}/index.js --bundle-output {PACKAGE_PATH}/codepush/main.jsbundle --assets-dest {PACKAGE_PATH}/codepush
```

2. Then releasing it with the `release` command instead of `release-react`:

```
appcenter codepush release -d Staging -a {APP_NAME} -c ./codepush
```

Hope this helps.

**Comment by tad3j** [comment]
@wmcbain , thank's, will try it out. Bellow is my solution, which let's met run a batch file from repository root:
```
REM workaround
cd packages\mobile
mv node_modules node_modules_tmp
mklink /D node_modules ..\..\node_modules
REM CODE-PUSH for staging
call yarn code-push:android-staging
REM CLEANUP
rm node_modules
mv node_modules_tmp node_modules
cd ..\..
```

**Comment by kennym** [comment]
> @tad3j I'm doing the following:
> 
> 1. Bundle the JavaScript from the package directory in the monorepo:
> 
> ```
> rm -rf codepush
> mkdir codepush
> cd {ROOT OF MONOREPO}
> node node_modules/react-native/local-cli/cli.js bundle --platform ios --dev false --entry-file {PACKAGE_PATH}/index.js --bundle-output {PACKAGE_PATH}/codepush/main.jsbundle --assets-dest {PACKAGE_PATH}/codepush
> ```
> 
> 1. Then releasing it with the `release` command instead of `release-react`:
> 
> ```
> appcenter codepush release -d Staging -a {APP_NAME} -c ./codepush
> ```
> 
> Hope this helps.

Thanks - this worked for my monorepo approach!

**Comment by mertbo** [comment]
in my case, `mobile` directory is inside `packages` directory. 

`cd` into `mobile` directory then provide only `-e` flag to `appcenter codepush` CLI. e.g. `appcenter codepush release-react -a OWNER_NAME/APP_NAME -d Production -m -e $PWD/index.js`

This worked well.

**Comment by disko998** [comment]
`appcenter codepush release -d Staging -a {APP_NAME} -c ./codepush`

This requires -t or --target-binary-version. How do i find the current version of the app programmatically
 from the root of the workspace?

**Comment by alexnekrashevich** [comment]
Hi @disko998, have you tried this?
```
appcenter analytics app-versions --app {APP_NAME}
```

Or please check this endpoint in AppCenter API (which is used by the CLI command above): https://openapi.appcenter.ms/#/analytics/Analytics_Versions

Please let us know if this helps.

**Comment by OkancanCosar** [comment]
run inside  /app directory

```js
rm -rf CodePush
mkdir CodePush

# create js source bundle
npx react-native bundle \
--entry-file=./index.js \
--bundle-output=./CodePush/index.android.bundle \
--assets-dest=./CodePush/ \
--dev=false \
--platform=android

# send codepush
appcenter codepush release \
-a XYZ/APPNAME \
-c ./CodePush \
-d Production \
-t 0.0.x
``
