### ISSUE TITLE
Command not found after installing appcenter-cli

### ISSUE THREAD

**Issue by konjoinfinity** [microsoft/appcenter-cli#719]
https://github.com/microsoft/appcenter-cli/issues/497

I'm also having the same issue...

Node 11.6.0
Appcenter CLI 2.3.2
Npm 6.5.0
Zsh 5.3
Mac OS Mojave 10.14.6

Tried other workarounds as well to no avail:

- Setting the java path various ways in the bash profile
- Adding a path to appcenter.js file
- Uninstalling and reinstalling
- Restarting workstation
- Closing out of all terminal/bash sessions after changes to paths or installs
- Installing with and without the sudo command
- Installing webpack via npm
- Attempted using regular bash as well

Does anyone have a solution for this issue?

zsh
```
 ~ sudo npm install -g appcenter-cli
Password:
/usr/local/Cellar/node/11.6.0/bin/appcenter -> /usr/local/Cellar/node/11.6.0/lib/node_modules/appcenter-cli/bin/appcenter.js

> fast-xml-parser@3.15.1 postinstall /usr/local/Cellar/node/11.6.0/lib/node_modules/appcenter-cli/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.

npm WARN webpack-cli@3.3.10 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.

+ appcenter-cli@2.3.2
added 493 packages from 437 contributors in 16.539s
➜  ~ appcenter
zsh: command not found: appcenter
➜  ~ appcenter help
zsh: command not found: appcenter
```

bash
```
new$ appcenter
bash: appcenter: command not found
```

bash_profile
```
export JAVA_HOME=$(/usr/libexec/java_home)
```

**Comment by jpeg-ms** [comment]
It appears that you are using macOS and node without `nvm`. The issue here is that the following file is not in your PATH:
```
/usr/local/Cellar/node/11.6.0/bin/appcenter
```

Please add this to your `PATH` environment variable and this should work.
The problem seems to be linked to `npm` as this path should be in your PATH. Is `node` in your PATH (i.e. what happens when you try to run just `node`?).

For information we usually use nvm but if this issue persists we will have to check further.

**Comment by phillipleblanc** [comment]
@konjoinfinity - I'm assuming the instructions given above worked for you, so I will close this issue. If not, feel free to re-open.
