### ISSUE TITLE
appcenter cmd Error: self signed certificate in certificate chain 

### ISSUE THREAD

**Issue by gualber98** [microsoft/appcenter-cli#722]
My company is under a proxy and I keep getting the self signed certificate issue.  
I am running under Windows, and the command is:

appcenter login --debug
Using appcenter-cli version: 2.3.3
Opening your browser...
? Visit https://appcenter.ms/cli-login?hostname=machineName and enter the code:
? Access code from browser:  <codeFromBrowser>
| Getting user info ...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/user",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.3.3 NodeJS/v10.16.0 win32/10.0.17134",
    "x-api-token": "<tokenFromBrowser>"
  },
  "body": null
}
/ Getting user info ...Error from response, message: self signed certificate in certificate chain
Error: self signed certificate in certificate chain

I have already try the following:

Setting environment variables are respected by request:
HTTP_PROXY / http_proxy
HTTPS_PROXY / https_proxy

Set NPM config to:
strict-ssl=true
proxy=<proxy_ur:port>

Any advice on how to solve this issue?

**Comment by ahdbilal** [comment]
Appcenter CLI doesn't run behind a corporate proxy server. This is a known feature gap in our product offering and a feature to provide this support is already in our backlog. Few of our customer have temporarily fixed this issue by enabling whitelist for the following addresses: https://intercom.help/appcenter/en/articles/1881230-urls-and-ip-addresses-to-whitelist-for-app-center

**Comment by souravguchait-udaan** [comment]
Any update on this?

**Comment by DmitriyKirakosyan** [comment]
Hi @souravguchait-udaan , thank you for bumping this thread!
Unfortunately, we don't have any ETA for this feature due to other priorities.

**Comment by souravguchait-udaan** [comment]
Suddenly my appcenter login is failing with Error: self signed certificate in certificate chain
when i am login using Access code from browser: XXXX..
Suddenly it started, any solve for it?

**Comment by souravguchait-udaan** [comment]
Any solve for this error? tried re-installing appcenter-cli, started today morning, was trying to add certificate to run localhost on https for our web application , post to that  code-push stopped working even appcenter login stopped working, totally unrelated not sure why it happened?Anyone any idea or a solve? Happening when i do "appcenter login"

**Comment by DmitriyKirakosyan** [comment]
@souravguchait-udaan Check if you have any firewall turned on. See https://github.com/microsoft/appcenter-cli/issues/1644/.

**Comment by souravguchait-udaan** [comment]
Firewall is turned off

**Comment by DmitriyKirakosyan** [comment]
The error means you have self signed certificate now participating in web requests. Please contact your admin or review your recently installed/updated software which might affect your connection configuration.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue. Please let me know if anyone is still facing it.
