### ISSUE TITLE
Codepush Cordova Incremental Update not working

### ISSUE THREAD

**Issue by earnzeemedia** [microsoft/appcenter-cli#724]
I'm using codepush to update HTML changes to the application. 
My application is around 99MB and every time I create a cordova-release by doing very minor changes the appcenter cli always uploads the entire 99MB zip to the app center servers. 
To my understanding, the incremental updates are suppose to be working in such a way that after a 99MB upload the App center server, any further updates should include only the modified files and not the entire files IMO and correct me if I'm wrong. 

The Command line I used to update.
`appcenter codepush release-cordova -d Production`

**Comment by earnzeemedia** [comment]
Upon further investigation, I understood that while code pushing the cli uploads the entire www directory to the servers. But while installing it to the user device it'll do some diffig and download only the modified files. 
But however during this process while checking the logcat I could see the device downloads the entire file zip from the server without doing the diffig magic. Is it only me or is it suppose to be working like that. I'm stuck.

**Comment by ahdbilal** [comment]
@earnzeemedia you are using the right cli command and if everything is set up correctly, differential updates should work (i.e even though the app code is uploaded on every update, the end users will only actually download the files they need). microsoft/code-push can provide more specific information on code-push. I am moving this issue there.
