### ISSUE TITLE
When I try to run xcui tests using Appcenter cli, I get that missing libraries or frameworks missing

### ISSUE THREAD

**Issue by mrityunjeyan** [microsoft/appcenter-cli#725]
Preparing tests... done.
Validating arguments... done.
Creating new test run... done.
Validating application file... done.
Uploading files... done.
Starting test run... failed.
Error: Invalid app: Missing libraries or frameworks for XCTest plugin ["/libswiftSwiftOnoneSupport.dylib"]

**Comment by genakir** [comment]
Hello @mrityunjeyan, how did you fix your issue?

**Comment by mohan1412** [comment]
I'm also seeing the same issue, How did you fix it?

**Comment by dvertovsek** [comment]
@MarcBiosca 
Hey where exactly did you add that line, could you give additional info ?

**Comment by MarcBiosca** [comment]
@dvertovsek in the project file, you can go to the build settings and add the LD_RUNPATH_SEARCH_PATHS in the search box in the UI, or toggle the code-mode to see it in plain text and search it there

**Comment by dvertovsek** [comment]
<img width="857" alt="Screen Shot 2022-04-09 at 6 51 35 PM" src="https://user-images.githubusercontent.com/11228615/162560453-cc414dfb-2f1a-4939-874b-51b7185e2c5f.png">

@MarcBiosca is this correct way of adding it ? With or without the quotation marks ?

**Comment by MarcBiosca** [comment]
@dvertovsek without them.
If I recall correctly it was to be put in the test target instead, but I guess it possibly makes the trick there where you have put it too as it will apply to all targets

**Comment by MarcBiosca** [comment]
@JoeGaggler
Side by side projects with build settings open and comparing one by one to try and spot differences… 😰
