### ISSUE TITLE
Allow appcenter distribute releases list to display unpublished release

### ISSUE THREAD

**Issue by Jerome91410** [microsoft/appcenter-cli#727]
Hello guys,

I'm facing problem, I tried to fetch all releases associated to an app through:
`appcenter distribute releases list --app XXX/YYY`
The result is an empty array.
```
Using appcenter-cli version: 2.1.0
| Loading list of releases...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/XXX/YYY/releases?published_only=true",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.1.0 NodeJS/v10.15.3 darwin/19.2.0",
    "x-api-token": "...."
  },
  "body": null
}
- Loading list of releases...Response status code: 200
Body: []
```
When i use the web 'https://appcenter.ms/orgs/XXX/apps/YYY/distribute/releases', i got the full list.
```
curl 'https://appcenter.ms/api/v0.1/apps/XXXX/YYYY/releases' -H 'x-api-token: ...'

[{"origin":"appcenter","id":1,"short_version":"1.6.0","version":"70","uploaded_at":"2020-01-02T16:18:48.000Z","enabled":true,"is_external_build":false}]⏎
```
So could you tell my why the cli is restricted to the 'published_only' release?
Is there a way to add an option to be able to fetch all releases using the cli?

thanks

**Comment by phillipleblanc** [comment]
@Jerome91410 - What is the scenario for needing the unpublished releases? The App Center CLI currently only supports fetching published releases.

**Comment by Jerome91410** [comment]
@phillipleblanc I expected to use it in my CD process.
When I release feature, my CI check if the build already exists, if not the CI has to build the iOS/Android releases and publish them on appcenter

- ios build time: ~20min
- android build time: ~10min

**Comment by michel-moreau** [comment]
We would love to have that feature as well!
We are using the CLI from our CI/CD to identify old releases and remove them from AppCenter. At this point we are unable to list unpublished releases :-(
