### ISSUE TITLE
appcenter cli couldn't read the $(MARKETING_VERSION) environment variable of the key 'CFBundleShortVersionString' in info.plist

### ISSUE THREAD

**Issue by rainrainrainrain1997** [microsoft/appcenter-cli#729]
### **Description**

it's seems like after I updated my Xcode, the key 'CFBundleShortVersionString' in my info.plist has been changed from version code(e.g. 1.1.3) to $(MARKETING_VERSION). And when I release a update without a target version. the console outputs a error like -- Error: Command 'xxx' failed with exception "The "CFBundleShortVersionString" key in the "iOS/xxx/Info.plist" file needs to specify a valid semver string, containing both a major and minor version (e.g. 1.3.2, 1.1)."

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. update Xcode
2. release a update  without target version parameter

### **Details**

1. Which version of the App Center SDK are you using?
    - 2.3.3
2. Which OS version did you experience the issue on?
    - iOS 13
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone X physical device
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`

System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 124.58 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 26, 27, 28, 29
      Build Tools: 26.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-update-cli: 0.1.0

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.8.4

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

**Comment by jp-andre** [comment]
I believe this is fixed by #751
