### ISSUE TITLE
Just update provisioning profile without uploading a new build

### ISSUE THREAD

**Issue by gannonbarnett** [microsoft/appcenter-cli#731]
In the online dashboard it is possible to just update the provisioning profiles associated with a build without uploading an entirely new build. Is there a way to do this from the command line/ api?

**Comment by phillipleblanc** [comment]
@gbarnett - I'm not sure I understand your scenario. Are you talking about this: https://docs.microsoft.com/en-us/appcenter/distribution/auto-provisioning#re-signing-capabilities ?

Nothing like that exists for the CLI today.

**Comment by gbarnett** [comment]
Yes. I ended up creating my own interface with other endpoints of AppCenter API to achieve this from the command line. I think this would be a useful feature for this repo to have as resigning is a common need for many app-based companies; resigning manually, especially if the app has multiple profiles, can be annoying.

**Comment by fbmiranda7** [comment]
Can you tela more about this implementation and which endpoints you used? I’m working with multiple apps but same distribution group, if there was a way to update all builds with the se provisioning would be awesome.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
