### ISSUE TITLE
Cannot clear release history

### ISSUE THREAD

**Issue by alexp25** [microsoft/appcenter-cli#732]
I am using the following command to remove all code push update history for an app (as described in docs).

```appcenter codepush deployment clear -a <app-name> Staging```

The CLI hangs indefinitely:

![Capture](https://user-images.githubusercontent.com/17313098/72531170-975eeb80-3879-11ea-9482-865a47aac483.PNG)

How can this still be achieved?

**Comment by yujincat** [comment]
Hi! Thanks all for reporting this issue, and apologies for the late reply.

We tried to repro the issue with appcenter version 2.4.0 and found the following problems : 
- When clearing deployment name that exists, the command exits.
- When clearing deployment name that does not exist, the command hangs.

@alexp25 Can you identify if this is your case?

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
