### ISSUE TITLE
Missing comprehensive documentation

### ISSUE THREAD

**Issue by sewil** [microsoft/appcenter-cli#733]
The CLI is missing usage examples and comprehensive documentation for what arguments and options that can be provided to the commands as well as configuration instructions for setting the current app.

**Comment by jerietve** [comment]
Most 'documentation' of the CLI is in the CLI itself and accessible through the `appcenter help` command. There are no examples and you are not really pointed toward setting the current app anywhere. We'll consider your feature request. I just want to make sure you know the `help` command exists, as it gets you started.

Set the current app using `appcenter apps set-current`. Run `appcenter help apps set-current` to learn (a little bit) more.
