### ISSUE TITLE
Passing parameters from appcenter to iOS app being tested in appcenter.

### ISSUE THREAD

**Issue by BicycleMark** [microsoft/appcenter-cli#736]
Hello I have a Xam Forms 4.x app that takes command line parameters and processes them well to the effect of doing some 'on device file' manipulation

how do I setup the appcenter app portal to insert and add the command line apps?

here is my override in App.Xaml.cs

 protected override async void OnInitialized()
        {
            InitializeComponent();
            await StartupTasks();
            if (Environment.CommandLine.Contains("EXTRACT_TEST_DATA"))
            {
                ExtractTestData();
            }

            else if (Environment.CommandLine.Contains("REMOVE_TEST_DATA"))
            {
                RemoveTestData();
            }
            await NavigationService.NavigateAsync("MainPage/NavigationPage/OfficerSelectionPage");
        }

**Comment by phillipleblanc** [comment]
@BicycleMark - I'm not sure I understand what scenario you are trying to accomplish. Which CLI command are you running that isn't working?

**Comment by yujincat** [comment]
Closing this issue as the thread has been inactive for a month.
