### ISSUE TITLE
Distribution Release big lack

### ISSUE THREAD

**Issue by Vacxe** [microsoft/appcenter-cli#737]
Have a good day. I struggling with uploading app with the following command

```appcenter distribute release```

Especially with ```--group``` specification.

I have a case when necessary add multiple groups. For avoiding additional calls of 

`appcenter distribute releases add-destination`

But with the current implementation is possible only for single group.

---

Could you help me with this stuff? I think that this feature is really important in API.

Cheers!

**Comment by RAM237** [comment]
I understand you want to avoid additional calls, but for those who can admit it, possible solution can be found here in comments, I guess:
#662

**Comment by Vacxe** [comment]
Thanks for your response @RAM237 and that exactly what I doing. But will be better to have a more elegant way to do it I think so. Does it possible to add this functionality to main library for avoiding crutches?

Cheers!

**Comment by phillipleblanc** [comment]
Thanks for your input on this, to make it easier to track interest please upvote the linked issue and I will close this one.

Closing as a duplicate of #662
