### ISSUE TITLE
look for test-cloud.exe in the build directory

### ISSUE THREAD

**Issue by dansiegel** [microsoft/appcenter-cli#738]
# Description

The App Center CLI currently has a hard requirement on  UI Test projects that rely on the older csproj format. In these projects a packages folder is created with the resources for each NuGet including the tools with the test-cloud.exe. As a result for those using the newer SDK style projects this requires some work arounds and specifying the location of the test-cloud.exe. If the test-cloud.exe cannot be found in this folder, the CLI should look for it in the build directory where the UI Test project assemblies are located.

**Comment by owenniblock** [comment]
The corresponding work for UITest has been done (the file should now be copied to your build folder): https://www.nuget.org/packages/Xamarin.UITest/3.0.8-dev1
