### ISSUE TITLE
CI/CD appcenter cli usage

### ISSUE THREAD

**Issue by pwillies** [microsoft/appcenter-cli#741]
Hi Guys,

Some others are asking for better documentation, and I support that request. I have a specific question that I'm unable to find the answer to. I'm using Azure DevOps to run our CI/CD pipeline, and attempting to use this command to upload UWP symbols to AppCenter:

`appcenter crashes upload-symbols --appxsym <arg>` 
where that arg is: `Path to an appxsym file containing UWP symbols.`

So the cli requires a Path to a single appxsym file. Problem is that Azure DevOps works with wildcards, so it seems I have to construct four fully-qualified paths (one per architecture) to use the cli. Is there a sample of how this can be done?

Thanks!

**Comment by phillipleblanc** [comment]
Hey @pwillies - is your question around how to construct the path to a single appxsym, or how you can automate this in a CI/CD pipeline?

**Comment by pwillies** [comment]
Hi @phillipleblanc - the question is about the mismatch between the Azure DevOps way of handling files (wildcarding) and the appcenter cli way of handling files (full path). 

So it's a bit of both - the appcenter cli is offered as something to use on an Azure DevOps pipeline. But in order to do that, you need to download the multiple architecture-specific appxsym files (easy to do using wildcards), but then you have to somehow figure out their specific filenames in order to upload them using the appcenter cli (hard to do)

Since it is offered as something to use (here: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli), I presume Microsoft already did it, and if so, a sample would be nice...

**Comment by yujincat** [comment]
Hi @pwillies , apologies for late reply. 

Unfortunately, we do not have a specific sample to handle this case. 

Have you considered [using App Center distribute pipeline directly](https://docs.microsoft.com/en-us/appcenter/distribution/vsts-deploy)? You might already have checked, but in case it helps.

**Comment by apwillies** [comment]
Thanks @yujincat. I will look into that at some point. Currently we use TestFlight, GooglePlay and the Microsoft Store directly to distribute our apps - just feels simpler that way and it's already running. But using AppCenter is something we can investigate if we have other drivers.
