### ISSUE TITLE
Allow "appcenter distribute release" to perform silent upload (--notify-testers false)

### ISSUE THREAD

**Issue by RAM237** [microsoft/appcenter-cli#746]
Need option to be able to perform quiet upload of the release (i.e. make available for download for everyone in the specified group, but **do not send email notification**).

Something like  
`appcenter distribute release <...> --notify-testers false`  
(or `0`).

This was really handy in HockeyApp API to be able to upload and decide the above in one line command. Now you either have to do a lot of useless parsing (going the plain API way), or forced not to use this (going appcenter-cli way) - this is unfriendly :(

p.s. as far as I understand, it is somehow near #692 , in terms of ~~porting~~ bringing back additional options of distribution API call https://openapi.appcenter.ms/#/build/builds_distribute (**mandatoryUpdate** = *#692* and **notifyTesters** = *current one*).

**Comment by RAM237** [comment]
Ah, sorry, it seems I was wrong in my "p.s.", builds are not relevant here, since the query is about releases! That means, we do not have a workaround at all, and this is one more feature that we lost when Microsoft forced us migrating from HockeyApp into AppCenter.

This is important for our company's CI process, and such policy from MS side (to make us to migrate not porting the tools we used to use) makes me really upset.

**Comment by anywherepilot** [comment]
`distribute release` has a flag `--silent` which does this. Have a look at the help: `appcenter help distribute release`.

**Comment by anywherepilot** [comment]
@RAM237 I'll close this now since it already exists. Feel free to comment if you have further related questions or suggestions!

**Comment by RAM237** [comment]
Cool, thanks! I was still on appcenter version 2.1.2 and it didn't have those `--silent` switch.
Now upgraded to 2.3.3 and I am really happy it is there!

Appreciate your help on this!
