### ISSUE TITLE
Providing --build-number argument during CLI distribute release for iOS .ipa upload does nothing

### ISSUE THREAD

**Issue by swburchill** [microsoft/appcenter-cli#747]
When using appcenter.cmd to upload builds, I am unable to set the build number in the store. It continues to be set automatically.

I can see that providing the --build-number argument on the commandline does something:

    "cli-command-name": "distribute release"
  },
  "body": "{\"build_number\":\"273001\"}"

but the build in the appcenter website still shows the autogenerated/autoincremented number.

Shouldn't the user provided CLI value take priority when it exists?

**Comment by jp-andre** [comment]
HI @swburchill 
Yes, this is expected behavior. We extract the data from the `.ipa` file for iOS. You can't change it using API or command line.

**Comment by paritosh-yadav** [comment]
Hi @jp-andre , then what's the significance of **--build-number** & **--build-version**

**Comment by DmitriyKirakosyan** [comment]
Hi @jp-andre build-number and build-version properties are used to identify a version and number of App Center releases and may not be related to the distributed application version.
Also note that these parameters are required when you upload msi, zip, pkg and dmg files.
