### ISSUE TITLE
request is deprecated

### ISSUE THREAD

**Issue by Richienb** [microsoft/appcenter-cli#761]
The `request` package has been deprecated. A replacement such as `got` should be used.

Raw install output:

```
warning appcenter-cli > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning appcenter-cli > azure-storage > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning appcenter-cli > ms-rest > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning appcenter-cli > unzipper > fstream > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface 
has changed to use Promises in 1.x.)
```

**Comment by jp-andre** [comment]
Thanks. We're working on updating our dependencies at the moment.

**Comment by casal033** [comment]
Has there been progress made on this?

**Comment by DmitriyKirakosyan** [comment]
Hi @martin-cech , we are keeping an eye on the issue and PR in the original repo. Also, there is filed issue in active fork from cypress-io: https://github.com/cypress-io/request/issues/27. Hopefully they would able to address the issue soon and we will move to their fork.

Another option is to replace `request` with `got` as it was initially proposed and I agree that it would be a good idea. However, it will require careful testing.

Also note, that the severity of the vulnerability is "Moderate".

**Comment by DmitriyKirakosyan** [comment]
`request` was removed in version 3.0.0. Closing.
