### ISSUE TITLE
Unclear error when uploading large release notes files.

### ISSUE THREAD

**Issue by funkybaboon** [microsoft/appcenter-cli#768]
I do have a large `changelog.md` file which I usually upload with 

`$ appcenter distribute release --app $APPCENTER_APP_ID --file $APPCENTER_FILE_TO_UPLOAD --group Collaborators --release-notes-file changelog.md`

Now I'm getting an error `Error: failed to set the release notes`. Nowhere does this error or the documentation or the source code say what the actual problem is. 

I logged into Appcenter and did a manual release. There I found out that the maximum size of the release notes should be 5000 characters. 

Suggestion: Change the error message to include a hint to the 5000 character limit, or do a precheck of the release notes file.

**Comment by mosofsky** [comment]
Please make the error message more specific.  I ran into this problem too.

**Comment by DmitriyKirakosyan** [comment]
Error output was improved in https://github.com/microsoft/appcenter-cli/pull/1278. Closing.
