### ISSUE TITLE
Can "appcenter codepush release-xxx" return version-number

### ISSUE THREAD

**Issue by sveinare** [microsoft/appcenter-cli#777]
For use in BitBucket pipelines / scripting it would be great to get the version-number as a return-value. This way we can ensure that the right version is promoted later in the workflow.

**Comment by leviadam** [comment]
This is super critical for a stable CI. Plz add it.

**Comment by janziemba** [comment]
You can use this command to retrieve the latest version number: https://github.com/microsoft/appcenter-cli/issues/707#issuecomment-557298743

**Comment by DmitriyKirakosyan** [comment]
Hi guys, thank you for this report and sorry for keeping this unanswered. Let's keep the feature progress in #707 and close this one as a duplicate. Thanks.
