### ISSUE TITLE
[feature request] All infrastructure as code like k8s / connect a repo

### ISSUE THREAD

**Issue by softlion** [microsoft/appcenter-cli#804]
It would be good to be able to create an application and setup all the settings using a single yaml file, instead of multiple incomplete command parameters. Like kubernetes (k8s) and helm are able to do for a cluster.

- it would simplify the command line, as only one command will be enough for tons of operations
- it would simplify updates, as changing one setting in the yaml and using the same creation command would instead update the app with one setting
- you would be able to export a whole appcenter app configuration in one file, and copy it to a new app for example.
- an appcenter app configuration can be versioned
- dry run can be easily supported

**Comment by ajaykn** [comment]
Thanks @softlion for raising a feature request.
Currently we may not prioritize this due to ongoing activities. But we will keep this open to keep tracking the interests.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
