### ISSUE TITLE
Clarify how to get the right app name

### ISSUE THREAD

**Issue by anywherepilot** [microsoft/appcenter-cli#812]
Apps have a display name and a name. The name is in the URL in the portal, and you also get it by running `appcenter apps list`. Using `appcenter apps set-current` you don't have to bother with providing the app name to every command.

Some customers pointed out the current description for the app name is not clear enough. The current description is:

`Specify app in the <ownerName>/<appName> format`

We should explain how to obtain those values. A reference to the `apps list` command seems most appropriate. Let's put this in both the help text for `--app` (which is in only one place and would hit all commands at once) and in the FAQ. Do we have an FAQ?

**Comment by rohan-kulkarni-25** [comment]
hey @anywherepilot will like to work on this can you please help me in getting started

**Comment by DmitriyKirakosyan** [comment]
Hi @rohan-kulkarni-25 

Thank you for your interest in contributing to this repo!

As for the issue, here is the place of such description: https://github.com/microsoft/appcenter-cli/blob/d7edaf551748c2e1c036cba795a5260bbf284f2e/src/util/commandline/app-command.ts#L17

You will need to modify this text to include an additional information on how to obtain the app name, as anywherepilot pointed out in his description.
Please, find the command that shows this description and verify that your change works. Check if any other related command requires such description as well.

**Comment by rohan-kulkarni-25** [comment]
Hey, @DmitriyKirakosyan Thanks for the help as I am trying to understand the code and also getting it slowly will like to know what description should we provide on how to get the app name ?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
