### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by miqmago** [microsoft/appcenter-cli#818]
Maybe could add a configuration file where some settings could be specified (per folder).
I'm thinking mainly in app name which would overwrite global settings so we can switch project without worrying about changing app name.
Maybe /additionally could be read from package.json file (cordova / react / capacitor).

**Comment by serhiiharbo** [comment]
+1

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
