### ISSUE TITLE
Codepush command can't find my pbxproj files

### ISSUE THREAD

**Issue by danidev-tempus** [microsoft/appcenter-cli#851]
Hi!

I'm running on this issue. My app's name on appcenter is named `my-app`, but in my project's tree the files are under `ios/MyApp`. 

I managed to do a codepush release a copule of weeks ago, by indicating where the `Info.plist` was with `--plist-file ios/MyApp/Info.plist` without issues, but now I'm getting the following error:

I can't find what's the config setting indicate where's my .xcodeproj in the documentation.

```
appcenter codepush release-react -a MyCompany/my-app --plist-file ios/MyApp/Info.plist
Detecting ios app version:

Error: Command 'codepush release-react -a MyCompany/my-app --plist-file ios/MyApp/Info.plist' failed with exception "Unable to find either of the following pbxproj files in order to infer your app's binary version: "ios/my-app.xcodeproj/project.pbxproj", "ios/project.pbxproj"."
```

Thanks in advance.

**Comment by garrettjoecox** [comment]
Running into this as well, it would be nice to be able to provide an option similar to `--plist-file` to specify where the pbxproj is

**Comment by danidev-tempus** [comment]
Hi, @garrettjoecox 

I fixed my issue by making the "main" package name in the package.json match the ios/android source folders. Hope it helps.

**Comment by giangdhwhtbr** [comment]
--plist-file is just to specify where the plist file is located
for the project.pbxproj file, I had to add a new option to specify the path to project.pbxproj file

https://github.com/giangdhwhtbr/appcenter-cli/blob/bf9c9328bb1fc8a7aebf0db2857cb9889f3674d9/src/commands/codepush/release-react.ts#L61

**Comment by federico-whitespectre** [comment]
> Hi, @garrettjoecox
> 
> I fixed my issue by making the "main" package name in the package.json match the ios/android source folders. Hope it helps.

For that you can use this param:
`--xcode-project-file=ios/<ReactNativeiOSProjectName>.xcodeproj`

**Comment by federico-whitespectre** [comment]
> Running into this as well, it would be nice to be able to provide an option similar to `--plist-file` to specify where the pbxproj is

For that you can use this param:
--xcode-project-file=ios/<ReactNativeiOSProjectName>.xcodeproj

**Comment by DmitriyKirakosyan** [comment]
This feature is already [implemented](https://github.com/microsoft/appcenter-cli/pull/1497). Closing.
