### ISSUE TITLE
Not found :Correlation ID

### ISSUE THREAD

**Issue by phanthelam** [microsoft/appcenter-cli#869]
I'm facing the new errors :
Error: Command 'codepush release-react -a {onwername}/{appname} -d Production' failed with exception "Not found. Correlation ID: 7fc49f82-dd05-4a54-9d8c-c9dda93c1bb2"
- I tried run command "appcenter apps list" and other appcenter CLI , All work fine .
Any have a solution for this ???

**Comment by anotherandersson** [comment]
I’m experiencing something similar after running:

`appcenter distribute release -f <file> -a <app> --token <token> --quiet --disable-telemetry --debug --group <distribution-group> --silent
`

**Error returned:** 

- Response status code: 404
- Body: {"message":"Not found. Correlation ID: <id>”,”statusCode":404,"code":"Not Found"}

Using version 2.5.2.

**Comment by yujincat** [comment]
@phanthelam can you check the ownername is correctly set? It should not be the display name, but the actual name. If you want to check the ownername of the app, `appcenter apps list` and it should show in a form of `<ownername>/<appname>`.

**Comment by yujincat** [comment]
@anotherandersson it might be unrelated issue as a different command

**Comment by phanthelam** [comment]
@yujincat  thanks bro, It's owner name not display name :(

**Comment by yujincat** [comment]
@phanthelam I can see that the latest command you triggered succeeded with the right parameter. :-D Let me know if you still have the issue!

**Comment by NedyUdombat** [comment]
Hi @yujincat I am facing this same issue on Appcenter on an android app with react-native.
It started after I had to re-authenticate the Appcenter application with Github.

```
...
File upload succeed.
Upload '/Users/runner/work/1/a/build' to file container: '#/10375163/build'
Associated artifact 42 with build 61
##[section]Async Command End: Upload Artifact
##[section]Finishing: Publish build
##[section]Starting: Create distribution
==============================================================================
Task         : App Center distribute
Description  : Distribute app builds to testers and ***s via Visual Studio App Center
Version      : 3.173.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
==============================================================================
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
##[error]"{\"message\":\"Not found. Correlation ID: 2537050c-2702-4d1c-8f6d-429aa164a22b\",\"statusCode\":404,\"code\":\"Not Found\"}"
http response code: 404
##[section]Finishing: Create distribution
##[section]Starting: Checkout git-f1fc1215-869e-4364-8a7c-a612b04f47e3@dev to s
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Cleaning any cached credential from repository: git-f1fc1215-869e-4364-8a7c-a612b04f47e3 (ExternalGit)
##[section]Finishing: Checkout git-f1fc1215-869e-4364-8a7c-a612b04f47e3@dev to s
##[section]Starting: Finalize Job
Cleaning up task key
Start cleaning up orphan processes.
Terminate orphan process: pid (7467) (java)
Terminate orphan process: pid (7441) (java)
Terminate orphan process: pid (6077) (java)
##[section]Finishing: Finalize Job
##[section]Finishing: Build
...
```

Please do you have any idea on how to fix this?

**Comment by xuangong** [comment]
I met the same issue. And found I changed the username in appcenter portal, which caused username dismatched. I got fixed now.

**Comment by xuangong** [comment]
> Hi @yujincat I am facing this same issue on Appcenter on an android app with react-native.
> It started after I had to re-authenticate the Appcenter application with Github.
> 
> ```
> ...
> File upload succeed.
> Upload '/Users/runner/work/1/a/build' to file container: '#/10375163/build'
> Associated artifact 42 with build 61
> ##[section]Async Command End: Upload Artifact
> ##[section]Finishing: Publish build
> ##[section]Starting: Create distribution
> ==============================================================================
> Task         : App Center distribute
> Description  : Distribute app builds to testers and ***s via Visual Studio App Center
> Version      : 3.173.0
> Author       : Microsoft Corporation
> Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
> ==============================================================================
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> (node:8794) Warning: Use Cipheriv for counter mode of aes-256-ctr
> ##[error]"{\"message\":\"Not found. Correlation ID: 2537050c-2702-4d1c-8f6d-429aa164a22b\",\"statusCode\":404,\"code\":\"Not Found\"}"
> http response code: 404
> ##[section]Finishing: Create distribution
> ##[section]Starting: Checkout git-f1fc1215-869e-4364-8a7c-a612b04f47e3@dev to s
> ==============================================================================
> Task         : Get sources
> Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
> Version      : 1.0.0
> Author       : Microsoft
> Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
> ==============================================================================
> Cleaning any cached credential from repository: git-f1fc1215-869e-4364-8a7c-a612b04f47e3 (ExternalGit)
> ##[section]Finishing: Checkout git-f1fc1215-869e-4364-8a7c-a612b04f47e3@dev to s
> ##[section]Starting: Finalize Job
> Cleaning up task key
> Start cleaning up orphan processes.
> Terminate orphan process: pid (7467) (java)
> Terminate orphan process: pid (7441) (java)
> Terminate orphan process: pid (6077) (java)
> ##[section]Finishing: Finalize Job
> ##[section]Finishing: Build
> ...
> ```
> 
> Please do you have any idea on how to fix this?

I met the same issue. And found I changed the username in appcenter portal, which caused username dismatched. I got fixed now.

**Comment by feruzm** [comment]
> I got fixed now.

@xuangong how?

**Comment by Piffo** [comment]
I've the same issue.

I've checked the matching between Appcenter owner name and the one set in Azure release.yml file. They arae the same.
Someone else ahas some other fix to try?

**Comment by AnastasiaKubova** [comment]
Hi, @Piffo ! Thanks for getting in touch with us! Could you please clarify which command is causing this issue?

**Comment by Piffo** [comment]
Hi @AnastasiaKubova, the issue appear when the Azure sys launch the "Deploy **/*.ipa to Visual Studio App Center" command.

**Comment by AnastasiaKubova** [comment]
@Piffo does this only happen on Azure? If you try to perform this command locally, does it work correctly?

**Comment by Piffo** [comment]
@AnastasiaKubova Do you mean to run the command on AppCenter CLI?
Otherwise, I don't know how to run locally this command.

**Comment by AnastasiaKubova** [comment]
@Piffo, could you please share the full error which you get with the correlation id value?

**Comment by Dat0318** [comment]
i have the same issues.
can you check it for me @AnastasiaKubova , thanks
[Error]  Not found. Correlation ID: a44d52bb-1e80-46bf-b1b8-4453b2d050cd
i have error when i rename application with command line code-push rn JoJoAndorid JoJoAndroid and give this error.
i try to make application run but not found and i can do anythings with app.

**Comment by Jamminroot** [comment]
Hey @Dat0318, I've checked the correlation ID you provided, and it looks like server reported lack of permissions to perform operation.
Can you check whether CLI works now, and provide fresh Correlation ID if it does not?

**Comment by Dat0318** [comment]
Thanks for your help. It have run since I wore comment for you after one
day. It run automatically.

**Comment by Jamminroot** [comment]
Glad to hear that!
Feel free to reopen the issue (or open another one) whether you feel like having us assist you.

**Comment by lilvip9999** [comment]
{\"message\":\"Not found. Correlation ID: a17a3a4b-cf90-4c58-b6a3-f7ba47c66fc7\",\"statusCode\":404,\"code\":\"Not Found\"}"

I've the same issue
@Jamminroot  : can u help me

**Comment by Jamminroot** [comment]
Hey @lilvip9999, sure. I've checked logs, and it looks like further troubleshooting would involve exchange with sensitive information. There seem to be an issue earlier with your application (perhaps ownership transfer or something like that), which now causes an error like this (I removed actual values):
>"Could not find app for user ID '{USER_ID_REMOVED}' and slug name '{APP_NAME_REMOVED}"

Troubleshooting would likely require sharing some sensitive information, so you can open an intercom ticket through the portal (top-right corner):

![image](https://user-images.githubusercontent.com/6387654/115006419-e9961e80-9eb9-11eb-82d6-721716b031c4.png)

**Comment by lilvip9999** [comment]
@Jamminroot  : yes, my project just changed ownership transfer, and login new apple account, and now can't create Release after run Pipeline, it show error above.

**Comment by Jamminroot** [comment]
Yeah, makes sense. Reach out to folks in intercom, they should be aware how to resolve the problem iirc.

**Comment by sahanah-ganesh** [comment]
Going into Distribute Builds from App Center and removing the Collaborator's tag and then re-adding Collaborator's from the destination search and saving solved this issue for us. 

<img width="537" alt="Screen Shot 2021-07-09 at 5 08 56 pm" src="https://user-images.githubusercontent.com/46799971/125038110-5ba48b00-e0d8-11eb-93cc-82c555458cd1.png">

**Comment by juliancorrea** [comment]
I realized this issue when I had transferred the app to organization... Deactivate, save, and activate the Distribute builds solved the problem.

**Comment by chenop** [comment]
Here is what AppCenter support send me about this issue:

_ Could you please open the branch configuration, disable the Distribution service and click on "Save". Then open the branch configuration again and enable Distribution service, then select the distribution group from the drop down menu and click on "Save & Build".
_

**Comment by ciarancolgan** [comment]
@Jamminroot same issue happening for us today, repeated deployment attempts, even with code that deployed successfully a few days ago. No changes to ownership, and we are pushing via the CLI (from ADO) so nothing to change in AppCenter itself I believe, so i dont think any of the fixes in the threads above applies to us. Would you be able to give us more details using the correlation id below? Many thanks! 

Error: {"message":"Not found. Correlation ID: f9a44ba0-fce3-41b5-b32f-cea00db60d84","statusCode":404,"code":"Not Found"}

**Comment by Jamminroot** [comment]
I am no longer maintaining AppCenter SDKs and CLI. @DordeDimitrijev, can you have a look?

**Comment by ciarancolgan** [comment]
Thanks, never mind, I'll contact App Center support and leave you in peace! :)
