### ISSUE TITLE
~1% failure with "appcenter build branches show"

### ISSUE THREAD

**Issue by pgilmorepf** [microsoft/appcenter-cli#872]
My build system executes 2 commands back to back:
appcenter build queue --app $AppName --branch $BranchName --quiet -d
appcenter build branches show -b $BranchName -a $AppName --quiet --output json

the "build branches show" fails about 1% of the time, randomly, with the error:
"Error: the Branch Builds request was rejected for an unknown reason"

I updated my script to detect this failure, and immediately do this:
appcenter build branches show -b $BranchName -a $AppName --debug --output json

Unfortunately, that succeeds, and displays success with valid info.

My best guess:
The immediate"build branches show" command can fail on some transient error. Retrying on the "build branches show" step seems to have fixed it for me so I can't provide the described --debug log for the failure because I've never seen it fail twice in a row.

**Comment by yujincat** [comment]
It seems like a transient issue, can you provide us more information when you have more details on this?

**Comment by jp-andre** [comment]
This may be related to some internal timeout issue we were experiencing before. I'm keeping this open as we should be able to add a retry logic around such network calls. If there's already a retry, maybe improve it :)

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for retry logic in the next year, I'm closing the issue.
