### ISSUE TITLE
Unknown argument --disabled

### ISSUE THREAD

**Issue by jdnichollsc** [microsoft/appcenter-cli#876]
Executing below command for Patching Update Metadata:
```console
appcenter codepush patch -a <ownerName>/MyApp-iOS Staging --disabled
```
Returns an error:
```console
Error: Command 'codepush patch -a <ownerName>/MyApp-iOS Staging --disabled true' failed with exception "Unknown argument --disabled"
```

Thanks in advance

**Comment by Krasavinigor** [comment]
Hello @jdnichollsc!
Sorry for delay. Thank you for reporting! 
Unfortunately, I couldn't get this error. Could you please provide a test project with this issue or repro steps?

**Comment by jdnichollsc** [comment]
this is an issue with the cli, I'm not running my project locally

**Comment by Krasavinigor** [comment]
Hi @jdnichollsc!

I couldn't reproduce this issue, command `appcenter codepush patch -a <ownerName>/MyApp-iOS Staging --disabled` works correctly. Please be careful when you input command, also use only English letters.

**Comment by Krasavinigor** [comment]
@jdnichollsc 
Please let me know if it's helpful for you or you have any questions.

**Comment by jdnichollsc** [comment]
Check this screenshot :)
![image](https://user-images.githubusercontent.com/2154886/84958189-7158a400-b0c2-11ea-9dd3-63089b15eca8.png)

Thanks for your help!

**Comment by jdnichollsc** [comment]
Ok, it was fixed after updating the **appcenter-cli** npm package to the version 2.5.4

Thanks!
