### ISSUE TITLE
Option to set release note in `build queue`

### ISSUE THREAD

**Issue by mcchrish** [microsoft/appcenter-cli#888]
<img width="524" alt="Screen Shot 2020-05-22 at 6 27 19 AM" src="https://user-images.githubusercontent.com/7200153/82612386-52670f00-9bf5-11ea-9fc3-bd742cda7259.png">

Is there a way to set the release notes in `build queue` command or some way to edit it? Would be nice have this feature.

**Comment by yujincat** [comment]
Currently we do not have a command that can set the release note. 

Instead you can consider using [openapi](https://openapi.appcenter.ms/#/build/builds_distribute) for distributing a build with a release note. See [App Center openapi documentation](https://docs.microsoft.com/en-us/appcenter/api-docs/). 

I will label this as a feature request :-)

**Comment by chandan-g-bhagat** [comment]
API for distributing build to store is returning error. I tried it many times and have been getting 500 Error code. Is  there any update in this feature-request?

**Comment by chandan-g-bhagat** [comment]
> API for distributing build to store is returning error. I tried it many times and have been getting 500 Error code. Is there any update in this feature-request?

This one is resolved.

**Comment by chandan-g-bhagat** [comment]
Any update on this feature request? @yujincat 

> Currently we do not have a command that can set the release note.
> 
> Instead you can consider using [openapi](https://openapi.appcenter.ms/#/build/builds_distribute) for distributing a build with a release note. See [App Center openapi documentation](https://docs.microsoft.com/en-us/appcenter/api-docs/) for more details.
> 
> I will label this as a feature request :-)

**Comment by yujincat** [comment]
Hi @chandan-g-bhagat , apologies for the late reply. 
About the feature request, we do not have any plan on this yet. 
You can check out our current planning strategy here: https://github.com/microsoft/appcenter#planning

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
