### ISSUE TITLE
appcenter distribute release with 404 code

### ISSUE THREAD

**Issue by phantrungphat** [microsoft/appcenter-cli#891]
Hi all, 
I have just approached appcenter cli shortly, so I am facing to this error and I don't know how to fix it.
I am trying to upload my APK file to appcenter and I don't understand why I am getting the "**failed to create release upload for MyAPK**" error.
**I ran:** 
appcenter distribute release -f .\build\app\outputs\flutter-apk\app-release.apk -g Collaborators --app phatphan/chatapp --debug
**I got error:** 
Using appcenter-cli version: 2.5.3
| Loading prerequisites...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/phatphan/chatapp/distribution_groups/Collaborators/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.3 NodeJS/v12.10.0 win32/10.0.17763",
    "x-api-token": "XXXXX",
    "internal-request-source": "cli",
    "diagnostic-context": "XXXXX",
    "cli-command-name": "distribute release"
  },
  "body": null
}
/ Loading prerequisites...Response status code: 404
Body: {"message":"Not found. Correlation ID: XXXXX","statusCode":404,"code":"Not Found"}
| Creating release upload...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/phatphan/chatapp/release_uploads",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.3 NodeJS/v12.10.0 win32/10.0.17763",
    "x-api-token": "XXXXX",
    "internal-request-source": "cli",
    "diagnostic-context": "XXXXX",
    "cli-command-name": "distribute release"
  },
  "body": null
}
| Creating release upload...Response status code: 404
Body: {"message":"Not found. Correlation ID: XXXXX","statusCode":404,"code":"Not Found"}
Error: failed to create release upload for .\build\app\outputs\flutter-apk\app-release.apk

**Comment by jp-andre** [comment]
Hi,

It is likely due to an invalid app name (I could not find the one you mentioned).
Try running `appcenter apps list` to figure out the exact name as required by the CLI.

Best regards

**Comment by phantrungphat** [comment]
I tried it and it ran without error. Thank you for the helpful responses @jp-andre !!!

**Comment by jp-andre** [comment]
Cool! I will close this Issue then :)

**Comment by bobrosoft** [comment]
I had that error because of old `appcenter-cli` v2.5. Updating it fixed the issue.
