### ISSUE TITLE
Install an App via appcenter-cli on your device

### ISSUE THREAD

**Issue by goncalosoares** [microsoft/appcenter-cli#896]
Hey :-)

I am working in Test Automation.

Is it possible to download and install a build on a device (let's say macOs) using appcenter-cli to run tests on the app?

**Comment by jp-andre** [comment]
Hi @goncalosoares

Sorry for the late reply. If you mean install and run automated tests in App Center Test, then, yes, the CLI is the tool for you. Type `appcenter help test` for details about the commands, and refer to [App Center Test docs](https://docs.microsoft.com/en-us/appcenter/test-cloud/getting-started).

If you mean something else, then I don't think this CLI what you are looking for.

I hope this answers your question.

**Comment by phillipleblanc** [comment]
Closing this issue
