### ISSUE TITLE
Support app bundle (.aab) file uploads to Appcenter to internal groups

### ISSUE THREAD

**Issue by shrikanthkr** [microsoft/appcenter-cli#900]
As appcenter has started supporting distribution of App Bundles for android, is there a way to extend the same from appcenter-cli?

**Comment by jp-andre** [comment]
Hey @shrikanthkr

The CLI can publish .aab files to Google Play store, just like App Center portal. If you're asking about distributing to groups, then this is not possible due to the very nature of app bundles (they can't be installed directly on a device).

**Comment by phillipleblanc** [comment]
As JP noted, it is not possible to distribute an .aab file to a group, only to the Google Play store.

**Comment by sanjaykumarm** [comment]
@phillipleblanc As you are telling that due to .aab nature, appcenter could not support distribution to group, then why it is possible to distribute to groups from their portal(https://appcenter.ms/) ? If we see internal mechanism, it is same process. Here we are uploading build using appcenter-cli as command line and where we are selecting .aab file from computer directory. Can you please explain it in more details ?

**Comment by DmitriyKirakosyan** [comment]
Hi @sanjaykumarm , the distributing `.aab` files is now supported via CLI. Please share more info about the failure if it doesn't work for you.

**Comment by sanjaykumarm** [comment]
@DmitriyKirakosyan Yes here is the error message we are getting:

`"Error: Files of type '.aab' can not be distributed to groups"`

**Comment by sanjaykumarm** [comment]
> @DmitriyKirakosyan Sorry for inconvenience, now it works actually, thank you for your help.

**Comment by chetakbhimani001** [comment]
@DmitriyKirakosyan @sanjaykumarm Can you share the CLI command for the same? Currently getting "Error: Files of type '.aab' can not be distributed to groups"

**Comment by vincentcastagna** [comment]
@DmitriyKirakosyan 
Would this work with `AppCenterDistribute@3` task for **AzurePipelines** ? Does it use the latest appcenter CLI ?

**Comment by DmitriyKirakosyan** [comment]
Hi @chetakbhimani001 , please update appcenter-cli to the latest version (2.10.10, or at least >= 2.10.4) and the error should gone.

**Comment by DmitriyKirakosyan** [comment]
Hi @vincentcastagna , yes the AzurePipelines task should work with `aab` files. Please let me know if it doesn't.

**Comment by vincentcastagna** [comment]
@DmitriyKirakosyan yes, just tested and it works well. Ty !
