### ISSUE TITLE
How to send environment variables when queuing builds?

### ISSUE THREAD

**Issue by anik786** [microsoft/appcenter-cli#946]
How to I send environment variables for AppCenter builds using the CLI.

I want to send an environment variable such as "TENANT=customer1".

I am using a command similar to:

```
appcenter build queue -b master --env TENANT=customer1 --token=XXX
```

However I get the error:
```
Error: TENANT=customer1 is not valid environment name
```
What am I doing wrong?

To give some context, I want to create a build system for a white-label app. I configure which app to use based on an environment variable. We expected to create thousands of different versions of the same app.

**Comment by anywherepilot** [comment]
The `env` parameter is for choosing which environment of App Center (the production one or our internal test one) to connect to. It is not meant for passing any variables. I don't think you can even set these kinds of variables on a per build basis through the website. You have to modify your branch build configuration.

The CLI only has read support for branch related items. To modify build configurations you will need to use the API directly.

**Comment by anik786** [comment]
We decided to create one app per a tenant to deal with this situation.
Thanks for your help.

**Comment by billnbell** [comment]
You can programmatically add keys, and VERSIOn, etc to AppCenter builds. If you have curl and jq this is the way:

export DATA=`curl -sX GET "https://api.appcenter.ms/v0.1/apps/Exclusive-Resorts/IOSBrowserstack/branches/stage/config" -H "Content-Type: application/json" -H "X-API-Token: $APPSERVERAPITOKEN" |  jq '.environmentVariables += [{"name": "VERSION", "value":"10222"}]' -c`

curl -X PUT -d "$DATA" "https://api.appcenter.ms/v0.1/apps/Exclusive-Resorts/IOSBrowserstack/branches/stage/config" -H "Content-Type: application/json" -H "X-API-Token: $APPSERVERAPITOKEN"

curl -sX GET "https://api.appcenter.ms/v0.1/apps/Exclusive-Resorts/IOSBrowserstack/branches/stage/config" -H "Content-Type: application/json" -H "X-API-Token: $APPSERVERAPITOKEN" | jq
