### ISSUE TITLE
How to move sourcemap file after hermes to sourcemapOutputDir

### ISSUE THREAD

**Issue by ryanypm** [microsoft/appcenter-cli#956]
![image](https://user-images.githubusercontent.com/7519919/85397039-6c459a00-b585-11ea-84af-132c07addc35.png)

code-push will upload the sourcemap after hermes together.

**Comment by ryanypm** [comment]
I added a pr, want to confirm whether it can be done like this?
[https://github.com/microsoft/appcenter-cli/pull/958](url)

**Comment by yujincat** [comment]
The discussion about the PR should be placed in the PR, so closing this issue. 
@ryanypm Could you please bring up the question in the PR?
