### ISSUE TITLE
Not able to create new release when access token is given using environment variable

### ISSUE THREAD

**Issue by sameeragrawal** [microsoft/appcenter-cli#973]
Version 2.6.1

I am trying to publish a new version of app to AppCenter, and the distrubute command fails with error:

> Error: failed to create release upload for ....ipa. Missing valid authentication token. Correlation ID: 06e24f3a-a11d-44ca-b100-4c75978d56ef

The same command works with CLI version 2.5.4 (verified by downgrading)

Auth token was provided using environment variable in both cases.

**Comment by sameeragrawal** [comment]
label:Distribute

**Comment by jp-andre** [comment]
This could be a side effect of the large changes introduced in #909. We'll circle back with the authors.
