### ISSUE TITLE
Timeout while publishing app to appcenter

### ISSUE THREAD

**Issue by balrajo** [microsoft/appcenter-cli#982]
We were using V2.5.3 and it works gr8. But when we upgraded to this latest version, as started getting timeout. Not sure if there is any URL change or anything.

**Comment by anywherepilot** [comment]
The distribution behavior changed recently, yes. Can you be more specific about what you are doing and whether you always experience timeouts?

**Comment by balrajo** [comment]
I am trying to distribute iOS and Android app using appcenter. But when I do so, I get "Timedout" if version of appcenter-cli is 2.6.X, though it work fine with V2.5.3

**Comment by Px7-941** [comment]
Error: Command 'distribute release --app MyOrg/MyApp --group MyGroup --file myapp-Signed.apk' failed with exception "request to https://api.appcenter.ms/v0.1/apps/MyOrg/MyApp/uploads/releases failed, reason: connect ETIMEDOUT 52.138.116.79:443"

Tested with appcenter-cli 2.6.5

**Comment by balrajo** [comment]
@anywherepilot Can you please look into the issue urgently?

**Comment by Px7-941** [comment]
I analyzed the problem a little more and narrowed down the cause. 
My guess is that with the new parallel upload of data, the company proxy is no longer being used. 
Outside a company network the upload works fine.

**Comment by andysousa** [comment]
@Jamminroot this still exists in 2.6.5

**Comment by Px7-941** [comment]
@Jamminroot can you add the bug label. 
We use a local proxy cntlm or Squidman for authentication at the company proxy. The local proxy is then set in the system settings and for the command line. I hope this helps to analyse the problem.

**Comment by russelarms** [comment]
Sorry for the delay.
I suspect `node-fetch` might be the root of the proxy problem. For me, it works fine with whatever proxy I've tried, so I need detailed logs from someone who has this problem. @Px7-941 @balrajo @andysousa 
You will need to set `DEBUG="appcenter-cli:commands:*"` before the release command and share the output, e.g.:
```
DEBUG="appcenter-cli:commands:*" appcenter distribute release -f appRelease.apk -g publicGroupName
```
Remember to exclude sensitive data from logs.

Also, I need to know if you're using any environment variables for the proxy to work, such as _http_proxy_, _https_proxy_, etc.

**Comment by Px7-941** [comment]
@russelarms Here is the desired log and further information.

```bash
$ DEBUG="appcenter-cli:commands:*" appcenter distribute release --app MyOrg/MyApp --group MyGroup --file myfile-Signed.apk --debug true --token ******TOKEN******
Using appcenter-cli version: 2.6.7
  appcenter-cli:commands:distribute:release Checking for invalid parameter combinations +0ms
  appcenter-cli:commands:distribute:release Loading prerequisites +0ms
| Loading prerequisites...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/MyOrg/MyApp/distribution_groups/MyGroup/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.6.7 NodeJS/v14.2.0 darwin/19.6.0",
    "x-api-token": "******TOKEN******"
  },
  "body": null,
  "strictSSL": false,
  "agent": {
    "options": {
      "proxy": {
        "host": "localhost",
        "port": "3129",
        "protocol": "http:"
      }
    },
    "proxyOptions": {
      "host": "localhost",
      "port": "3129",
      "protocol": "http:"
    },
    "maxSockets": null,
    "requests": [],
    "sockets": [],
    "_events": {},
    "_eventsCount": 1
  }
}
/ Loading prerequisites...Response status code: 200
Body: []
  appcenter-cli:commands:distribute:release Checking for invalid parameter combinations with prerequisites +831ms
  appcenter-cli:commands:distribute:release Creating release upload +0ms
Command Failure at FetchError: request to https://api.appcenter.ms/v0.1/apps/MyOrg/MyApp/uploads/releases failed, reason: connect EPERM 52.138.116.79:443 - Local (192.168.1.141:53691)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/appcenter-cli/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:463:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Command 'distribute release --app MyOrg/MyApp --group MyGroup --file myfile-Signed.apk --debug true --token ******TOKEN******' failed with exception "request to https://api.appcenter.ms/v0.1/apps/MyOrg/MyApp/uploads/releases failed, reason: connect EPERM 52.138.116.79:443 - Local (192.168.1.141:53691)"
```
.bash_profile
```bash
export NODE_EXTRA_CA_CERTS=$HOME/cacert.pem
export http_proxy=http://localhost:3129
export https_proxy=http://localhost:3129
export all_proxy=http://localhost:3129
```
.npmrc
```bash
proxy=http://localhost:3129/
https-proxy=http://localhost:3129/
```
